-----------------------------------------------------
  0:           __NR_read 1+3s 1m
-----------------------------------------------------
Syscall param (syscallno) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param read(fd) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param read(buf) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param read(count) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param read(buf) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

-----------------------------------------------------
  1:          __NR_write 3s 1m
-----------------------------------------------------
Syscall param write(fd) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param write(buf) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param write(count) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param write(buf) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

-----------------------------------------------------
 60:           __NR_exit below
-----------------------------------------------------
-----------------------------------------------------
 97:      __NR_getrlimit 2s 1m
-----------------------------------------------------
Syscall param getrlimit(resource) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param getrlimit(rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param getrlimit(rlim) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

-----------------------------------------------------
160:      __NR_setrlimit 2s 1m
-----------------------------------------------------
Syscall param setrlimit(resource) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param setrlimit(rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param setrlimit(rlim) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

-----------------------------------------------------
247:         __NR_waitid 5s 0m
-----------------------------------------------------
Syscall param sys_waitid(which) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param sys_waitid(pid) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param sys_waitid(infop) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param sys_waitid(options) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param sys_waitid(ru) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

-----------------------------------------------------
247:         __NR_waitid (infop,ru) 5s 2m
-----------------------------------------------------
Syscall param sys_waitid(which) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param sys_waitid(pid) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param sys_waitid(infop) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param sys_waitid(options) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param sys_waitid(ru) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param waitid(infop) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param waitid(ru) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

-----------------------------------------------------
302:      __NR_prlimit64 (nop) 4s 0m
-----------------------------------------------------
Syscall param prlimit64(pid) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(resource) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(new_rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(old_rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

-----------------------------------------------------
302:      __NR_prlimit64 (set) 4s 1m
-----------------------------------------------------
Syscall param prlimit64(pid) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(resource) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(new_rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(old_rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param rlimit64(new_rlim) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

-----------------------------------------------------
302:      __NR_prlimit64 (get) 4s 1m
-----------------------------------------------------
Syscall param prlimit64(pid) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(resource) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(new_rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(old_rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param rlimit64(old_rlim) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

-----------------------------------------------------
302:      __NR_prlimit64 (get+set) 4s 2m
-----------------------------------------------------
Syscall param prlimit64(pid) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(resource) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(new_rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param prlimit64(old_rlim) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

Syscall param rlimit64(new_rlim) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param rlimit64(old_rlim) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar.c)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

-----------------------------------------------------
9999:                9999 1e
-----------------------------------------------------
WARNING: unhandled amd64-linux syscall: 9999
You may be able to write your own handler.
Read the file README_MISSING_SYSCALL_OR_IOCTL.
Nevertheless we consider this a bug.  Please report
it at http://valgrind.org/support/bug_reports.html.
-----------------------------------------------------
 60:           __NR_exit 1s 0m
-----------------------------------------------------
Syscall param exit(status) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar.c)

