#! /bin/sh

dir=`dirname $0`

$dir/../../tests/filter_stderr_basic    |

# Remove "Lackey, ..." line and the following copyright line.
sed "/^Lackey, an example Valgrind tool/ , /./ d" |

# Filter all the numbers.
../../tests/filter_numbers |

# Replace "call" with "calls"
sed "s/ call / calls /"
