Syscall param fadvise64(fd) contains uninitialised byte(s)
   ...
   by 0x........: main (fadvise64.c:10)

Syscall param fadvise64(offset_low) contains uninitialised byte(s)
   ...
   by 0x........: main (fadvise64.c:11)

Syscall param fadvise64(offset_high) contains uninitialised byte(s)
   ...
   by 0x........: main (fadvise64.c:11)

Syscall param fadvise64(len_low) contains uninitialised byte(s)
   ...
   by 0x........: main (fadvise64.c:12)

Syscall param fadvise64(len_high) contains uninitialised byte(s)
   ...
   by 0x........: main (fadvise64.c:12)

Syscall param fadvise64(advice) contains uninitialised byte(s)
   ...
   by 0x........: main (fadvise64.c:13)

