
Conflicting load by thread 1 at 0x........ size 1
   at 0x........: main (annotate_ignore_write.c:?)
Location 0x........ is 0 bytes inside global var "s_b"
declared at annotate_ignore_write.c:11

Conflicting load by thread 1 at 0x........ size 1
   at 0x........: main (annotate_ignore_write.c:?)
Location 0x........ is 0 bytes inside global var "s_c"
declared at annotate_ignore_write.c:12

Conflicting store by thread 1 at 0x........ size 1
   at 0x........: main (annotate_ignore_write.c:?)
Location 0x........ is 0 bytes inside global var "s_a"
declared at annotate_ignore_write.c:10

Finished.

ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
