
missing happens-before annotation
   at 0x........: vgDrdCl_annotate_happens_after (drd.h:?)
   by 0x........: main (annotate_hb_err.c:?)

wrong type of synchronization object
   at 0x........: vgDrdCl_annotate_happens_before (drd.h:?)
   by 0x........: main (annotate_hb_err.c:?)
mutex 0x........ was first observed at:
   at 0x........: pthread_mutex_init (drd_pthread_intercepts.c:?)
   by 0x........: main (annotate_hb_err.c:?)

wrong type of synchronization object
   at 0x........: vgDrdCl_annotate_happens_before (drd.h:?)
   by 0x........: main (annotate_hb_err.c:?)
cond 0x........ was first observed at:
   at 0x........: pthread_cond_init (drd_pthread_intercepts.c:?)
   by 0x........: main (annotate_hb_err.c:?)

wrong type of synchronization object
   at 0x........: pthread_cond_init (drd_pthread_intercepts.c:?)
   by 0x........: main (annotate_hb_err.c:?)
order annotation 0x........ was first observed at:
   at 0x........: vgDrdCl_annotate_happens_before (drd.h:?)
   by 0x........: main (annotate_hb_err.c:?)

happens-before after happens-after
   at 0x........: vgDrdCl_annotate_happens_before (drd.h:?)
   by 0x........: main (annotate_hb_err.c:?)
order annotation 0x........ was first observed at:
   at 0x........: vgDrdCl_annotate_happens_before (drd.h:?)
   by 0x........: main (annotate_hb_err.c:?)

Done.

ERROR SUMMARY: 5 errors from 5 contexts (suppressed: 0 from 0)
