<?xml version="1.0"?>

<valgrindoutput>

<protocolversion>4</protocolversion>
<protocoltool>drd</protocoltool>

<preamble>
  <line>...</line>
  <line>...</line>
  <line>...</line>
  <line>...</line>
</preamble>

<pid>...</pid>
<ppid>...</ppid>
<tool>drd</tool>

<args>
  <vargv>...</vargv>
  <argv>
    <exe>./tsan_unittest</exe>
    <arg>1</arg>
  </argv>
</args>

<status>
  <state>RUNNING</state>
  <time>...</time>
</status>

FLAGS [phb=1, fm=0]
test01: positive
  <trace><text>store 0x........ size 4 (thread x / vc ...)</text>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>test01::Worker()</fn>
      <dir>...</dir>
      <file>tsan_unittest.cpp</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>MyThread::ThreadBody(MyThread*)</fn>
      <dir>...</dir>
      <file>tsan_thread_wrappers_pthread.h</file>
      <line>...</line>
    </frame>
  </stack>
  </trace>
  <trace><text>store 0x........ size 4 (thread x / vc ...)</text>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>test01::Parent()</fn>
      <dir>...</dir>
      <file>tsan_unittest.cpp</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>test01::Run()</fn>
      <dir>...</dir>
      <file>tsan_unittest.cpp</file>
      <line>...</line>
    </frame>
  </stack>
  </trace>
<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>ConflictingAccess</kind>
  <what>Conflicting store by thread x at 0x........ size 4</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>test01::Parent()</fn>
      <dir>...</dir>
      <file>tsan_unittest.cpp</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>test01::Run()</fn>
      <dir>...</dir>
      <file>tsan_unittest.cpp</file>
      <line>...</line>
    </frame>
  </stack>
  <auxwhat>Allocation context: BSS section of tsan_unittest</auxwhat>
</error>

  <trace><text>load  0x........ size 4 (thread x / vc ...)</text>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>test01::Run()</fn>
      <dir>...</dir>
      <file>tsan_unittest.cpp</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>main</fn>
      <dir>...</dir>
      <file>tsan_unittest.cpp</file>
      <line>...</line>
    </frame>
  </stack>
  </trace>
	GLOB=2

<status>
  <state>FINISHED</state>
  <time>...</time>
</status>

<errorcounts>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
</errorcounts>

<suppcounts>...</suppcounts>

</valgrindoutput>

