
Thread 2:
Conflicting load by thread 2/3 at 0x........ size 4
   at 0x........: th (hg05_race2.c:17)
   by 0x........: vg_thread_wrapper (drd_pthread_intercepts.c:?)
   by 0x........: (within libpthread-?.?.so)
   by 0x........: clone (in /...libc...)
Location 0x........ is 0 bytes inside foo.poot[5].plop[11],
declared at hg05_race2.c:24, in frame #? of thread 1
Other segment start (thread 0/2)
   (thread finished, call stack no longer available)
Other segment end (thread 0/2)
   (thread finished, call stack no longer available)

Conflicting store by thread 2/3 at 0x........ size 4
   at 0x........: th (hg05_race2.c:17)
   by 0x........: vg_thread_wrapper (drd_pthread_intercepts.c:?)
   by 0x........: (within libpthread-?.?.so)
   by 0x........: clone (in /...libc...)
Location 0x........ is 0 bytes inside foo.poot[5].plop[11],
declared at hg05_race2.c:24, in frame #? of thread 1
Other segment start (thread 0/2)
   (thread finished, call stack no longer available)
Other segment end (thread 0/2)
   (thread finished, call stack no longer available)

ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
