
Start.
Thread 2:
Conflicting store by thread 2 at 0x........ size 10
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: thread_func (free_is_write.c:?)
   by 0x........: vgDrd_thread_wrapper (drd_pthread_intercepts.c:?)
Address 0x........ is at offset 0 from 0x......... Allocation context:
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (free_is_write.c:?)

Done.

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
