
Conflicting load by thread x at 0x........ size 4
   at 0x........: thread_func (rwlock_race.c:?)
   by 0x........: vgDrd_thread_wrapper (drd_pthread_intercepts.c:?)
Location 0x........ is 0 bytes inside global var "s_racy"
declared at rwlock_race.c:18

Conflicting store by thread x at 0x........ size 4
   at 0x........: thread_func (rwlock_race.c:?)
   by 0x........: vgDrd_thread_wrapper (drd_pthread_intercepts.c:?)
Location 0x........ is 0 bytes inside global var "s_racy"
declared at rwlock_race.c:18

Result: 2

ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
