
Conflicting load by thread 1 at 0x........ size 4
   at 0x........: main (tc01_simple_race.c:28)
Location 0x........ is 0 bytes inside global var "x"
declared at tc01_simple_race.c:9

Conflicting store by thread 1 at 0x........ size 4
   at 0x........: main (tc01_simple_race.c:28)
Location 0x........ is 0 bytes inside global var "x"
declared at tc01_simple_race.c:9


ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
