<?xml version="1.0"?>

<valgrindoutput>

<protocolversion>4</protocolversion>
<protocoltool>drd</protocoltool>

<preamble>
  <line>...</line>
  <line>...</line>
  <line>...</line>
  <line>...</line>
</preamble>

<pid>...</pid>
<ppid>...</ppid>
<tool>drd</tool>

<args>
  <vargv>...</vargv>
  <argv>
    <exe>./thread_name</exe>
  </argv>
</args>

<status>
  <state>RUNNING</state>
  <time>...</time>
</status>


thread_func instance 1

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 2

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 3

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 4

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 5

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 6

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 7

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 8

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 9

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


thread_func instance 10

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>MutexErr</kind>
  <what>The object at address 0x........ is not a mutex.</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>pthread_mutex_unlock</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>thread_func</fn>
      <dir>...</dir>
      <file>thread_name.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>vgDrd_thread_wrapper</fn>
      <dir>...</dir>
      <file>drd_pthread_intercepts.c</file>
      <line>...</line>
    </frame>
  </stack>
</error>


<status>
  <state>FINISHED</state>
  <time>...</time>
</status>

<errorcounts>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
</errorcounts>

<suppcounts>...</suppcounts>

</valgrindoutput>

