
Locking rwlock via pthread_rwlock_wrlock().
Locking rwlock via pthread_rwlock_trywrlock().
Locking rwlock via pthread_rwlock_timedwrlock().
Locking rwlock via pthread_rwlock_rdlock().
Locking rwlock via pthread_rwlock_tryrdlock().
Locking rwlock via pthread_rwlock_timedrdlock().
Attempt to lock for writing recursively (not allowed).
Recursive writer locking not allowed: rwlock 0x.........
   at 0x........: pthread_rwlock_trywrlock (drd_pthread_intercepts.c:?)
   by 0x........: main (trylock.c:?)
rwlock 0x........ was first observed at:
   at 0x........: pthread_rwlock_init (drd_pthread_intercepts.c:?)
   by 0x........: main (trylock.c:?)

Locking mutex via pthread_mutex_trylock().
Locking mutex via pthread_mutex_lock().
Locking mutex via pthread_mutex_timedlock().

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
