
Warning: client syscall mmap2 tried to modify addresses 0x0-0x10000
mmap @ 0x00000000: Cannot allocate memory
Warning: client syscall mmap2 tried to modify addresses 0xB0000000-0xB0010000
mmap @ top: Cannot allocate memory
Warning: client syscall mmap2 tried to modify addresses 0xB8000000-0xB8010000
mmap @ top+.5G: Cannot allocate memory

ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
