inc_counter(): count = 1, unlocking mutex
inc_counter(): count = 2, unlocking mutex
inc_counter(): count = 3, unlocking mutex
inc_counter(): count = 4, unlocking mutex
inc_counter(): count = 5, unlocking mutex
inc_counter(): count = 6, unlocking mutex
inc_counter(): count = 7, unlocking mutex
inc_counter(): count = 8, unlocking mutex
inc_counter(): count = 9, unlocking mutex
inc_counter(): count = 10, unlocking mutex
inc_counter(): count = 11, unlocking mutex
inc_counter(): count = 12, unlocking mutex
hit threshold!
inc_counter(): count = 13, unlocking mutex
inc_counter(): count = 14, unlocking mutex
inc_counter(): count = 15, unlocking mutex
inc_counter(): count = 16, unlocking mutex
inc_counter(): count = 17, unlocking mutex
inc_counter(): count = 18, unlocking mutex
inc_counter(): count = 19, unlocking mutex
inc_counter(): count = 20, unlocking mutex
condvar was hit!
