
Invalid read of size 8
   at 0x........: main (fp.c:13)
 Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, a block of size 8 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fp.c:11)

Invalid write of size 8
   at 0x........: main (fp.c:13)
 Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, a block of size 8 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fp.c:11)

Invalid read of size 4
   at 0x........: main (fp.c:14)
 Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, a block of size 4 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fp.c:12)

Invalid write of size 4
   at 0x........: main (fp.c:14)
 Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, a block of size 4 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fp.c:12)


ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
