
Invalid read of size 4
   at 0x........: main (hp_dangle.c:17)
 Address 0x........ is 20 bytes inside the accessing pointer's
 once-legitimate range, a block of size 400 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: mk_dangle (hp_dangle.c:7)
   by 0x........: main (hp_dangle.c:15)

Doubly-invalid read of size 4
   at 0x........: main (hp_dangle.c:18)
 Address 0x........ is 4 bytes before the accessing pointer's
 once-legitimate range, a block of size 400 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: mk_dangle (hp_dangle.c:7)
   by 0x........: main (hp_dangle.c:15)


ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
