<?xml version="1.0"?>

<valgrindoutput>

<protocolversion>4</protocolversion>
<protocoltool>exp-sgcheck</protocoltool>

<preamble>
  <line>...</line>
  <line>...</line>
  <line>...</line>
  <line>...</line>
  <line>...</line>
</preamble>

<pid>...</pid>
<ppid>...</ppid>
<tool>exp-sgcheck</tool>

<args>
  <vargv>...</vargv>
  <argv>
    <exe>./hsg</exe>
  </argv>
</args>

<status>
  <state>RUNNING</state>
  <time>...</time>
</status>

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>SorG</kind>
  <what>Invalid read of size 2</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>addup_wrongly</fn>
      <dir>...</dir>
      <file>hsg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>main</fn>
      <dir>...</dir>
      <file>hsg.c</file>
      <line>...</line>
    </frame>
  </stack>
  <auxwhat>Address 0x........ expected vs actual:</auxwhat>
  <auxwhat>Expected: global array "ga" of size 200 in object with soname "NONE"</auxwhat>
  <auxwhat>Actual:   unknown</auxwhat>
</error>

<error>
  <unique>0x........</unique>
  <tid>...</tid>
  <kind>SorG</kind>
  <what>Invalid read of size 2</what>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>addup_wrongly</fn>
      <dir>...</dir>
      <file>hsg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>do_other_stuff</fn>
      <dir>...</dir>
      <file>hsg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>main</fn>
      <dir>...</dir>
      <file>hsg.c</file>
      <line>...</line>
    </frame>
  </stack>
  <auxwhat>Address 0x........ expected vs actual:</auxwhat>
  <auxwhat>Expected: stack array "la" of size 200 in frame 1 back from here</auxwhat>
  <auxwhat>Actual:   unknown</auxwhat>
</error>


<status>
  <state>FINISHED</state>
  <time>...</time>
</status>

<errorcounts>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
  <pair>
    <count>...</count>
    <unique>0x........</unique>
  </pair>
</errorcounts>

<suppcounts>...</suppcounts>

</valgrindoutput>

