
about to do 14 [0]
Invalid read of size 4
   at 0x........: main (idiv.c:14)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 14 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:14)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block

Invalid IDIV
   at 0x........: main (idiv.c:16)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First arg not a pointer
Second arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
about to do 16 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:16)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 16 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:16)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 18 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:18)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 18 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:18)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block

Invalid IDIV
   at 0x........: main (idiv.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Both args derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
about to do 20 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 20 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 22 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 22 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 23 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:23)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 23 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:23)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 25 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:25)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 25 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:25)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 26 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:26)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 26 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:26)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 28 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:28)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 28 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:28)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 29 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:29)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 29 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:29)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 30 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:30)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 30 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:30)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 31 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:31)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 31 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:31)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block

Invalid IDIV
   at 0x........: main (idiv.c:33)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First arg may be a pointer
Second arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
about to do 33 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:33)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 33 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:33)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block

Invalid IDIV
   at 0x........: main (idiv.c:34)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First arg may be a pointer
Second arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
about to do 34 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:34)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 34 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:34)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 36 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:36)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 36 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:36)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 37 [0]

Invalid read of size 4
   at 0x........: main (idiv.c:37)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 37 [-1]

Invalid read of size 4
   at 0x........: main (idiv.c:37)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block


ERROR SUMMARY: 36 errors from 36 contexts (suppressed: 0 from 0)
