
Invalid read of size 1
   at 0x........: main (pth_specific.c:19)
 Address 0x........ is 1 bytes before the accessing pointer's
 legitimate range, a block of size 100 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (pth_specific.c:17)

Invalid read of size 1
   at 0x........: main (pth_specific.c:27)
 Address 0x........ is 1 bytes before the accessing pointer's
 legitimate range, a block of size 100 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (pth_specific.c:17)


ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
