---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create_WRK (hg_intercepts.c:...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (locked_vs_unlocked2.c:61)

---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create_WRK (hg_intercepts.c:...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (locked_vs_unlocked2.c:62)

----------------------------------------------------------------

Lock at 0x........ was first observed
   at 0x........: pthread_mutex_init (hg_intercepts.c:...)
   by 0x........: main (locked_vs_unlocked2.c:58)

Lock at 0x........ was first observed
   at 0x........: pthread_mutex_init (hg_intercepts.c:...)
   by 0x........: main (locked_vs_unlocked2.c:59)

Lock at 0x........ was first observed
   at 0x........: pthread_mutex_init (hg_intercepts.c:...)
   by 0x........: main (locked_vs_unlocked2.c:57)

Possible data race during write of size 4 at 0x........ by thread #x
Locks held: 2, at addresses 0x........ 0x........
   at 0x........: child_fn2 (locked_vs_unlocked2.c:45)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

This conflicts with a previous write of size 4 by thread #x
Locks held: 2, at address 0x........ (and 1 that can't be shown)
   at 0x........: child_fn1 (locked_vs_unlocked2.c:29)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

