---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (pth_destroy_cond.c:29)

----------------------------------------------------------------

Thread #x: pthread_cond_destroy: destruction of condition variable being waited upon
   at 0x........: pthread_cond_destroy_WRK (hg_intercepts.c:...)
   by 0x........: pthread_cond_destroy@* (hg_intercepts.c:...)
   by 0x........: ThreadFunction (pth_destroy_cond.c:18)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

