---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: barriers_and_races (pth_barrier.c:92)
   by 0x........: main (pth_barrier.c:122)

---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: barriers_and_races (pth_barrier.c:92)
   by 0x........: main (pth_barrier.c:122)

---Thread-Announcement------------------------------------------

Thread #x is the program's root thread

----------------------------------------------------------------

Possible data race during write of size 1 at 0x........ by thread #x
Locks held: none
   at 0x........: threadfunc (pth_barrier.c:60)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

This conflicts with a previous write of size 1 by thread #x
Locks held: none
   at 0x........: threadfunc (pth_barrier.c:60)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...
 Address 0x........ is 0 bytes inside a block of size 1 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: barriers_and_races (pth_barrier.c:76)
   by 0x........: main (pth_barrier.c:122)
 Block was alloc'd by thread #x

