---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create_WRK (hg_intercepts.c:...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: barriers_and_races (pth_barrier.c:91)
   by 0x........: main (pth_barrier.c:121)

---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create_WRK (hg_intercepts.c:...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: barriers_and_races (pth_barrier.c:91)
   by 0x........: main (pth_barrier.c:121)

----------------------------------------------------------------

Possible data race during write of size 4 at 0x........ by thread #x
Locks held: none
   at 0x........: threadfunc (pth_barrier.c:59)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

This conflicts with a previous write of size 4 by thread #x
Locks held: none
   at 0x........: threadfunc (pth_barrier.c:59)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

Address 0x........ is 0 bytes inside a block of size 4 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: barriers_and_races (pth_barrier.c:75)
   by 0x........: main (pth_barrier.c:121)

