
---Thread-Announcement------------------------------------------

Thread #x is the program's root thread

----------------------------------------------------------------

Thread #x: lock order "0x........ before 0x........" violated

Observed (incorrect) order is: acquisition of lock at 0x........
   at 0x........: pthread_mutex_lock (hg_intercepts.c:...)
   by 0x........: main (tc13_laog1.c:23)

 followed by a later acquisition of lock at 0x........
   at 0x........: pthread_mutex_lock (hg_intercepts.c:...)
   by 0x........: main (tc13_laog1.c:24)

Required order was established by acquisition of lock at 0x........
   at 0x........: pthread_mutex_lock (hg_intercepts.c:...)
   by 0x........: main (tc13_laog1.c:17)

 followed by a later acquisition of lock at 0x........
   at 0x........: pthread_mutex_lock (hg_intercepts.c:...)
   by 0x........: main (tc13_laog1.c:18)


ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
