
---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (tc14_laog_dinphils.c:34)

----------------------------------------------------------------

Thread #x: lock order "0x........ before 0x........" violated

Observed (incorrect) order is: acquisition of lock at 0x........
   at 0x........: pthread_mutex_lock (hg_intercepts.c:...)
   by 0x........: dine (tc14_laog_dinphils.c:18)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

 followed by a later acquisition of lock at 0x........
   at 0x........: pthread_mutex_lock (hg_intercepts.c:...)
   by 0x........: dine (tc14_laog_dinphils.c:19)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...


ERROR SUMMARY: 1000 errors from 1 contexts (suppressed: 0 from 0)
