
---Thread-Announcement------------------------------------------

Thread #x is the program's root thread

---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create_WRK (hg_intercepts.c:...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (tc16_byterace.c:22)

----------------------------------------------------------------

Possible data race during read of size 1 at 0x........ by thread #x
Locks held: none
   at 0x........: main (tc16_byterace.c:34)

This conflicts with a previous write of size 1 by thread #x
Locks held: none
   at 0x........: child_fn (tc16_byterace.c:13)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

Location 0x........ is 0 bytes inside bytes[4],
a global variable declared at tc16_byterace.c:7

----------------------------------------------------------------

Possible data race during write of size 1 at 0x........ by thread #x
Locks held: none
   at 0x........: main (tc16_byterace.c:34)

This conflicts with a previous write of size 1 by thread #x
Locks held: none
   at 0x........: child_fn (tc16_byterace.c:13)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...

Location 0x........ is 0 bytes inside bytes[4],
a global variable declared at tc16_byterace.c:7


ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
