
---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (tc22_exit_w_lock.c:39)

----------------------------------------------------------------

Thread #x: Exiting thread still holds 2 locks
   ...

---Thread-Announcement------------------------------------------

Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (tc22_exit_w_lock.c:42)

----------------------------------------------------------------

Thread #x: Exiting thread still holds 1 lock
   ...

---Thread-Announcement------------------------------------------

Thread #x is the program's root thread

----------------------------------------------------------------

Thread #x: Exiting thread still holds 1 lock
   ...
   by 0x........: main (tc22_exit_w_lock.c:48)


ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
