Invalid free() / delete / delete[] / realloc()
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (tests/badfree.c:12)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Invalid free() / delete / delete[] / realloc()
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (tests/badfree.c:15)
 Address 0x........ is on thread 1's stack
 in frame #1, created by main (badfree.c:7)

