
Invalid free() / delete / delete[]
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (badfree.c:12)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: (within /.../tests/badfree)
   Address 0x........ is not stack'd, malloc'd or free'd

Invalid free() / delete / delete[]
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (badfree.c:15)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: (within /.../tests/badfree)
   Address 0x........ is on thread 1's stack

ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 0 allocs, 2 frees, 0 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
