
Jump to the invalid address stated on the next line
   at 0x........: ???
   by 0x........: (below main) (in /...libc...)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Process terminating with default action of signal 11 (SIGSEGV)
 Access not within mapped region at address 0x........
   at 0x........: ???
   by 0x........: (below main) (in /...libc...)
 If you believe this happened as a result of a stack overflow in your
 program's main thread (unlikely but possible), you can try to increase
 the size of the main thread stack using the --main-stacksize= flag.
 The main thread stack size used in this run was ....

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: ... bytes in ... blocks.
malloc/free: ... allocs, ... frees, ... bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
