Mismatched aligned_alloc/free_sized size value: 1024
   at 0x........: free_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:26)
 Address 0x........ is 0 bytes inside a block of size 1,000 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:24)

Mismatched aligned_alloc/free_sized size value: 990
   at 0x........: free_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:29)
 Address 0x........ is 0 bytes inside a block of size 1,000 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:27)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: free_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:38)

Invalid alignment value: 1000 (should be a power of 2)
   at 0x........: free_aligned_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:42)

Mismatched aligned_alloc/free_aligned_sized alignment alloc value: default-aligned dealloc value: 1000
   at 0x........: free_aligned_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:42)
 Address 0x........ is 0 bytes inside a block of size 1,000 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:40)

Mismatched aligned_alloc/free_aligned_sized alignment alloc value: 256 dealloc value: 128
   at 0x........: free_aligned_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:46)
 Address 0x........ is 0 bytes inside a block of size 4,096 alloc'd
   at 0x........: aligned_alloc (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:44)

Mismatched aligned_alloc/free_aligned_sized size value: 1024
   at 0x........: free_aligned_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:50)
 Address 0x........ is 0 bytes inside a block of size 2,048 alloc'd
   at 0x........: aligned_alloc (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:48)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: free_aligned_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:54)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: free_aligned_sized (vg_replace_malloc.c:...)
   by 0x........: main (c23_free.c:58)

