<?xml version="1.0"?>

<valgrindoutput>

<protocolversion>4</protocolversion>
<protocoltool>memcheck</protocoltool>

<preamble>
  <line>...</line>
  <line>...</line>
  <line>...</line>
  <line>...</line>
</preamble>

<pid>...</pid>
<ppid>...</ppid>
<tool>memcheck</tool>

<args>
  <vargv>...</vargv>
  <argv>
    <exe>./client-msg</exe>
  </argv>
</args>

<status>
  <state>RUNNING</state>
  <time>...</time>
</status>

<clientmsg>
  <tid>...</tid>
  <text>hello &lt;&gt; &lt;&amp;&gt;%s world
  </text>
  <stack>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>VALGRIND_PRINTF_BACKTRACE</fn>
      <dir>...</dir>
      <file>valgrind.h</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>baz</fn>
      <dir>...</dir>
      <file>client-msg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>bar</fn>
      <dir>...</dir>
      <file>client-msg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>foo</fn>
      <dir>...</dir>
      <file>client-msg.c</file>
      <line>...</line>
    </frame>
    <frame>
      <ip>0x........</ip>
      <obj>...</obj>
      <fn>main</fn>
      <dir>...</dir>
      <file>client-msg.c</file>
      <line>...</line>
    </frame>
  </stack>
</clientmsg>

<status>
  <state>FINISHED</state>
  <time>...</time>
</status>

<errorcounts>
</errorcounts>

<suppcounts>...</suppcounts>

</valgrindoutput>

