
Conditional jump or move depends on uninitialised value(s)
   at 0x........: abc::def<int, magic<int> >::xyzzy(int*, magic<int>*) (demangle.cpp:9)
   by 0x........: magic<int>::xyzzy(int*) (demangle.cpp:19)
   by 0x........: main (demangle.cpp:27)


HEAP SUMMARY:
    in use at exit: 6 bytes in 3 blocks
  total heap usage: 3 allocs, 0 frees, 6 bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
Use --track-origins=yes to see where uninitialised values come from
ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
