Mismatched free() / delete / delete []
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: abc::def<int, magic<int> >::xyzzy(int*, magic<int>*) (demangle.cpp:10)
   by 0x........: magic<int>::xyzzy(int*) (demangle.cpp:21)
   by 0x........: main (demangle.cpp:29)
 Address 0x........ is 0 bytes inside a block of size 4 alloc'd
   at 0x........: ...operator new... (vg_replace_malloc.c:...)
   by 0x........: main (demangle.cpp:29)

