
Invalid write of size 1
   at 0x........: main (describe-block.c:8)
 Address 0x........ is 0 bytes inside a magic foople zone of size 4,096 client-defined
   at 0x........: main (describe-block.c:6)

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: ... bytes in ... blocks.
malloc/free: ... allocs, ... frees, ... bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
