Invalid free() / delete / delete[]
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (doublefree.c:10)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
   Address 0x........ is 0 bytes inside a block of size 177 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (doublefree.c:10)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
