
Invalid read of size 1
   at 0x........: ddd (errs1.c:7)
   by 0x........: bbb (errs1.c:9)
   by 0x........: aaa (errs1.c:10)
   by 0x........: main (errs1.c:17)
   Address 0x........ is 1 bytes before a block of size 10 alloc'd
   at 0x........: malloc (vg_clientfuncs.c:...)
   by 0x........: zzzzzzz (errs1.c:12)
   by 0x........: yyy (errs1.c:13)
   by 0x........: xxx (errs1.c:14)

Invalid write of size 1
   at 0x........: ddd (errs1.c:7)
   by 0x........: bbb (errs1.c:9)
   by 0x........: aaa (errs1.c:10)
   by 0x........: main (errs1.c:17)
   Address 0x........ is 1 bytes before a block of size 10 alloc'd
   at 0x........: malloc (vg_clientfuncs.c:...)
   by 0x........: zzzzzzz (errs1.c:12)
   by 0x........: yyy (errs1.c:13)
   by 0x........: xxx (errs1.c:14)

ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 10 bytes in 1 blocks.
malloc/free: 1 allocs, 0 frees, 10 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
