

HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
  total heap usage: ... allocs, ... frees, ... bytes allocated

320 bytes in 20 blocks are definitely lost in loss record ... of ...

LEAK SUMMARY:
   definitely lost: 320 bytes in 20 blocks
   indirectly lost: 0 bytes in 0 blocks
     possibly lost: 4,096 bytes in 1 blocks
   still reachable: 0 bytes in 0 blocks
        suppressed: 0 bytes in 0 blocks

For lists of detected and suppressed errors, rerun with: -s
ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
