leaked:      64 bytes in  4 blocks
dubious:      0 bytes in  0 blocks
reachable:   48 bytes in  3 blocks
suppressed:   0 bytes in  0 blocks
16 bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-tree.c:28)
   by 0x........: f (leak-tree.c:44)
   by 0x........: main (leak-tree.c:63)

48 (16 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-tree.c:28)
   by 0x........: f (leak-tree.c:43)
   by 0x........: main (leak-tree.c:63)

