leaked:     288 bytes in 18 blocks
dubious:      0 bytes in  0 blocks
reachable:    0 bytes in  0 blocks
suppressed:   0 bytes in  0 blocks
48 (16 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-cycle.c:15)
   by 0x........: mkcycle (leak-cycle.c:26)
   by 0x........: main (leak-cycle.c:44)

48 (16 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-cycle.c:15)
   by 0x........: mkcycle (leak-cycle.c:26)
   by 0x........: main (leak-cycle.c:45)

96 (16 direct, 80 indirect) bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-cycle.c:15)
   by 0x........: mkcycle (leak-cycle.c:26)
   by 0x........: main (leak-cycle.c:51)

96 (16 direct, 80 indirect) bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-cycle.c:15)
   by 0x........: mkcycle (leak-cycle.c:26)
   by 0x........: main (leak-cycle.c:63)

