
searching for pointers to 11 not-freed blocks.
checked ... bytes.

72 (8 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 11 of 11
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-tree.c:11)
   by 0x........: main (leak-tree.c:25)

LEAK SUMMARY:
   definitely lost: 8 bytes in 1 blocks.
   indirectly lost: 64 bytes in 8 blocks.
     possibly lost: 0 bytes in 0 blocks.
   still reachable: 16 bytes in 2 blocks.
        suppressed: 0 bytes in 0 blocks.
Reachable blocks (those to which a pointer was found) are not shown.
To see them, rerun with: --show-reachable=yes
searching for pointers to 14 not-freed blocks.
checked ... bytes.


8 bytes in 1 blocks are definitely lost in loss record 1 of 14
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-tree.c:11)
   by 0x........: main (leak-tree.c:39)


88 (8 direct, 80 indirect) bytes in 1 blocks are definitely lost in loss record 13 of 14
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-tree.c:11)
   by 0x........: main (leak-tree.c:25)


16 (8 direct, 8 indirect) bytes in 1 blocks are definitely lost in loss record 14 of 14
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: mk (leak-tree.c:11)
   by 0x........: main (leak-tree.c:38)

LEAK SUMMARY:
   definitely lost: 24 bytes in 3 blocks.
   indirectly lost: 88 bytes in 11 blocks.
     possibly lost: 0 bytes in 0 blocks.
   still reachable: 0 bytes in 0 blocks.
        suppressed: 0 bytes in 0 blocks.
Reachable blocks (those to which a pointer was found) are not shown.
To see them, rerun with: --show-reachable=yes

ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 112 bytes in 14 blocks.
malloc/free: 14 allocs, 0 frees, 112 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
