Invalid write of size 1
   at 0x........: main (malloc2.c:50)
 Address 0x........ is 0 bytes inside a block of size 772 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (malloc2.c:49)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (malloc2.c:41)

Invalid free() / delete / delete[] / realloc()
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (malloc2.c:54)
 Address 0x........ is 0 bytes inside a block of size 772 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (malloc2.c:49)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (malloc2.c:41)

