

ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 1000 bytes in 1 blocks.
malloc/free: 1 allocs, 0 frees, 1000 bytes allocated.
For counts of detected errors, rerun with: -v
searching for pointers to 1 not-freed blocks.
checked ... bytes.

definitely lost: 1000 bytes in 1 blocks.
possibly lost:   0 bytes in 0 blocks.
still reachable: 0 bytes in 0 blocks.

1000 bytes in 1 blocks are definitely lost in loss record 1 of 1
   at 0x........: malloc (vg_clientfuncs.c:...)
   by 0x........: main (nanoleak.c:6)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: (within /.../tests/nanoleak)

LEAK SUMMARY:
   definitely lost: 1000 bytes in 1 blocks.
   possibly lost:   0 bytes in 0 blocks.
   still reachable: 0 bytes in 0 blocks.
Reachable blocks (those to which a pointer was found) are not shown.
To see them, rerun with: --show-reachable=yes

