
Invalid write of size 1
   at 0x........: main (noisy_child.c:27)
 Address 0x........ is 5 bytes inside a block of size 10 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (noisy_child.c:24)

Invalid write of size 1
   at 0x........: do_parent_badness (noisy_child.c:16)
   by 0x........: main (noisy_child.c:37)
 Address 0x........ is 0 bytes after a block of size 10 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (noisy_child.c:24)


HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
  total heap usage: ... allocs, ... frees, ... bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
