
Warning: src and dst overlap in memcpy(0x........, 0x........, 21)
Warning: src and dst overlap in memcpy(0x........, 0x........, 21)
Warning: src and dst overlap in strncpy(0x........, 0x........, 21)
Warning: src and dst overlap in strncpy(0x........, 0x........, 21)
Warning: src and dst overlap in strcpy(0x........, 0x........)
Warning: src and dst overlap in strncat(0x........, 0x........, 21)
Warning: src and dst overlap in strncat(0x........, 0x........, 21)

ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 0 allocs, 0 frees, 0 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
