
Conditional jump or move depends on uninitialised value(s)
   at 0x........: foo (partiallydefinedeq.c:15)
   by 0x........: main (partiallydefinedeq.c:37)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: foo (partiallydefinedeq.c:15)
   by 0x........: main (partiallydefinedeq.c:52)

ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: ... bytes in ... blocks.
malloc/free: ... allocs, ... frees, ... bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
Use --track-origins=yes to see where uninitialised values come from
