realloc() with size 0
   at 0x........: realloc (vg_replace_malloc.c:...)
   ...
 Address 0x........ is 0 bytes inside a block of size 1,024 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...

ERROR SUMMARY: 5 errors from 1 contexts (suppressed: 0 from 0)

5 errors in context 1 of 1:
realloc() with size 0
   at 0x........: realloc (vg_replace_malloc.c:...)
   ...
 Address 0x........ is 0 bytes inside a block of size 1,024 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...

ERROR SUMMARY: 5 errors from 1 contexts (suppressed: 0 from 0)
