-----------------------------------------------------
251:                 251 0e
-----------------------------------------------------
-----------------------------------------------------
253: __NR_lookup_dcookie 4s 1m
-----------------------------------------------------
Syscall param lookup_dcookie(cookie_low32) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(cookie_high32) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(len) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
9999:                9999 1e
-----------------------------------------------------
WARNING: unhandled syscall: 9999
Do not panic.  You may be able to fix this easily.
Read the file README_MISSING_SYSCALL_OR_IOCTL.
-----------------------------------------------------
252:     __NR_exit_group 1s 0m
-----------------------------------------------------

Syscall param exit_group(error_code) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
