-----------------------------------------------------
  3:           __NR_read 1+3s 1m
-----------------------------------------------------
Syscall param (syscallno) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param read(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param read(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param read(count) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param read(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  4:          __NR_write 3s 1m
-----------------------------------------------------

Syscall param write(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param write(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param write(count) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param write(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  5:           __NR_open (2-args) 2s 1m
-----------------------------------------------------

Syscall param open(filename) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param open(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param open(filename) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  5:           __NR_open (3-args) 1s 0m
-----------------------------------------------------

Syscall param open(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
  6:          __NR_close 1s 0m
-----------------------------------------------------

Syscall param close(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Warning: invalid file descriptor -1 in syscall close()
-----------------------------------------------------
  7:        __NR_waitpid 3s 1m
-----------------------------------------------------

Syscall param waitpid(pid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param waitpid(status) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param waitpid(options) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param waitpid(status) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  8:          __NR_creat 2s 1m
-----------------------------------------------------

Syscall param creat(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param creat(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param creat(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  9:           __NR_link 2s 2m
-----------------------------------------------------

Syscall param link(oldpath) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param link(newpath) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param link(oldpath) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param link(newpath) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 10:         __NR_unlink 1s 1m
-----------------------------------------------------

Syscall param unlink(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param unlink(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 11:         __NR_execve 3s 1m
-----------------------------------------------------

Syscall param execve(filename) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param execve(argv) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param execve(envp) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param execve(filename) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 12:          __NR_chdir 1s 1m
-----------------------------------------------------

Syscall param chdir(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chdir(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 13:           __NR_time 1s 1m
-----------------------------------------------------

Syscall param time(t) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param time(t) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 14:          __NR_mknod 3s 1m
-----------------------------------------------------

Syscall param mknod(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mknod(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mknod(dev) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mknod(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 15:          __NR_chmod 2s 1m
-----------------------------------------------------

Syscall param chmod(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chmod(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chmod(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 17:          __NR_break 0e
-----------------------------------------------------
-----------------------------------------------------
 19:          __NR_lseek 3s 0m
-----------------------------------------------------

Syscall param lseek(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lseek(offset) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lseek(whence) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 20:         __NR_getpid 0s 0m
-----------------------------------------------------
-----------------------------------------------------
 21:          __NR_mount 5s 3m
-----------------------------------------------------

Syscall param mount(source) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(target) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(type) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(data) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

More than 50 errors detected.  Subsequent errors
will still be recorded, but in less detail than before.

Syscall param mount(source) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param mount(target) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param mount(type) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 22:         __NR_umount 1s 1m
-----------------------------------------------------

Syscall param umount(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param umount(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 23:         __NR_setuid 1s 0m
-----------------------------------------------------

Syscall param setuid16(uid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 24:         __NR_getuid 0e
-----------------------------------------------------
-----------------------------------------------------
 26:         __NR_ptrace 4s 2m
-----------------------------------------------------

Syscall param ptrace(request) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param ptrace(pid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param ptrace(addr) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param ptrace(data) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param ptrace(getregs) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 27:          __NR_alarm 1s 0m
-----------------------------------------------------

Syscall param alarm(seconds) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 30:          __NR_utime 2s 2m
-----------------------------------------------------

Syscall param utime(filename) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param utime(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param utime(filename) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param utime(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 31:           __NR_stty 0e
-----------------------------------------------------
-----------------------------------------------------
 32:           __NR_gtty 0e
-----------------------------------------------------
-----------------------------------------------------
 33:         __NR_access 2s 1m
-----------------------------------------------------

Syscall param access(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param access(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param access(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 34:           __NR_nice 1s 0m
-----------------------------------------------------

Syscall param nice(inc) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 35:          __NR_ftime 0e
-----------------------------------------------------
-----------------------------------------------------
 36:           __NR_sync 0e
-----------------------------------------------------
-----------------------------------------------------
 37:           __NR_kill 2s 0m
-----------------------------------------------------

Syscall param kill(pid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param kill(sig) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 38:         __NR_rename 2s 2m
-----------------------------------------------------

Syscall param rename(oldpath) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param rename(newpath) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param rename(oldpath) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param rename(newpath) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 39:          __NR_mkdir 2s 1m
-----------------------------------------------------

Syscall param mkdir(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mkdir(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mkdir(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 40:          __NR_rmdir 1s 1m
-----------------------------------------------------

Syscall param rmdir(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param rmdir(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 41:            __NR_dup 1s 0m
-----------------------------------------------------

Syscall param dup(oldfd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 42:           __NR_pipe 1s 1m
-----------------------------------------------------

Syscall param pipe(filedes) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param pipe(filedes) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 43:          __NR_times 1s 1m
-----------------------------------------------------

Syscall param times(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param times(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 44:           __NR_prof 0e
-----------------------------------------------------
-----------------------------------------------------
 45:            __NR_brk 1s 0m
-----------------------------------------------------

Syscall param brk(end_data_segment) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 46:         __NR_setgid 1s 0m
-----------------------------------------------------

Syscall param setgid16(gid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 47:         __NR_getgid 0e
-----------------------------------------------------
-----------------------------------------------------
 49:        __NR_geteuid 0e
-----------------------------------------------------
-----------------------------------------------------
 50:        __NR_getegid 0e
-----------------------------------------------------
-----------------------------------------------------
 51:           __NR_acct 1s 1m
-----------------------------------------------------

Syscall param acct(filename) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param acct(filename) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 52:        __NR_umount2 2s 1m
-----------------------------------------------------

Syscall param umount2(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param umount2(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param umount2(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 53:           __NR_lock 0e
-----------------------------------------------------
-----------------------------------------------------
 54:          __NR_ioctl 3s 1m
-----------------------------------------------------

Syscall param ioctl(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param ioctl(request) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param ioctl(arg) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param ioctl(TCSET{S,SW,SF}) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 55:          __NR_fcntl 3s 0m
-----------------------------------------------------

Syscall param fcntl(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fcntl(cmd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fcntl(arg) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 56:            __NR_mpx 0e
-----------------------------------------------------
-----------------------------------------------------
 57:        __NR_setpgid 2s 0m
-----------------------------------------------------

Syscall param setpgid(pid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setpgid(pgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 58:         __NR_ulimit 0e
-----------------------------------------------------
-----------------------------------------------------
 60:          __NR_umask 1s 0m
-----------------------------------------------------

Syscall param umask(mask) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 61:         __NR_chroot 1s 1m
-----------------------------------------------------

Syscall param chroot(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chroot(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 63:           __NR_dup2 2s 0m
-----------------------------------------------------

Syscall param dup2(oldfd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param dup2(newfd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 64:        __NR_getppid 0e
-----------------------------------------------------
-----------------------------------------------------
 65:        __NR_getpgrp 0e
-----------------------------------------------------
-----------------------------------------------------
 66:         __NR_setsid 0e
-----------------------------------------------------
-----------------------------------------------------
 67:      __NR_sigaction 3s 2m
-----------------------------------------------------

Syscall param sigaction(signum) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param sigaction(act) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param sigaction(oldact) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param sigaction(act) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param sigaction(oldact) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 70:       __NR_setreuid 2s 0m
-----------------------------------------------------

Syscall param setreuid16(ruid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setreuid16(euid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 71:       __NR_setregid 2s 0m
-----------------------------------------------------

Syscall param setregid16(rgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setregid16(egid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 73:     __NR_sigpending 1s 1m
-----------------------------------------------------

Syscall param sigpending(set) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param sigpending(set) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 75:      __NR_setrlimit 2s 1m
-----------------------------------------------------

Syscall param setrlimit(resource) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setrlimit(rlim) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setrlimit(rlim) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
111:        __NR_vhangup 0e
-----------------------------------------------------
-----------------------------------------------------
112:           __NR_idle 0e
-----------------------------------------------------
-----------------------------------------------------
122:          __NR_uname 1s 1m
-----------------------------------------------------

Syscall param uname(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param uname(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
127:  __NR_create_module 0e
-----------------------------------------------------
-----------------------------------------------------
130:__NR_get_kernel_syms 0e
-----------------------------------------------------
-----------------------------------------------------
137:    __NR_afs_syscall 0e
-----------------------------------------------------
-----------------------------------------------------
153:     __NR_munlockall 0e
-----------------------------------------------------
-----------------------------------------------------
167:   __NR_query_module 0e
-----------------------------------------------------
-----------------------------------------------------
199:       __NR_getuid32 0e
-----------------------------------------------------
-----------------------------------------------------
200:       __NR_getgid32 0e
-----------------------------------------------------
-----------------------------------------------------
201:      __NR_geteuid32 0e
-----------------------------------------------------
-----------------------------------------------------
202:      __NR_getegid32 0e
-----------------------------------------------------
-----------------------------------------------------
203:     __NR_setreuid32 2s 0m
-----------------------------------------------------

Syscall param setreuid(ruid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setreuid(euid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
204:     __NR_setregid32 2s 0m
-----------------------------------------------------

Syscall param setregid(rgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setregid(egid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
213:       __NR_setuid32 1s 0m
-----------------------------------------------------

Syscall param setuid(uid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
214:       __NR_setgid32 1s 0m
-----------------------------------------------------

Syscall param setgid(gid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
222:                 222 0e
-----------------------------------------------------
-----------------------------------------------------
223:                 223 0e
-----------------------------------------------------
-----------------------------------------------------
251:                 251 0e
-----------------------------------------------------
-----------------------------------------------------
253: __NR_lookup_dcookie 4s 1m
-----------------------------------------------------

Syscall param lookup_dcookie(cookie_low32) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(cookie_high32) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(len) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
9999:                9999 1e
-----------------------------------------------------
WARNING: unhandled syscall: 9999
Do not panic.  You may be able to fix this easily.
Read the file README_MISSING_SYSCALL_OR_IOCTL.
-----------------------------------------------------
  1:           __NR_exit 1s 0m
-----------------------------------------------------

Syscall param exit(error_code) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
