-----------------------------------------------------
200:       __NR_getgid32 0e
-----------------------------------------------------
-----------------------------------------------------
201:      __NR_geteuid32 0e
-----------------------------------------------------
-----------------------------------------------------
202:      __NR_getegid32 0e
-----------------------------------------------------
-----------------------------------------------------
203:     __NR_setreuid32 2s 0m
-----------------------------------------------------
Syscall param setreuid(ruid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setreuid(euid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
204:     __NR_setregid32 2s 0m
-----------------------------------------------------

Syscall param setregid(rgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setregid(egid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
205:    __NR_getgroups32 2s 1m
-----------------------------------------------------

Syscall param getgroups(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getgroups(list) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getgroups(list) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
206:    __NR_setgroups32 2s 1m
-----------------------------------------------------

Syscall param setgroups(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setgroups(list) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setgroups(list) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
207:       __NR_fchown32 3s 0m
-----------------------------------------------------

Syscall param fchown(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fchown(owner) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fchown(group) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
208:    __NR_setresuid32 3s 0m
-----------------------------------------------------

Syscall param setresuid(ruid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setresuid(euid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setresuid(suid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
209:    __NR_getresuid32 3s 3m
-----------------------------------------------------

Syscall param getresuid(ruid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresuid(euid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresuid(suid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresuid(ruid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getresuid(euid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getresuid(suid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
210:    __NR_setresgid32 3s 0m
-----------------------------------------------------

Syscall param setresgid(rgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setresgid(egid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setresgid(sgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
211:    __NR_getresgid32 3s 3m
-----------------------------------------------------

Syscall param getresgid(rgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresgid(egid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresgid(sgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresgid(rgid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getresgid(egid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getresgid(sgid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
212:        __NR_chown32 3s 1m
-----------------------------------------------------

Syscall param chown(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chown(owner) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chown(group) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chown(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
213:       __NR_setuid32 1s 0m
-----------------------------------------------------

Syscall param setuid(uid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
214:       __NR_setgid32 1s 0m
-----------------------------------------------------

Syscall param setgid(gid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
215:     __NR_setfsuid32 1s 0m
-----------------------------------------------------

Syscall param setfsuid(uid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
216:     __NR_setfsgid32 1s 0m
-----------------------------------------------------

Syscall param setfsgid(gid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
222:                 222 0e
-----------------------------------------------------
-----------------------------------------------------
223:                 223 0e
-----------------------------------------------------
-----------------------------------------------------
226:       __NR_setxattr 5s 3m
-----------------------------------------------------

Syscall param setxattr(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setxattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setxattr(value) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setxattr(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setxattr(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param setxattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param setxattr(value) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
227:      __NR_lsetxattr 5s 3m
-----------------------------------------------------

Syscall param lsetxattr(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lsetxattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lsetxattr(value) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

More than 50 errors detected.  Subsequent errors
will still be recorded, but in less detail than before.

Syscall param lsetxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lsetxattr(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lsetxattr(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lsetxattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lsetxattr(value) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
228:      __NR_fsetxattr 5s 2m
-----------------------------------------------------

Syscall param fsetxattr(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fsetxattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fsetxattr(value) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fsetxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fsetxattr(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fsetxattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param fsetxattr(value) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
229:       __NR_getxattr 4s 3m
-----------------------------------------------------

Syscall param getxattr(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getxattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getxattr(value) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getxattr(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getxattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getxattr(value) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
230:      __NR_lgetxattr 4s 3m
-----------------------------------------------------

Syscall param lgetxattr(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lgetxattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lgetxattr(value) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lgetxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lgetxattr(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lgetxattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lgetxattr(value) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
231:      __NR_fgetxattr 4s 2m
-----------------------------------------------------

Syscall param fgetxattr(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fgetxattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fgetxattr(value) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fgetxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fgetxattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param fgetxattr(value) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
232:      __NR_listxattr 3s 2m
-----------------------------------------------------

Syscall param listxattr(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param listxattr(list) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param listxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param listxattr(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param listxattr(list) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
233:     __NR_llistxattr 3s 2m
-----------------------------------------------------

Syscall param llistxattr(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param llistxattr(list) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param llistxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param llistxattr(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param llistxattr(list) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
234:     __NR_flistxattr 3s 1m
-----------------------------------------------------

Syscall param flistxattr(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param flistxattr(list) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param flistxattr(size) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param flistxattr(list) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
235:    __NR_removexattr 2s 2m
-----------------------------------------------------

Syscall param removexattr(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param removexattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param removexattr(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param removexattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
236:   __NR_lremovexattr 2s 2m
-----------------------------------------------------

Syscall param lremovexattr(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lremovexattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lremovexattr(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lremovexattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
237:   __NR_fremovexattr 2s 1m
-----------------------------------------------------

Syscall param fremovexattr(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fremovexattr(name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fremovexattr(name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
