-----------------------------------------------------
  3:           __NR_read 1+3s 1m
-----------------------------------------------------
Syscall param (syscallno) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param read(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param read(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param read(count) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param read(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  4:          __NR_write 3s 1m
-----------------------------------------------------

Syscall param write(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param write(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param write(count) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param write(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  5:           __NR_open (2-args) 2s 1m
-----------------------------------------------------

Syscall param open(filename) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param open(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param open(filename) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  5:           __NR_open (3-args) 1s 0m
-----------------------------------------------------

Syscall param open(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
  6:          __NR_close 1s 0m
-----------------------------------------------------

Syscall param close(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Warning: invalid file descriptor -1 in syscall close()
-----------------------------------------------------
  7:        __NR_waitpid 3s 1m
-----------------------------------------------------

Syscall param waitpid(pid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param waitpid(status) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param waitpid(options) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param waitpid(status) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  8:          __NR_creat 2s 1m
-----------------------------------------------------

Syscall param creat(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param creat(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param creat(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  9:           __NR_link 2s 2m
-----------------------------------------------------

Syscall param link(oldpath) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param link(newpath) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param link(oldpath) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param link(newpath) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 10:         __NR_unlink 1s 1m
-----------------------------------------------------

Syscall param unlink(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param unlink(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 12:          __NR_chdir 1s 1m
-----------------------------------------------------

Syscall param chdir(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chdir(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 13:           __NR_time 1s 1m
-----------------------------------------------------

Syscall param time(t) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param time(t) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 14:          __NR_mknod 3s 1m
-----------------------------------------------------

Syscall param mknod(pathname) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mknod(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mknod(dev) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mknod(pathname) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 15:          __NR_chmod 2s 1m
-----------------------------------------------------

Syscall param chmod(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chmod(mode) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chmod(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 17:          __NR_break 0e
-----------------------------------------------------
-----------------------------------------------------
 19:          __NR_lseek 3s 0m
-----------------------------------------------------

Syscall param lseek(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lseek(offset) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lseek(whence) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 20:         __NR_getpid 0s 0m
-----------------------------------------------------
-----------------------------------------------------
 21:          __NR_mount 5s 3m
-----------------------------------------------------

Syscall param mount(source) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(target) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(type) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(data) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param mount(source) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param mount(target) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param mount(type) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 22:         __NR_umount 1s 1m
-----------------------------------------------------

Syscall param umount(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

More than 50 errors detected.  Subsequent errors
will still be recorded, but in less detail than before.

Syscall param umount(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 23:         __NR_setuid 1s 0m
-----------------------------------------------------

Syscall param setuid16(uid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
 24:         __NR_getuid 0e
-----------------------------------------------------
-----------------------------------------------------
 31:           __NR_stty 0e
-----------------------------------------------------
-----------------------------------------------------
 32:           __NR_gtty 0e
-----------------------------------------------------
-----------------------------------------------------
 35:          __NR_ftime 0e
-----------------------------------------------------
-----------------------------------------------------
 36:           __NR_sync 0e
-----------------------------------------------------
-----------------------------------------------------
 44:           __NR_prof 0e
-----------------------------------------------------
-----------------------------------------------------
 47:         __NR_getgid 0e
-----------------------------------------------------
-----------------------------------------------------
 49:        __NR_geteuid 0e
-----------------------------------------------------
-----------------------------------------------------
 50:        __NR_getegid 0e
-----------------------------------------------------
-----------------------------------------------------
 51:           __NR_acct 1s 1m
-----------------------------------------------------

Syscall param acct(filename) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param acct(filename) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 52:        __NR_umount2 2s 1m
-----------------------------------------------------

Syscall param umount2(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param umount2(flags) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param umount2(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
 53:           __NR_lock 0e
-----------------------------------------------------
-----------------------------------------------------
 56:            __NR_mpx 0e
-----------------------------------------------------
-----------------------------------------------------
 58:         __NR_ulimit 0e
-----------------------------------------------------
-----------------------------------------------------
 64:        __NR_getppid 0e
-----------------------------------------------------
-----------------------------------------------------
 65:        __NR_getpgrp 0e
-----------------------------------------------------
-----------------------------------------------------
 66:         __NR_setsid 0e
-----------------------------------------------------
-----------------------------------------------------
111:        __NR_vhangup 0e
-----------------------------------------------------
-----------------------------------------------------
112:           __NR_idle 0e
-----------------------------------------------------
-----------------------------------------------------
122:          __NR_uname 1s 1m
-----------------------------------------------------

Syscall param uname(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param uname(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
127:  __NR_create_module 0e
-----------------------------------------------------
-----------------------------------------------------
130:__NR_get_kernel_syms 0e
-----------------------------------------------------
-----------------------------------------------------
137:    __NR_afs_syscall 0e
-----------------------------------------------------
-----------------------------------------------------
153:     __NR_munlockall 0e
-----------------------------------------------------
-----------------------------------------------------
167:   __NR_query_module 0e
-----------------------------------------------------
-----------------------------------------------------
199:       __NR_getuid32 0e
-----------------------------------------------------
-----------------------------------------------------
200:       __NR_getgid32 0e
-----------------------------------------------------
-----------------------------------------------------
201:      __NR_geteuid32 0e
-----------------------------------------------------
-----------------------------------------------------
202:      __NR_getegid32 0e
-----------------------------------------------------
-----------------------------------------------------
213:       __NR_setuid32 1s 0m
-----------------------------------------------------

Syscall param setuid(uid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
222:                 222 0e
-----------------------------------------------------
-----------------------------------------------------
223:                 223 0e
-----------------------------------------------------
-----------------------------------------------------
251:                 251 0e
-----------------------------------------------------
-----------------------------------------------------
253: __NR_lookup_dcookie 4s 1m
-----------------------------------------------------

Syscall param lookup_dcookie(cookie_low32) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(cookie_high32) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(len) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lookup_dcookie(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
9999:                9999 1e
-----------------------------------------------------
WARNING: unhandled syscall: 9999
Do not panic.  You may be able to fix this easily.
Read the file README_MISSING_SYSCALL_OR_IOCTL.
-----------------------------------------------------
  1:           __NR_exit 1s 0m
-----------------------------------------------------

Syscall param exit(error_code) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
