-----------------------------------------------------
153:     __NR_munlockall 0e
-----------------------------------------------------
-----------------------------------------------------
164:      __NR_setresuid 3s 0m
-----------------------------------------------------
Syscall param setresuid16(ruid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setresuid16(euid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setresuid16(suid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
165:      __NR_getresuid 3s 3m
-----------------------------------------------------

Syscall param getresuid16(ruid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresuid16(euid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresuid16(suid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresuid16(ruid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getresuid16(euid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getresuid16(suid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
167:   __NR_query_module 0e
-----------------------------------------------------
-----------------------------------------------------
170:      __NR_setresgid 3s 0m
-----------------------------------------------------

Syscall param setresgid16(rgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setresgid16(egid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param setresgid16(sgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
-----------------------------------------------------
171:      __NR_getresgid 3s 3m
-----------------------------------------------------

Syscall param getresgid16(rgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresgid16(egid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresgid16(sgid) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getresgid16(rgid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getresgid16(egid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param getresgid16(sgid) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
174:   __NR_rt_sigaction 4s 2m
-----------------------------------------------------

Syscall param rt_sigaction(signum) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param rt_sigaction(act) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param rt_sigaction(oldact) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param rt_sigaction(sigsetsize) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param rt_sigaction(act) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param rt_sigaction(oldact) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
182:          __NR_chown 3s 1m
-----------------------------------------------------

Syscall param chown16(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chown16(owner) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chown16(group) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param chown16(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
191:     __NR_ugetrlimit 2s 1m
-----------------------------------------------------

Syscall param getrlimit(resource) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getrlimit(rlim) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param getrlimit(rlim) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
195:         __NR_stat64 2s 2m
-----------------------------------------------------

Syscall param stat64(file_name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param stat64(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param stat64(file_name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param stat64(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
196:        __NR_lstat64 2s 2m
-----------------------------------------------------

Syscall param lstat64(file_name) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lstat64(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lstat64(file_name) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lstat64(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
197:        __NR_fstat64 2s 1m
-----------------------------------------------------

Syscall param fstat64(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fstat64(buf) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param fstat64(buf) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
198:       __NR_lchown32 3s 1m
-----------------------------------------------------

Syscall param lchown(path) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lchown(owner) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lchown(group) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param lchown(path) points to unaddressable byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
199:       __NR_getuid32 0e
-----------------------------------------------------
