new/new[] aligned failed and should throw an exception, but Valgrind
   cannot throw exceptions and so is aborting instead.  Sorry.
   ...
   by 0x........: operator new(unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (sized_aligned_new_delete_misaligned.cpp:69)
new/new[] aligned failed and should throw an exception, but Valgrind
   cannot throw exceptions and so is aborting instead.  Sorry.
   ...
   by 0x........: operator new[](unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (sized_aligned_new_delete_misaligned.cpp:81)
