Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator new(unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator new(unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete(void*, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator new[](unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator new[](unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete[](void*, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator new(unsigned long, std::align_val_t, std::nothrow_t const&) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator new(unsigned long, std::align_val_t, std::nothrow_t const&) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete(void*, std::align_val_t, std::nothrow_t const&) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator new[](unsigned long, std::align_val_t, std::nothrow_t const&) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator new[](unsigned long, std::align_val_t, std::nothrow_t const&) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete[](void*, std::align_val_t, std::nothrow_t const&) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: ...operator delete... (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete[](void*, unsigned long) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete(void*, unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete(void*, unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete[](void*, unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: operator delete[](void*, unsigned long, std::align_val_t) (vg_replace_malloc.c:...)
   by 0x........: main (in /usr/home/paulf/scratch/valgrind/memcheck/tests/sized_aligned_new_delete_args)

