
Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (supp.c:8)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 0 allocs, 0 frees, 0 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
