
Invalid free() / delete / delete[]
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: ddd (suppfree.c:7)
   by 0x........: ccc (suppfree.c:12)
   by 0x........: bbb (suppfree.c:17)
   Address 0x........ is 0 bytes inside a block of size 10 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: ddd (suppfree.c:6)
   by 0x........: ccc (suppfree.c:12)
   by 0x........: bbb (suppfree.c:17)

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 1 allocs, 2 frees, 10 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
