Invalid free() / delete / delete[]
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: ddd (suppfree.c:7)
   by 0x........: ccc (suppfree.c:12)
   by 0x........: bbb (suppfree.c:17)
   Address 0x........ is 0 bytes inside a block of size 10 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: ddd (suppfree.c:6)
   by 0x........: ccc (suppfree.c:12)
   by 0x........: bbb (suppfree.c:17)
