Emulation fatal error -- Valgrind cannot continue:
  PPC64 function redirection stack overflow
   at 0x........: ???
   by 0x........: fact2 (wrap8.c:78)
   by 0x........: ...
   by 0x........: fact1 (wrap8.c:65)
   by 0x........: ...
   by 0x........: fact2 (wrap8.c:79)
   by 0x........: ...
   by 0x........: fact1 (wrap8.c:65)
   by 0x........: ...
   by 0x........: fact2 (wrap8.c:79)
   by 0x........: ...
   by 0x........: fact1 (wrap8.c:65)

Valgrind has to exit now.  Sorry.

