Emulation fatal error -- Valgrind cannot continue:
  PPC64 function redirection stack overflow
   at 0x........: ???
   by 0x........: fact2 (wrap8.c:79)
   by 0x........: fact1 (wrap8.c:50)
   by 0x........: fact1 (wrap8.c:66)
   by 0x........: fact2 (wrap8.c:55)
   by 0x........: fact2 (wrap8.c:80)
   by 0x........: fact1 (wrap8.c:50)
   by 0x........: fact1 (wrap8.c:66)
   by 0x........: fact2 (wrap8.c:55)
   by 0x........: fact2 (wrap8.c:80)
   by 0x........: fact1 (wrap8.c:50)
   by 0x........: fact1 (wrap8.c:66)

Valgrind has to exit now.  Sorry.

