Test file created.
Syscall param writev(vector[...]) points to unaddressable byte(s)
   at 0x........: writev (in /...libc...)
   by 0x........: main (writev.c:56)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
Received EFAULT as expected

Syscall param writev(vector) points to unaddressable byte(s)
   at 0x........: writev (in /...libc...)
   by 0x........: main (writev.c:68)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
Received EINVAL as expected

Syscall param readv(vector) points to unaddressable byte(s)
   at 0x........: readv (in /...libc...)
   by 0x........: main (writev.c:76)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
Received EINVAL as expected
