#! /bin/sh

# Only one test uses this which calls syscall(SYS_sendfile)
# which is the only x86 syscall that uses 8 arguments
# The output includes --trace-syscalls=yes which is very verbose
# but we only want to see the sendfile line

# the libc signature for sendfile is
#     int sendfile(int fd, int s, off_t offset, size_t nbytes,
#                  struct sf_hdtr *hdtr, off_t *sbytes, int flags);
# The testcase uses values from 101 to 108 for the arguments
# (to make it easy to match the testcase to the log output)
# Some of the arguments are printed as hex, not too bad.
# Argument 3 is a 64bit value made up from the 32bit arguments
# 3 and 4 resulting in 7 values in the expected.

grep "SYSCALL.*sendfile" |
sed 's/==.*//' |
sed -E 's/\[[0-9]{5}/[xxxxx/'

