bc1eqz
bc1eqz:: result: b
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 21
bc1eqz:: result: 21
bc1eqz:: result: 21
bc1eqz:: result: 1d
bc1eqz:: result: 1d
bc1eqz:: result: 1d

bc1nez
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: b
bc1nez:: result: b
bc1nez:: result: b
bc1nez:: result: 21
bc1nez:: result: 21
bc1nez:: result: 21
