#! /bin/sh

# Anonymise paths like "/local/foo/bar/tests/baz/quux" (note "tests" is there)
#sed "s/\/.*\/tests\//\/...\/tests\//"

# Remove these three kinds of lines, which tend to appear beneath
# the stack frame of __libc_start_main
#    by 0x........: (within /.../tests/malloc2)
#    by 0x........: ??? (start.S:81)
#    by 0x........: function_name (in object_name)
sed "s/by 0x........: (within [^)]*)/by 0x........: .../" | \
sed "s/by 0x........: ??? ([^)]*)/by 0x........: .../" | \
sed "s/by 0x........: [a-zA-Z0-9_]* (in [^)]*)/by 0x........: .../"
