#! /bin/sh

# This filter should be applied to *every* stderr results.  It removes Valgrind
# startup stuff and pid numbers.

# Remove ==pid== and --pid-- and ++pid++ strings 
sed "s/\(==\|--\|++\)[0-9]\{3,5\}\1 //"                                |

# Remove "<name>, a <description> for x86-linux." line and the following
# copyright notice line.  Works for skin and core intro lines.
sed "/^.*, .* for x86-linux\./ , /./ d"                                | 

# Remove other introductory lines
sed "/Estimated CPU clock rate is [0-9]\+ MHz/d"                       |
sed "/For more details, rerun with: -v/d"                              |

# Reduce some libc incompatibility
sed "s/ __getsockname / getsockname /"                                 |
sed "s/ __sigaction / sigaction /"                                     |
sed "s/ __GI___/ __/"
