#! /bin/sh

dir=`dirname $0`

# Remove number and position of discards
sed "s/discard [0-9]\+ ([0-9]\+ -> [0-9]\+) translations in range/discard ... (... -> ...) translations in range/"     |

$dir/filter_addresses
