

FILE DESCRIPTORS: 5 open at exit.
Open AF_UNIX socket .: <unknown>
   at 0x........: socketpair (in /...libc...)
   by 0x........: main (fdleak_socketpair.c:15)

Open AF_UNIX socket .: <unknown>
   at 0x........: socketpair (in /...libc...)
   by 0x........: main (fdleak_socketpair.c:15)

Open file descriptor .: .
   <inherited from parent>

Open file descriptor .: .
   <inherited from parent>

Open file descriptor .: /dev/null
   <inherited from parent>


