

FILE DESCRIPTORS: 5 open at exit.
Open AF_UNIX socket .: <unknown>
   at 0x........: socketpair (in /...libc...)
   by 0x........: (below main)

Open AF_UNIX socket .: <unknown>
   at 0x........: socketpair (in /...libc...)
   by 0x........: (below main)

Open file descriptor .: .
   <inherited from parent>

Open file descriptor .: .
   <inherited from parent>

Open file descriptor .: /dev/null
   <inherited from parent>


