

FILE DESCRIPTORS: 5 open at exit.
Open AF_INET socket 4: 127.0.0.1:... <-> 127.0.0.1:...
   ...

Open AF_INET socket 3: 127.0.0.1:... <-> unbound
   ...

Open file descriptor ...: ...
   <inherited from parent>

Open file descriptor ...: ...
   <inherited from parent>

Open file descriptor ...: /dev/null
   <inherited from parent>



FILE DESCRIPTORS: 4 open at exit.
Open AF_INET socket 3: 127.0.0.1:... <-> 127.0.0.1:...
   ...

Open file descriptor ...: ...
   <inherited from parent>

Open file descriptor ...: ...
   <inherited from parent>

Open file descriptor ...: /dev/null
   <inherited from parent>


