

FILE DESCRIPTORS: 7 open (3 inherited) at exit.
Open file descriptor ...: ...
   <inherited from parent>

Open file descriptor ...: ...
   <inherited from parent>

Open file descriptor ...: /dev/null
   <inherited from parent>



FILE DESCRIPTORS: 6 open (3 inherited) at exit.
Open file descriptor ...: ...
   <inherited from parent>

Open file descriptor ...: ...
   <inherited from parent>

Open file descriptor ...: /dev/null
   <inherited from parent>


