

FILE DESCRIPTORS: 5 open at exit.
Open file descriptor .: /dev/null
   at 0x........: dup (in /...libc...)
   by 0x........: (below main) (in /...libc...)

Open file descriptor .: /dev/null
   at 0x........: open (in /...libc...)
   by 0x........: (below main) (in /...libc...)

Open file descriptor .: .
   <inherited from parent>

Open file descriptor .: .
   <inherited from parent>

Open file descriptor .: /dev/null
   <inherited from parent>


