#! /bin/sh

dir=`dirname $0`

$dir/../../tests/filter_stderr_basic |

# Filter out differences in the ioctls because IOC_NONE is
# not == 0 on all platforms.
sed 's/0x[13]/0x./' |

# Remove "Nulgrind, ..." line and the following copyright line.
sed "/^Nulgrind, the minimal Valgrind tool/ , /./ d"
