Warning: noted but unhandled ioctl 0x.2345670 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345671 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345672 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345673 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345674 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345675 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345676 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345677 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345678 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Warning: noted but unhandled ioctl 0x.2345679 with no direction hints.
   This could cause spurious value errors to appear.
   See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
