Open socket 3
close socket_fd 3
and close the socket again 3
File descriptor 3: AF_UNIX socket 3: <unknown> is already closed
   at 0x........: close (in /...libc...)
   by 0x........: main (socket_close.c:37)
 Previously closed
   at 0x........: close (in /...libc...)
   by 0x........: main (socket_close.c:33)
 Originally opened
   at 0x........: socket (in /...libc...)
   by 0x........: open_socket (socket_close.c:14)
   by 0x........: main (socket_close.c:28)
