bad
File descriptor was closed already
   at 0x........: write (in /...libc...)
   by 0x........: main
 Previously closed
   at 0x........: close (in /...libc...)
   by 0x........: main
 Originally opened
   at 0x........: dup (in /...libc...)
   by 0x........: main
File descriptor 7 was never created
   at 0x........: write (in /...libc...)
   by 0x........: main
File descriptor -7 Invalid file descriptor
   at 0x........: write (in /...libc...)
   by 0x........: main
File descriptor ...: ... is already closed
   at 0x........: close (in /...libc...)
   by 0x........: main
 Previously closed
   at 0x........: close (in /...libc...)
   by 0x........: main
 Originally opened
   at 0x........: dup (in /...libc...)
   by 0x........: main
File descriptor -7 Invalid file descriptor
   at 0x........: close (in /...libc...)
   by 0x........: main
