#! /bin/sh

# It's impossible to get exact matches for copy counts because even trivial C
# programs do a few memcpy/strcpy calls. So we allow some fuzzy matching.
# So we allow 1,200,000..1,209,999 bytes and 1,200..1,299 blocks.

./filter_stderr "$@" |
sed -e "s/1,20.,... bytes in 1,2.. blocks/1,200,... bytes in 1,2.. blocks/"

