#! /bin/sh

# Solaris libc prints 'Inf' or 'Infinity' instead of 'inf'
# and 'NaN' instead of 'nan'. Filter these differences here.
sed "s/-Infinity/     -inf/g" |
sed "s/Infinity/     inf/g"   |
sed "s/Inf/inf/g"             |
sed "s/NaN/nan/g"

exit 0

