
Syscall param copy_file_range("off_in") contains uninitialised byte(s)
   ...
   by 0x........: main (sys-copy_file_range.c:57)

Syscall param copy_file_range(off_out) points to unaddressable byte(s)
   ...
   by 0x........: main (sys-copy_file_range.c:58)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Warning: invalid file descriptor -1 in syscall copy_file_range(fd_in)()

HEAP SUMMARY:
    in use at exit: 0 bytes in 0 blocks
  total heap usage: 0 allocs, 0 frees, 0 bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

Use --track-origins=yes to see where uninitialised values come from
For lists of detected and suppressed errors, rerun with: -s
ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
