Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:83)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:39)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:90)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:39)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:90)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:35)

