Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_eflags2.c:75)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_eflags2.c:35)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_eflags2.c:75)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_eflags2.c:35)

