Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:80)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:36)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:36)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:32)

