LOAD AND TEST short BFP
ltebr 100.000000 -> 100.000000   cc = 2
ltebr -10.500000 -> -10.500000   cc = 1
ltebr 0.000000 -> 0.000000   cc = 0
ltebr nan -> nan   cc = 3
LOAD AND TEST long BFP
ltdbr 100.000000 -> 100.000000   cc = 2
ltdbr -10.500000 -> -10.500000   cc = 1
ltdbr 0.000000 -> 0.000000   cc = 0
ltdbr nan -> nan   cc = 3
LOAD AND TEST extended BFP
ltxbr 100.000000 -> 100.000000   cc = 2
ltxbr -10.500000 -> -10.500000   cc = 1
ltxbr 0.000000 -> 0.000000   cc = 0
ltxbr nan -> nan   cc = 3

LOAD LENGTHENED short BFP -> long BFP
ldebr 101.5 -> 101.500000
ldebr -11.1 -> -11.100000
ldebr 0 -> 0.000000
ldebr 7e-06 -> 0.000007
ldebr nan -> nan
ldebr inf -> inf
ldebr -inf -> -inf
LOAD LENGTHENED short BFP -> extended BFP
lxebr 101.5 -> 101.500000
lxebr -11.1 -> -11.100000
lxebr 0 -> 0.000000
lxebr 7e-06 -> 0.000007
lxebr nan -> nan
lxebr inf -> inf
lxebr -inf -> -inf
LOAD LENGTHENED long BFP -> extended BFP
lxdbr 101.5 -> 101.500000
lxdbr -11.1 -> -11.100000
lxdbr 0 -> 0.000000
lxdbr 7e-16 -> 7e-16
lxdbr nan -> nan
lxdbr inf -> inf
lxdbr -inf -> -inf

LOAD ZERO
lzer  gpr value = 0
lzdr  gpr value = 0
lzdr  gpr values = 0 0
