------- Copy 10+1 bytes from buffer to target
------- EX to OR in the length
before: buffer = |0123456789abcdef|
before: target = |XXXXXXXXXXXXXXXX|
after:  buffer = |0123456789abcdef|
after:  target = |0123456789aXXXXX|

------- EX 0,... has no effect (writes out target)
        target = |0123456789aXXXXX|

------- EX to OR in the syscall number (writes out target)
        target = |0123456789aXXXXX|

