
Emulation warning: unsupported action:
  The specified rounding mode cannot be supported. That
  feature requires the floating point extension facility
  which is not available on this host. Continuing using
  the rounding mode from FPC. Results may differ!
   at 0x........: main (fpext_warn.c:11)
Emulation warning: unsupported action:
  The specified rounding mode cannot be supported. That
  feature requires the floating point extension facility
  which is not available on this host. Continuing using
  the rounding mode from FPC. Results may differ!
   at 0x........: main (fpext_warn.c:12)
Emulation warning: unsupported action:
  The specified rounding mode cannot be supported. That
  feature requires the floating point extension facility
  which is not available on this host. Continuing using
  the rounding mode from FPC. Results may differ!
   at 0x........: main (fpext_warn.c:13)

