
vex s390->IR: unknown insn: 0000
valgrind: Unrecognised instruction at address 0x.........
   at 0x........: main (op_exception.c:23)
Your program just tried to execute an instruction that Valgrind
did not recognise.  There are two possible reasons for this.
1. Your program has a bug and erroneously jumped to a non-code
   location.  If you are running Memcheck and you just saw a
   warning about a bad jump, it's probably your program's fault.
2. The instruction is legitimate but Valgrind doesn't handle it,
   i.e. it's Valgrind's fault.  If you think this is the case or
   you are not sure, please let us know and we'll try to fix it.
Either way, Valgrind will now raise a SIGILL signal which will
probably kill your program.
vex s390->IR: unknown insn: 0000
valgrind: Unrecognised instruction at address 0x.........
   at 0x........: main (op_exception.c:27)
Your program just tried to execute an instruction that Valgrind
did not recognise.  There are two possible reasons for this.
1. Your program has a bug and erroneously jumped to a non-code
   location.  If you are running Memcheck and you just saw a
   warning about a bad jump, it's probably your program's fault.
2. The instruction is legitimate but Valgrind doesn't handle it,
   i.e. it's Valgrind's fault.  If you think this is the case or
   you are not sure, please let us know and we'll try to fix it.
Either way, Valgrind will now raise a SIGILL signal which will
probably kill your program.
vex s390->IR: unknown insn: FFFF FFFF FFFF
valgrind: Unrecognised instruction at address 0x.........
   at 0x........: main (op_exception.c:30)
Your program just tried to execute an instruction that Valgrind
did not recognise.  There are two possible reasons for this.
1. Your program has a bug and erroneously jumped to a non-code
   location.  If you are running Memcheck and you just saw a
   warning about a bad jump, it's probably your program's fault.
2. The instruction is legitimate but Valgrind doesn't handle it,
   i.e. it's Valgrind's fault.  If you think this is the case or
   you are not sure, please let us know and we'll try to fix it.
Either way, Valgrind will now raise a SIGILL signal which will
probably kill your program.
vex s390->IR: unknown insn: 0000
valgrind: Unrecognised instruction at address 0x.........
   at 0x........: main (op_exception.c:34)
Your program just tried to execute an instruction that Valgrind
did not recognise.  There are two possible reasons for this.
1. Your program has a bug and erroneously jumped to a non-code
   location.  If you are running Memcheck and you just saw a
   warning about a bad jump, it's probably your program's fault.
2. The instruction is legitimate but Valgrind doesn't handle it,
   i.e. it's Valgrind's fault.  If you think this is the case or
   you are not sure, please let us know and we'll try to fix it.
Either way, Valgrind will now raise a SIGILL signal which will
probably kill your program.

