setting FPC rounding mode to [-> near]
load rounded  d = 12345678.250     f = 12345678.000
setting FPC rounding mode to [-> zero]
load rounded  d = 12345678.250     f = 12345678.000
setting FPC rounding mode to [-> +inf]
load rounded  d = 12345678.250     f = 12345679.000
setting FPC rounding mode to [-> -inf]
load rounded  d = 12345678.250     f = 12345678.000
======================================
setting FPC rounding mode to [-> near]
load rounded  d = 12345678.750     f = 12345679.000
setting FPC rounding mode to [-> zero]
load rounded  d = 12345678.750     f = 12345678.000
setting FPC rounding mode to [-> +inf]
load rounded  d = 12345678.750     f = 12345679.000
setting FPC rounding mode to [-> -inf]
load rounded  d = 12345678.750     f = 12345678.000
======================================
setting FPC rounding mode to [-> near]
load rounded  d = -12345678.250     f = -12345678.000
setting FPC rounding mode to [-> zero]
load rounded  d = -12345678.250     f = -12345678.000
setting FPC rounding mode to [-> +inf]
load rounded  d = -12345678.250     f = -12345678.000
setting FPC rounding mode to [-> -inf]
load rounded  d = -12345678.250     f = -12345679.000
======================================
setting FPC rounding mode to [-> near]
load rounded  d = -12345678.750     f = -12345679.000
setting FPC rounding mode to [-> zero]
load rounded  d = -12345678.750     f = -12345678.000
setting FPC rounding mode to [-> +inf]
load rounded  d = -12345678.750     f = -12345678.000
setting FPC rounding mode to [-> -inf]
load rounded  d = -12345678.750     f = -12345679.000

load lengthened  d =     1234.5677490234375    f =     1234.5677490234375
