the value of cc is 0 and #double words is 3
the value of cc is 0 and #double words is 3
The z/Architecture architectural mode is installed and active
the value of cc is 0 and #double words is 3
STFLE facility is installed
the value of cc is 3 and #double words is 3
the value of cc is 3 and #double words is 3
The z/Architecture architectural mode is installed and active
the value of cc is 3 and #double words is 3
No MSA facility available
