0 bytes translated
the translated values is
0 bytes translated
the translated values is
0 bytes translated
the translated values is
6 bytes translated
the translated values is cc dd ff cc ab ca
10 bytes translated
the translated values is cc dd ff cc ab ca bc cc dd ea
2 bytes translated
the translated values is cc dd 0 0 0 0
0 bytes translated
the translated values is cc dd 0 0 0 0
9 bytes translated
the translated values is cc dd ff cc ab ca bc cc dd 0
