0 bytes translated
the translated values is
0 bytes translated
the translated values is
0 bytes translated
the translated values is
2 bytes translated
the translated values is ffff dddd
5 bytes translated
the translated values is ffff dddd ffff cccc abab
0 bytes translated
the translated values is 0 0 0 0 0
3 bytes translated
the translated values is ffff dddd ffff 0 0
9 bytes translated
the translated values is ffff dddd ffff cccc abab caca bcbc cccc dada 0
