posting 1 on 3
waiting on 4
wait completed on 4: count=1
posting 1 on 3
waiting on 4
wait completed on 4: count=1
posting 5 on 3
waiting 5 times on 4
wait completed on 4: count=1
wait completed on 4: count=1
wait completed on 4: count=1
wait completed on 4: count=1
wait completed on 4: count=1
posting 1 on 4
waiting on 3
wait completed on 3: count=1
posting 1 on 4
waiting on 3
wait completed on 3: count=1
posting 5 on 4
waiting 5 times on 3
wait completed on 3: count=1
wait completed on 3: count=1
wait completed on 3: count=1
wait completed on 3: count=1
wait completed on 3: count=1
