Syscall param fexecve(fd) contains uninitialised byte(s)
   at 0x........: fexecve (in /...libc...)
   by 0x........: main (fexecve.c:29)

Syscall param fexecve(argv[0]) points to unaddressable byte(s)
   at 0x........: fexecve (in /...libc...)
   by 0x........: main (fexecve.c:29)
 Address 0x........ is 0 bytes inside a block of size 10 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fexecve.c:27)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (fexecve.c:19)

Syscall param fexecve(envp[i]) points to unaddressable byte(s)
   at 0x........: fexecve (in /...libc...)
   by 0x........: main (fexecve.c:29)
 Address 0x........ is 0 bytes inside a block of size 8 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fexecve.c:28)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (fexecve.c:20)

