#! /bin/sh

gsed 's/Invalid write of size 8/Invalid write of size 4/' |
gsed 's/is [4-9][0-9] bytes inside a block of size 100 free/is ... bytes inside a block of size 100 free/' |


../filter_stderr "$@"

exit 0
