Syscall param getcontext(ucp) points to unaddressable byte(s)
   ...
   by 0x........: main (get_set_context.c:51)
 Address 0x........ is 0 bytes inside a block of size ... alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (get_set_context.c:46)

Syscall param setcontext(ucp) points to unaddressable byte(s)
   ...
   by 0x........: main (get_set_context.c:59)
 Address 0x........ is 0 bytes inside a block of size ... alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (get_set_context.c:46)

Syscall param swapcontext(ucp) points to unaddressable byte(s)
   ...
   by 0x........: main (get_set_context.c:69)
 Address 0x........ is 0 bytes inside a block of size ... alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (get_set_context.c:46)

Syscall param swapcontext(oucp) points to unaddressable byte(s)
   ...
   by 0x........: main (get_set_context.c:69)
 Address 0x........ is 0 bytes inside a block of size ... alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (get_set_context.c:47)

