Syscall param getfh(path) points to unaddressable byte(s)
   at 0x........: getfh (in /...libc...)
   by 0x........: main (getfh.c:40)
 Address 0x........ is 0 bytes inside a block of size 23 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:37)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (getfh.c:34)

Syscall param getfh(fhp) points to unaddressable byte(s)
   at 0x........: getfh (in /...libc...)
   by 0x........: main (getfh.c:40)
 Address 0x........ is 0 bytes inside a block of size 28 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:38)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:35)

Syscall param lgetfh(path) points to unaddressable byte(s)
   at 0x........: lgetfh (in /...libc...)
   by 0x........: main (getfh.c:41)
 Address 0x........ is 0 bytes inside a block of size 23 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:37)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (getfh.c:34)

Syscall param lgetfh(fhp) points to unaddressable byte(s)
   at 0x........: lgetfh (in /...libc...)
   by 0x........: main (getfh.c:41)
 Address 0x........ is 0 bytes inside a block of size 28 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:38)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:35)

Syscall param getfhat(fd) contains uninitialised byte(s)
   at 0x........: getfhat (in /...libc...)
   by 0x........: main (getfh.c:43)

Syscall param getfhat(flag) contains uninitialised byte(s)
   at 0x........: getfhat (in /...libc...)
   by 0x........: main (getfh.c:43)

Syscall param getfhat(path) points to unaddressable byte(s)
   at 0x........: getfhat (in /...libc...)
   by 0x........: main (getfh.c:43)
 Address 0x........ is 0 bytes inside a block of size 23 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:37)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (getfh.c:34)

Syscall param getfhat(fhp) points to unaddressable byte(s)
   at 0x........: getfhat (in /...libc...)
   by 0x........: main (getfh.c:43)
 Address 0x........ is 0 bytes inside a block of size 28 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:38)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (getfh.c:35)

