
Warning: bad or unimplemented kenv action: 1764
Syscall param kenv(action) contains uninitialised byte(s)
   at 0x........: kenv (in /...libc...)
   by 0x........: main (kenv.cpp:111)

Syscall param kenv(name) contains uninitialised byte(s)
   at 0x........: kenv (in /...libc...)
   by 0x........: main (kenv.cpp:111)

Syscall param kenv(value) contains uninitialised byte(s)
   at 0x........: kenv (in /...libc...)
   by 0x........: main (kenv.cpp:111)

Syscall param kenv(len) contains uninitialised byte(s)
   at 0x........: kenv (in /...libc...)
   by 0x........: main (kenv.cpp:111)

Syscall param kenv(name) points to unaddressable byte(s)
   at 0x........: kenv (in /...libc...)
   by 0x........: main (kenv.cpp:117)
 Address 0x........ is 0 bytes inside a block of size 32 free'd
   at 0x........: ...operator delete[]... (vg_replace_malloc.c:...)
   by 0x........: main (kenv.cpp:116)
 Block was alloc'd at
   at 0x........: ...operator new[]... (vg_replace_malloc.c:...)
   by 0x........: main (kenv.cpp:114)

Syscall param kenv(value) points to unaddressable byte(s)
   at 0x........: kenv (in /...libc...)
   by 0x........: main (kenv.cpp:120)
 Address 0x........ is 0 bytes inside a block of size 32 free'd
   at 0x........: ...operator delete[]... (vg_replace_malloc.c:...)
   by 0x........: main (kenv.cpp:119)
 Block was alloc'd at
   at 0x........: ...operator new[]... (vg_replace_malloc.c:...)
   by 0x........: main (kenv.cpp:118)

Syscall param kenv(value) points to unaddressable byte(s)
   at 0x........: kenv (in /...libc...)
   by 0x........: main (kenv.cpp:121)
 Address 0x........ is 0 bytes after a block of size 1,024 alloc'd
   at 0x........: ...operator new[]... (vg_replace_malloc.c:...)
   by 0x........: main (kenv.cpp:19)


HEAP SUMMARY:
    in use at exit: 0 bytes in 0 blocks
  total heap usage: 5 allocs, 5 frees, XXX bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

Use --track-origins=yes to see where uninitialised values come from
For lists of detected and suppressed errors, rerun with: -s
ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 0 from 0)
