Invalid alignment value: 3 (should be power of 2)
   at 0x........: memalign (vg_replace_malloc.c:...)
   by 0x........: main (memalign.c:39)

Invalid alignment value: 5 (should be power of 2)
   at 0x........: memalign (vg_replace_malloc.c:...)
   by 0x........: main (memalign.c:45)

Invalid alignment value: 7 (should be power of 2)
   at 0x........: memalign (vg_replace_malloc.c:...)
   by 0x........: main (memalign.c:49)

Invalid alignment value: 9 (should be power of 2)
   at 0x........: memalign (vg_replace_malloc.c:...)
   by 0x........: main (memalign.c:55)

Invalid alignment value: 31 (should be power of 2)
   at 0x........: memalign (vg_replace_malloc.c:...)
   by 0x........: main (memalign.c:59)

Invalid alignment value: 33 (should be power of 2)
   at 0x........: memalign (vg_replace_malloc.c:...)
   by 0x........: main (memalign.c:65)

Invalid alignment value: 4095 (should be power of 2)
   at 0x........: memalign (vg_replace_malloc.c:...)
   by 0x........: main (memalign.c:69)

Invalid alignment value: 4097 (should be power of 2)
   at 0x........: memalign (vg_replace_malloc.c:...)
   by 0x........: main (memalign.c:75)

