Invalid write of size 4
   at 0x........: main (realpathat.c:18)
 Address 0x........ is 0 bytes inside a block of size 1 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:16)

Invalid write of size 4
   at 0x........: main (realpathat.c:19)
 Address 0x........ is 0 bytes inside a block of size 1 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:17)

Syscall param __realpathat(fd) contains uninitialised byte(s)
   ...
   by 0x........: main (realpathat.c:20)

Syscall param __realpathat(size) contains uninitialised byte(s)
   ...
   by 0x........: main (realpathat.c:20)

Invalid read of size 1
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 0 bytes inside a block of size 31 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:28)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (realpathat.c:26)

Syscall param __realpathat(path) points to unaddressable byte(s)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 0 bytes inside a block of size 31 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:28)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (realpathat.c:26)

Syscall param __realpathat(buf) points to unaddressable byte(s)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 0 bytes inside a block of size 100 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:27)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:25)

Invalid read of size 1
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 0 bytes inside a block of size 31 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:28)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (realpathat.c:26)

Syscall param __getcwd(buf) points to unaddressable byte(s)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 0 bytes inside a block of size 100 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:27)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:25)

Invalid read of size 1
   at 0x........: strlcpy (vg_replace_strmem.c:...)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 0 bytes inside a block of size 31 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:28)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (realpathat.c:26)

Invalid read of size 1
   at 0x........: strlcpy (vg_replace_strmem.c:...)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 1 bytes inside a block of size 31 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:28)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (realpathat.c:26)

Invalid read of size 1
   at 0x........: strlcpy (vg_replace_strmem.c:...)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 30 bytes inside a block of size 31 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:28)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   ...
   by 0x........: main (realpathat.c:26)

Invalid write of size 2
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 55 bytes inside a block of size 100 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:27)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:25)

Invalid read of size 1
   at 0x........: strlcat (vg_replace_strmem.c:...)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 56 bytes inside a block of size 100 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:27)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:25)

Invalid write of size 1
   at 0x........: strlcat (vg_replace_strmem.c:...)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 56 bytes inside a block of size 100 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:27)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:25)

Invalid write of size 1
   at 0x........: strlcat (vg_replace_strmem.c:...)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 66 bytes inside a block of size 100 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:27)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:25)

Syscall param fstatat(path) points to unaddressable byte(s)
   ...
   by 0x........: main (realpathat.c:30)
 Address 0x........ is 56 bytes inside a block of size 100 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:27)
 Block was alloc'd at
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (realpathat.c:25)

