---------------------------------------------------------
583:             SYS_kqueuex  1s 0m
---------------------------------------------------------
Syscall param kqueuex(flags) contains uninitialised byte(s)
   ...

---------------------------------------------------------
584:          SYS_membarrier  3s 0m
---------------------------------------------------------
Syscall param membarrier(cmd) contains uninitialised byte(s)
   ...

Syscall param membarrier(flags) contains uninitialised byte(s)
   ...

Syscall param membarrier(cpu_id) contains uninitialised byte(s)
   ...

---------------------------------------------------------
585:      SYS_timerfd_create  2s 0m
---------------------------------------------------------
Syscall param timerfd_create(clockid) contains uninitialised byte(s)
   ...

Syscall param timerfd_create(flags) contains uninitialised byte(s)
   ...

---------------------------------------------------------
586:     SYS_timerfd_gettime  2s 1m
---------------------------------------------------------
Syscall param timerfd_gettime(fd) contains uninitialised byte(s)
   ...

Syscall param timerfd_gettime(curr_value) contains uninitialised byte(s)
   ...

Syscall param timerfd_gettime(curr_value) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
587:     SYS_timerfd_settime 3s 2m
---------------------------------------------------------
Syscall param timerfd_settime(fd) contains uninitialised byte(s)
   ...

Syscall param timerfd_settime(flags) contains uninitialised byte(s)
   ...

Syscall param timerfd_settime(new_value) contains uninitialised byte(s)
   ...

Syscall param timerfd_settime(new_value) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param timerfd_settime(old_value) points to unaddressable byte(s)
   ...
 Address 0x........ is on thread 1's stack
 .... bytes below stack pointer

