---------------------------------------------------------
463:              SYS_abort2 3s 2m
---------------------------------------------------------
Syscall param abort2(why) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar_abort2.c:10)

Syscall param abort2(nargs) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar_abort2.c:10)

Syscall param abort2(args) contains uninitialised byte(s)
   ...
   by 0x........: main (scalar_abort2.c:10)

Syscall param abort2(why) points to unaddressable byte(s)
   ...
   by 0x........: main (scalar_abort2.c:10)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param abort2(args points to unaddressable byte(s)
   ...
   by 0x........: main (scalar_abort2.c:10)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

