---------------------------------------------------------
577:         SYS___specialfd 3s 1m
---------------------------------------------------------
Syscall param __specialfd(type) contains uninitialised byte(s)
   ...

Syscall param __specialfd(req) contains uninitialised byte(s)
   ...

Syscall param __specialfd(len) contains uninitialised byte(s)
   ...

Syscall param __specialfd(req) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

