realloc() with size 0
   at 0x........: reallocf (vg_replace_malloc.c:...)
   by 0x........: main (static_allocs.c:36)
 Address 0x........ is 0 bytes inside a block of size 160 alloc'd
   at 0x........: calloc (vg_replace_malloc.c:...)
   by 0x........: main (static_allocs.c:35)

1 bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: reallocf (vg_replace_malloc.c:...)
   by 0x........: main (static_allocs.c:36)

10 bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: realloc (vg_replace_malloc.c:...)
   by 0x........: main (static_allocs.c:34)

