
about to do 19 [0]
Invalid read of size 4
   at 0x........: main (and.c:19)
 Address 0x........ is not derived from any known block
about to do 19 [-1]

Invalid read of size 4
   at 0x........: main (and.c:19)
 Address 0x........ is not derived from any known block
about to do 21 [0]

Invalid read of size 4
   at 0x........: main (and.c:21)
 Address 0x........ is not derived from any known block
about to do 21 [-1]

Invalid read of size 4
   at 0x........: main (and.c:21)
 Address 0x........ is not derived from any known block
about to do 22 [0]
about to do 22 [-1]

Invalid read of size 4
   at 0x........: main (and.c:22)
 Address 0x........ is 4 bytes before the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 24 [0]

Invalid read of size 4
   at 0x........: main (and.c:24)
 Address 0x........ is not derived from any known block
about to do 24 [-1]

Invalid read of size 4
   at 0x........: main (and.c:24)
 Address 0x........ is not derived from any known block
about to do 25 [0]
about to do 25 [-1]

Invalid read of size 4
   at 0x........: main (and.c:25)
 Address 0x........ is 4 bytes before the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 27 [0]
about to do 27 [-1]

Invalid read of size 4
   at 0x........: main (and.c:27)
 Address 0x........ is 4 bytes before the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)

Invalid arguments to And32/And64
   at 0x........: main (and.c:28)
 First arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
 Second arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 28 [0]

Invalid read of size 4
   at 0x........: main (and.c:28)
 Address 0x........ is not derived from any known block
about to do 28 [-1]

Invalid read of size 4
   at 0x........: main (and.c:28)
 Address 0x........ is not derived from any known block
about to do 30 [0]

Invalid read of size 4
   at 0x........: main (and.c:30)
 Address 0x........ is not derived from any known block
about to do 30 [-1]

Invalid read of size 4
   at 0x........: main (and.c:30)
 Address 0x........ is not derived from any known block
about to do 31 [0]

Invalid read of size 4
   at 0x........: main (and.c:31)
 Address 0x........ is not derived from any known block
about to do 31 [-1]

Invalid read of size 4
   at 0x........: main (and.c:31)
 Address 0x........ is not derived from any known block
about to do 33 [0]

Invalid read of size 4
   at 0x........: main (and.c:33)
 Address 0x........ is not derived from any known block
about to do 33 [-1]

Invalid read of size 4
   at 0x........: main (and.c:33)
 Address 0x........ is not derived from any known block
about to do 34 [0]

Invalid read of size 4
   at 0x........: main (and.c:34)
 Address 0x........ is not derived from any known block
about to do 34 [-1]

Invalid read of size 4
   at 0x........: main (and.c:34)
 Address 0x........ is not derived from any known block
about to do 36 [0]
about to do 36 [-1]
about to do 37 [0]

Invalid read of size 4
   at 0x........: main (and.c:37)
 Address 0x........ is not derived from any known block
about to do 37 [-1]

Invalid read of size 4
   at 0x........: main (and.c:37)
 Address 0x........ is not derived from any known block
about to do 38 [0]

Invalid read of size 4
   at 0x........: main (and.c:38)
 Address 0x........ is not derived from any known block
about to do 38 [-1]

Invalid read of size 4
   at 0x........: main (and.c:38)
 Address 0x........ is not derived from any known block
about to do 39 [0]
about to do 39 [-1]
about to do 40 [0]
about to do 40 [-1]
about to do 42 [0]

Invalid read of size 4
   at 0x........: main (and.c:42)
 Address 0x........ is not derived from any known block
about to do 42 [-1]

Invalid read of size 4
   at 0x........: main (and.c:42)
 Address 0x........ is not derived from any known block
about to do 43 [0]

Invalid read of size 4
   at 0x........: main (and.c:43)
 Address 0x........ is not derived from any known block
about to do 43 [-1]

Invalid read of size 4
   at 0x........: main (and.c:43)
 Address 0x........ is not derived from any known block
about to do 45 [0]

Invalid read of size 4
   at 0x........: main (and.c:45)
 Address 0x........ is not derived from any known block
about to do 45 [-1]

Invalid read of size 4
   at 0x........: main (and.c:45)
 Address 0x........ is not derived from any known block
about to do 46 [0]

Invalid read of size 4
   at 0x........: main (and.c:46)
 Address 0x........ is not derived from any known block
about to do 46 [-1]

Invalid read of size 4
   at 0x........: main (and.c:46)
 Address 0x........ is not derived from any known block

ERROR SUMMARY: 32 errors from 32 contexts (suppressed: 0 from 0)
