
Invalid ADD
   at 0x........: main (arith.c:19)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Both args derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith.c:9)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid AND
   at 0x........: main (arith.c:21)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith.c:9)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Second arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith.c:8)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid IDIV
   at 0x........: main (arith.c:27)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Both args derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith.c:9)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid IDIV
   at 0x........: main (arith.c:28)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First arg not a pointer
Second arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith.c:9)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid DIV
   at 0x........: main (arith.c:31)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Both args derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith.c:9)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid DIV
   at 0x........: main (arith.c:32)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First arg not a pointer
Second arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith.c:9)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid IMUL
   at 0x........: main (arith.c:34)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Both args derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith.c:9)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 0 from 0)
