
about to do 14 [0]
Invalid read of size 4
   at 0x........: main (not.c:14)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 14 [-1]

Invalid read of size 4
   at 0x........: main (not.c:14)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 16 [0]

Invalid read of size 4
   at 0x........: main (not.c:16)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 16 [-1]

Invalid read of size 4
   at 0x........: main (not.c:16)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 18 [0]

Invalid read of size 4
   at 0x........: main (not.c:18)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 18 [-1]

Invalid read of size 4
   at 0x........: main (not.c:18)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 20 [0]

Invalid read of size 4
   at 0x........: main (not.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 20 [-1]

Invalid read of size 4
   at 0x........: main (not.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 22 [0]

Invalid read of size 4
   at 0x........: main (not.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block
about to do 22 [-1]

Invalid read of size 4
   at 0x........: main (not.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is not derived from any known block


ERROR SUMMARY: 10 errors from 10 contexts (suppressed: 0 from 0)
