
about to do 14 [0]
Invalid read of size 4
   at 0x........: main (or.c:14)
 Address 0x........ is not derived from any known block
about to do 14 [-1]

Invalid read of size 4
   at 0x........: main (or.c:14)
 Address 0x........ is not derived from any known block
about to do 16 [0]
about to do 16 [-1]

Invalid read of size 4
   at 0x........: main (or.c:16)
 Address 0x........ is 4 bytes before the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 18 [0]
about to do 18 [-1]

Invalid read of size 4
   at 0x........: main (or.c:18)
 Address 0x........ is 4 bytes before the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)

Invalid OR
   at 0x........: main (or.c:20)
Both args derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 20 [0]

Invalid read of size 4
   at 0x........: main (or.c:20)
 Address 0x........ is not derived from any known block
about to do 20 [-1]

Invalid read of size 4
   at 0x........: main (or.c:20)
 Address 0x........ is not derived from any known block

Invalid arguments to Or32/Or64
   at 0x........: main (or.c:21)
 First arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
 Second arg derived from address 0x........ of 40-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 21 [0]

Invalid read of size 4
   at 0x........: main (or.c:21)
 Address 0x........ is not derived from any known block
about to do 21 [-1]

Invalid read of size 4
   at 0x........: main (or.c:21)
 Address 0x........ is not derived from any known block
about to do 23 [0]
about to do 23 [-1]
about to do 24 [0]
about to do 24 [-1]
about to do 26 [0]
about to do 26 [-1]
about to do 27 [0]
about to do 27 [-1]
about to do 29 [0]
about to do 29 [-1]
about to do 30 [0]
about to do 30 [-1]
about to do 31 [0]
about to do 31 [-1]
about to do 32 [0]
about to do 32 [-1]
about to do 33 [0]
about to do 33 [-1]
about to do 35 [0]
about to do 35 [-1]
about to do 36 [0]
about to do 36 [-1]
about to do 38 [0]
about to do 38 [-1]
about to do 39 [0]
about to do 39 [-1]


ERROR SUMMARY: 10 errors from 10 contexts (suppressed: 0 from 0)
