
Invalid write of size 4
   at 0x........: pthread_key_create (in /...libpthread...)
   by 0x........: main (pth_create.c:17)
 Address 0x........ is 1 bytes inside the accessing pointer's
 legitimate range, a block of size 4 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (pth_create.c:14)

Invalid write of size 4
   at 0x........: pthread_key_create (in /...libpthread...)
   by 0x........: main (pth_create.c:19)
 Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, a block of size 4 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (pth_create.c:18)


ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
