
Invalid read of size 4
   at 0x........: strlen (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is 12 bytes inside the accessing pointer's
 legitimate range, a block of size 13 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: __strdup (in /...libc...)
   by 0x........: main (strlen.c:14)

Invalid read of size 4
   at 0x........: strchr (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is 12 bytes inside the accessing pointer's
 legitimate range, a block of size 13 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: __strdup (in /...libc...)
   by 0x........: main (strlen.c:14)

Invalid read of size 4
   at 0x........: strrchr (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is 12 bytes inside the accessing pointer's
 legitimate range, a block of size 13 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: __strdup (in /...libc...)
   by 0x........: main (strlen.c:14)

Invalid read of size 4
   at 0x........: strrchr (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
 Address 0x........ is 12 bytes inside the accessing pointer's
 legitimate range, a block of size 13 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: __strdup (in /...libc...)
   by 0x........: main (strlen.c:14)


ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
