
about to do 15 [0]
Invalid read of size 4
   at 0x........: main (sub.c:15)
 Address 0x........ is not derived from any known block
about to do 15 [-1]

Invalid read of size 4
   at 0x........: main (sub.c:15)
 Address 0x........ is not derived from any known block
about to do 17 [0]

Invalid read of size 4
   at 0x........: main (sub.c:17)
 Address 0x........ is not derived from any known block
about to do 17 [-1]

Invalid read of size 4
   at 0x........: main (sub.c:17)
 Address 0x........ is not derived from any known block
about to do 19 [0]
about to do 19 [-1]

Invalid read of size 4
   at 0x........: main (sub.c:19)
 Address 0x........ is 4 bytes before the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 21 [0]
about to do 21 [-1]
about to do 23 [0]
about to do 23 [-1]
about to do 24 [0]
about to do 24 [-1]
about to do 26 [0]
about to do 26 [-1]
about to do 27 [0]
about to do 27 [-1]
about to do 29 [0]

Invalid read of size 4
   at 0x........: main (sub.c:29)
 Address 0x........ is not derived from any known block
about to do 29 [-1]

Invalid read of size 4
   at 0x........: main (sub.c:29)
 Address 0x........ is not derived from any known block
about to do 30 [0]
about to do 30 [-1]
about to do 31 [0]
about to do 31 [-1]
about to do 32 [0]

Invalid read of size 4
   at 0x........: main (sub.c:32)
 Address 0x........ is not derived from any known block
about to do 32 [-1]

Invalid read of size 4
   at 0x........: main (sub.c:32)
 Address 0x........ is not derived from any known block
about to do 34 [0]
about to do 34 [-1]
about to do 35 [0]
about to do 35 [-1]
about to do 37 [0]

Invalid read of size 4
   at 0x........: main (sub.c:37)
 Address 0x........ is ... bytes before the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 37 [-1]

Invalid read of size 4
   at 0x........: main (sub.c:37)
 Address 0x........ is ... bytes before the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 38 [0]

Invalid read of size 4
   at 0x........: main (sub.c:38)
 Address 0x........ is ... bytes after the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)
about to do 38 [-1]

Invalid read of size 4
   at 0x........: main (sub.c:38)
 Address 0x........ is ... bytes after the accessing pointer's
 legitimate range, a block of size 40 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (arith_include2.c:22)


ERROR SUMMARY: 13 errors from 13 contexts (suppressed: 0 from 0)
