
Invalid read of size 1
   at 0x........: main (supp.c:13)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 1 bytes before the accessing pointer's
 legitimate range, the 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (supp.c:12)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

---- Print suppression ? --- [Return/N/n/Y/y/C/c] ---- {
   <insert a suppression name here>
   Annelid:LoadStore
   fun:main
   fun:__libc_start_main
   obj:*/annelid/tests/supp
}

Invalid ADD
   at 0x........: main (supp.c:14)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Both args derived from address 0x........ of 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (supp.c:12)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

---- Print suppression ? --- [Return/N/n/Y/y/C/c] ---- {
   <insert a suppression name here>
   Annelid:Arith
   fun:main
   fun:__libc_start_main
   obj:*/annelid/tests/supp
}
Warning: invalid file descriptor -1 in syscall write()

Syscall param write(buf) is non-contiguous
   at 0x........: __libc_write (...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First byte (0x........) is 3 bytes within a 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (supp.c:12)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Last byte is not within a known block

---- Print suppression ? --- [Return/N/n/Y/y/C/c] ---- {
   <insert a suppression name here>
   Annelid:SysParam
   write(buf)
   fun:__GI___libc_write
   fun:__libc_start_main
   obj:*/annelid/tests/supp
}


ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
