
Warning: invalid file descriptor -1 in syscall write()
Syscall param write(buf) is non-contiguous
   at 0x........: __libc_write (...libc...)
   by 0x........: main (syscall.c:32)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First byte (0x........) is 3 bytes within a 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Last byte is not within a known block
Warning: invalid file descriptor -1 in syscall write()

Syscall param write(buf) is non-contiguous
   at 0x........: __libc_write (...libc...)
   by 0x........: main (syscall.c:33)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First byte is not within a known block
Last byte (0x........) is 3 bytes within a 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Warning: invalid file descriptor -1 in syscall write()

Syscall param write(buf) is non-contiguous
   at 0x........: __libc_write (...libc...)
   by 0x........: main (syscall.c:34)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First byte (0x........) is 1 bytes within a 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Last byte (0x........) is 0 bytes within a 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Syscall param open(pathname) is non-contiguous
   at 0x........: __libc_open (...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First byte (0x........) is 3 bytes within a 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Last byte is not within a known block

Syscall param getitimer(timer) is non-contiguous
   at 0x........: __getitimer (in /...libc...)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First byte (0x........) is 0 bytes within a 15-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:21)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Last byte is not within a known block
Warning: invalid file descriptor -1 in syscall write()

Syscall param write(buf) contains unaddressable byte(s)
   at 0x........: __libc_write (...libc...)
   by 0x........: main (syscall.c:41)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Address 0x........ is 0 bytes within a 6-byte block free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:40)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Warning: invalid file descriptor -1 in syscall write()

Syscall param write(buf) is non-contiguous
   at 0x........: __libc_write (...libc...)
   by 0x........: main (syscall.c:42)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First byte (0x........) is 3 bytes within a 6-byte block free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:40)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Last byte is not within a known block
Warning: invalid file descriptor -1 in syscall write()

Syscall param write(buf) is non-contiguous
   at 0x........: __libc_write (...libc...)
   by 0x........: main (syscall.c:43)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
First byte (0x........) is 1 bytes within a 6-byte block free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:40)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
Last byte (0x........) is 0 bytes within a 6-byte block alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (syscall.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...


ERROR SUMMARY: 8 errors from 8 contexts (suppressed: 0 from 0)
