
Invalid read of size 1
   at 0x........: main (zero.c:10)
 Address 0x........ is 0 bytes after the accessing pointer's
 legitimate range, a block of size 0 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (zero.c:8)

Invalid read of size 1
   at 0x........: main (zero.c:21)
 Address 0x........ is 0 bytes inside the accessing pointer's
 once-legitimate range, a block of size 10 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: realloc (vg_replace_malloc.c:...)
   by 0x........: main (zero.c:18)


ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
