#! /bin/sh

# Skip first four lines (valgrind intro)  
# XXX: be more clever/subtle; eg. if there's just a 1-line error message
# don't cut it

dir=`dirname $0`

$dir/../filter_stderr_basic                             |

# Anonymise addresses
$dir/../filter_addresses                                |

# Anonymise line numbers in vg_clientfuncs.c
sed "s/vg_clientfuncs.c:[0-9]\+/vg_clientfuncs.c:.../"  |

$dir/../filter_test_paths                               |

# Anonymise paths like "(in /foo/bar/libc-baz.so)"
sed "s/(in \/.*libc.*)$/(in \/...libc...)/"             |

# Anonymise paths like "__libc_start_main (../foo/bar/libc-quux.c:129)"
sed "s/__libc_\(.*\) (.*)$/__libc_\1 (...libc...)/"

