
Mismatched free() / delete / delete []
   at 0x........: __builtin_delete (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:6)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)
   Address 0x........ is 0 bytes inside a block of size 10 alloc'd
   at 0x........: malloc (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:5)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)

Mismatched free() / delete / delete []
   at 0x........: __builtin_vec_delete (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:8)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)
   Address 0x........ is 0 bytes inside a block of size 10 alloc'd
   at 0x........: malloc (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:7)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)

Mismatched free() / delete / delete []
   at 0x........: __builtin_delete (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:13)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)
   Address 0x........ is 0 bytes inside a block of size 40 alloc'd
   at 0x........: __builtin_vec_new (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:12)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)

Mismatched free() / delete / delete []
   at 0x........: free (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:15)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)
   Address 0x........ is 0 bytes inside a block of size 40 alloc'd
   at 0x........: __builtin_vec_new (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:14)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)

Mismatched free() / delete / delete []
   at 0x........: __builtin_vec_delete (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)
   Address 0x........ is 0 bytes inside a block of size 4 alloc'd
   at 0x........: __builtin_new (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:19)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)

Mismatched free() / delete / delete []
   at 0x........: free (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)
   Address 0x........ is 0 bytes inside a block of size 4 alloc'd
   at 0x........: __builtin_new (vg_clientfuncs.c:...)
   by 0x........: main (mismatches.cpp:21)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: __builtin_new (in /.../tests/memcheck/mismatches)

ERROR SUMMARY: 6 errors from 6 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 9 allocs, 9 frees, 162 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
