#! /bin/sh

# used to filter memcheck output shown by vgdb.

dir=`dirname $0`

$dir/../memcheck/tests/filter_stderr                   |

# filter vgdb messages
$dir/filter_vgdb                                       |


# Bypass a s390x kernel bug which makes faultstatus test3 fail. In our case, we are
# not interested in checking the si_code, but rather the signal passing
# in mcsig(no)pass
sed -e 's/Test 3:   FAIL: expected si_code==2, not 128/Test 3:   PASS/'
