#! /bin/sh

dir=`dirname $0`

$dir/filter_stderr                              |

# Anonymise addresses
$dir/../tests/filter_addresses                  |

# filter vgdb process id, pid
# gdb 7.2 sometimes tries to access address 0x0
#   (same as with standard gdbserver)
sed -e 's/\(relaying data between gdb and process \)[0-9][0-9]*/\1..../' \
    -e 's/\(sending command .* to pid \)[0-9][0-9]*/\1..../'             \
    -e '/Cannot access memory at address 0x......../d'
