#! /bin/sh

dir=`dirname $0`

$dir/filter_stderr                              |

# Anonymise addresses
$dir/../tests/filter_addresses                  |

# filter vgdb process id,
#             pid
# gdb 7.2 sometimes tries to access address 0x0 (same as with standard gdbserver)
# filter a debian 6.0/ppc32 line
sed -e 's/\(relaying data between gdb and process \)[0-9][0-9]*/\1..../' \
    -e 's/\(sending command .* to pid \)[0-9][0-9]*/\1..../'             \
    -e '/Cannot access memory at address 0x......../d'                   \
    -e '/^[1-9][0-9]*	\.\.\/sysdeps\/powerpc\/powerpc32\/dl-start\.S: No such file or directory\./d'
