Breakpoint 1 at 0x........: file tls.c, line 55.
Continuing.
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test race tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test race tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test local tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test local tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test global tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test global tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test static_extern tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test static_extern tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test so_extern tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test so_extern tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test so_local tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test so_local tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test so_global tls_ip 0x........ ip 0x........ equal 1
Breakpoint 1, tls_ptr (p=0x........) at tls.c:55
55		int here = 0;
test so_global tls_ip 0x........ ip 0x........ equal 1
Program exited normally.
