vgdb-error value changed from 0 to 999999
10 bytes in 1 blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:15)
   by 0x........: main (leak-delta.c:72)
10 (+10) bytes in 1 (+1) blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:15)
   by 0x........: main (leak-delta.c:72)
21 (+21) bytes in 1 (+1) blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:24)
   by 0x........: main (leak-delta.c:72)
65 (+65) bytes in 2 (+2) blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:29)
   by 0x........: main (leak-delta.c:72)
10 (+10) bytes in 1 (+1) blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:15)
   by 0x........: main (leak-delta.c:72)
0 (-10) bytes in 0 (-1) blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:15)
   by 0x........: main (leak-delta.c:72)
10 (+10) bytes in 1 (+1) blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:15)
   by 0x........: main (leak-delta.c:72)
0 (-10) bytes in 0 (-1) blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:15)
   by 0x........: main (leak-delta.c:72)
10 (+10) bytes in 1 (+1) blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:15)
   by 0x........: main (leak-delta.c:72)
32 (+32) bytes in 1 (+1) blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:29)
   by 0x........: main (leak-delta.c:72)
33 (-32) bytes in 1 (-1) blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:29)
   by 0x........: main (leak-delta.c:72)
42 (+42) bytes in 1 (+1) blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:53)
   by 0x........: main (leak-delta.c:72)
43 (+43) bytes in 1 (+1) blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:53)
   by 0x........: main (leak-delta.c:72)
10 bytes in 1 blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:15)
   by 0x........: main (leak-delta.c:72)
21 bytes in 1 blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:24)
   by 0x........: main (leak-delta.c:72)
32 bytes in 1 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:29)
   by 0x........: main (leak-delta.c:72)
33 bytes in 1 blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:29)
   by 0x........: main (leak-delta.c:72)
85 bytes in 2 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:53)
   by 0x........: main (leak-delta.c:72)
33 bytes in 1 blocks are still reachable in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:29)
   by 0x........: main (leak-delta.c:72)
85 bytes in 2 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:53)
   by 0x........: main (leak-delta.c:72)
85 bytes in 2 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:53)
   by 0x........: main (leak-delta.c:72)
85 bytes in 2 blocks are definitely lost in loss record ... of ...
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: f (leak-delta.c:53)
   by 0x........: main (leak-delta.c:72)
