Breakpoint 1 at 0x........: file leak-delta.c, line 10.
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:17
17	   fprintf(stderr, "expecting details 10 bytes reachable\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:20
20	   fprintf(stderr, "expecting to have NO details\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:25
25	   fprintf(stderr, "expecting details +10 bytes lost, +21 bytes reachable\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:30
30	   fprintf(stderr, "expecting details +65 bytes reachable\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:33
33	   fprintf(stderr, "expecting to have NO details\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:37
37	   fprintf(stderr, "expecting details +10 bytes reachable\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:41
41	   fprintf(stderr, "expecting details -10 bytes reachable, +10 bytes lost\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:45
45	   fprintf(stderr, "expecting details -10 bytes lost, +10 bytes reachable\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:49
49	   fprintf(stderr, "expecting details 32 (+32) bytes lost, 33 (-32) bytes reachable\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
#1  0x........ in f () at leak-delta.c:56
56	   fprintf(stderr, "expecting details 42 (+42) bytes lost, 43 (+43) bytes reachable\n"); fflush(stderr); breakme();
Continuing.
Breakpoint 1, breakme () at leak-delta.c:10
10	static void breakme() {};
Continuing.
Program exited normally.
