(action at startup) vgdb me ... 
Test 1: Invalid write of size 4
   at 0x........: test1 (faultstatus.c:117)
   by 0x........: main (faultstatus.c:184)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
  PASS
Test 2:   PASS
Test 3:   PASS
Test 4:   PASS
HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
For a detailed leak analysis, rerun with: --leak-check=full
For lists of detected and suppressed errors, rerun with: -s
ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
