Continuing.
Program received signal SIGSEGV, Segmentation fault.
test1 () at faultstatus.c:116
116		*BADADDR = 'x';
Continuing.
Program received signal SIGSEGV, Segmentation fault.
test2 () at faultstatus.c:121
121		mapping[0] = 'x';
Continuing.
Program received signal SIGBUS, Bus error.
test3 () at faultstatus.c:126
126		mapping[FILESIZE+10];
Continuing.
Program received signal SIGFPE, Arithmetic exception.
