
(action at startup) vgdb me ... 


breakme function called from line 19
before reading 0/4/8
u: Expected value at 0
f: Expected value at 4
d: Expected value at 8
before writing 0
before writing 4
before writing 8
after writing 8
value UndeFineD
before rewriting 0
before rewriting 4
before rewriting 8
value 0nde4ine8
value of k50[1000] p

HEAP SUMMARY:
    in use at exit: 0 bytes in 0 blocks
  total heap usage: 1 allocs, 1 frees, 50,000 bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
