Continuing.
Program received signal SIGTRAP, Trace/breakpoint trap.
0x........ in syscall ...
[New Thread ....]
[New Thread ....]
[New Thread ....]
  4 Thread .... (tid 4 VgTs_WaitSys)  0x........ in syscall ...
  3 Thread .... (tid 3 VgTs_WaitSys)  0x........ in syscall ...
  2 Thread .... (tid 2 VgTs_WaitSys)  0x........ in syscall ...
* 1 Thread .... (tid 1 VgTs_WaitSys)  0x........ in syscall ...
$1 = 0
$2 = 0
$3 = 0
$4 = 0
changed burning parameters
Continuing.
Program received signal SIGTRAP, Trace/breakpoint trap.
0x........ in do_burn () at sleepers.c:39
39	   for (i = 0; i < burn; i++) loopnr++;
$5 = 0
$6 = 0
$7 = 0
Continuing.
Program exited normally.
