Continuing.
Program received signal SIGTRAP, Trace/breakpoint trap.
0x........ in syscall ...
* 1 Thread .... (tid 1 VgTs_WaitSys)  0x........ in syscall ...
$1 = 0
$2 = 0
$3 = 0
$4 = 0
changed burning parameters
Continuing.
Program received signal SIGTRAP, Trace/breakpoint trap.
0x........ in do_burn () at sleepers.c:41
41	   for (i = 0; i < burn; i++) loopnr++;
$5 = 0
$6 = 0
$7 = 0
Continuing.
Program exited normally.
