
/*---------------------------------------------------------------*/
/*---                                                         ---*/
/*--- This file (guest-ppc32/ghelpers.c) is                   ---*/
/*--- Copyright (c) 2004 OpenWorks LLP.  All rights reserved. ---*/
/*---                                                         ---*/
/*---------------------------------------------------------------*/

/*
   This file is part of LibVEX, a library for dynamic binary
   instrumentation and translation.

   Copyright (C) 2004 OpenWorks, LLP.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; Version 2 dated June 1991 of the
   license.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, or liability
   for damages.  See the GNU General Public License for more details.

   Neither the names of the U.S. Department of Energy nor the
   University of California nor the names of its contributors may be
   used to endorse or promote products derived from this software
   without prior written permission.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
   USA.
*/

#include "libvex_basictypes.h"
#include "libvex_guest_ppc32.h"
#include "libvex_ir.h"
#include "libvex.h"

#include "main/vex_util.h"
#include "guest-ppc32/gdefs.h"


/* This file contains helper functions for ppc32 guest code.
   Calls to these functions are generated by the back end.
   These calls are of course in the host machine code and 
   this file will be compiled to host machine code, so that
   all makes sense.  

   Only change the signatures of these helper functions very
   carefully.  If you change the signature here, you'll have to change
   the parameters passed to it in the IR calls constructed by
   guest-ppc32/toIR.c.
*/





/* CALLED FROM GENERATED CODE: CLEAN HELPER */
/* Calculates CR0[LT,GT,EQ,SO] flags from the supplied
   thunk parameters. */
UInt ppc32g_calculate_cr0_all ( UChar op, UInt word1, UInt word2 )
{
    Int sword1 = (Int)word1;
    if (op) {
	return (word1 & 0xF0000000);
    } else {
	return
	    ((word2 & 1) << 3)
	    | (((sword1 == 0) ? 1:0) << 2)
	    | (((sword1 >  0) ? 1:0) << 1)
	    | (((sword1 <  0) ? 1:0) << 0);
    }
}

UInt ppc32g_calculate_cr0_bit0 ( UChar op, UInt word1, UInt word2 )
{
    return (ppc32g_calculate_cr0_all(op,word1,word2) >> 0) & 1;
}

UInt ppc32g_calculate_cr0_bit1 ( UChar op, UInt word1, UInt word2 )
{
    return (ppc32g_calculate_cr0_all(op,word1,word2) >> 1) & 1;
}

UInt ppc32g_calculate_cr0_bit2 ( UChar op, UInt word1, UInt word2 )
{
    return (ppc32g_calculate_cr0_all(op,word1,word2) >> 2) & 1;
}

UInt ppc32g_calculate_cr0_bit3 ( UChar op, UInt word1, UInt word2 )
{
    return (ppc32g_calculate_cr0_all(op,word1,word2) >> 3) & 1;
}






// Calculate XER_OV
UInt ppc32g_calculate_xer_ov ( UInt theInstr, UInt Ra, UInt Rb, UInt Rd, UChar ov )
{
    UChar opc1    = (theInstr >> 26) & 0x3F;    /* opcode1: theInstr[0:5]   */
    UInt  opc2    = (theInstr >> 1) & 0x1FF;    /* opcode2: theInstr[22:30] */

    switch (opc1) {
    case 0x1F:
       switch (opc2) {
       case 0x10A: // addo
	   // i.e. ((both_same_sign) & (sign_changed) & (sign_mask))
	   return ((Ra^Rb^-1) & (Ra^Rd) & (1<<31)) ? 1:0;

       case 0x00A: // addc
	   return ((Ra^Rb^-1) & (Ra^Rd) & (1<<31)) ? 1:0;

       case 0x08A: // addeo
	   return ((Ra^Rb^-1) & (Ra^Rd) & (1<<31)) ? 1:0;

       default:
	   break;
       }

    default:
	break;
    }

    return 0;
}

// Calculate XER_CA
UInt ppc32g_calculate_xer_ca ( UInt theInstr, UInt Ra, UInt Rb, UInt Rd, UChar ca )
{
    UChar opc1    = (theInstr >> 26) & 0x3F;    /* opcode1: theInstr[0:5]   */
    UInt  opc2    = (theInstr >> 1) & 0x1FF;    /* opcode2: theInstr[22:30] */

    switch (opc1) {
    case 0x0D: // addic
    case 0x0E: // addic.
	return (Rd < Ra) ? 1:0;

    case 0x1F:
       switch (opc2) {
       case 0x00A: // addc
	   return (Rd < Ra) ? 1:0;

       case 0x08A: // adde
	   return (Rd < Ra || (ca==1 && Rd==Ra)) ? 1:0;

       default:
	   break;
       }

    default:
	break;
    }

    return 0;
}







/* Used by the optimiser to try specialisations.  Returns an
   equivalent expression, or NULL if none. */

#if 0
/* temporarily unused */
static Bool isU32 ( IRExpr* e, UInt n )
{
   return e->tag == Iex_Const
          && e->Iex.Const.con->tag == Ico_U32
          && e->Iex.Const.con->Ico.U32 == n;
}
#endif
IRExpr* guest_ppc32_spechelper ( Char* function_name,
                               IRExpr** args )
{
   return NULL;
}


/*----------------------------------------------*/
/*--- The exported fns ..                    ---*/
/*----------------------------------------------*/

/* VISIBLE TO LIBVEX CLIENT */
#if 0
void LibVEX_GuestPPC32_put_flags ( UInt flags_native,
                                 /*OUT*/VexGuestPPC32State* vex_state )
{
   vassert(0); // FIXME
}
#endif

/* VISIBLE TO LIBVEX CLIENT */
UInt LibVEX_GuestPPC32_get_flags ( /*IN*/VexGuestPPC32State* vex_state )
{
   UInt flags = ppc32g_calculate_cr0_all(
       vex_state->guest_CC_OP,
       vex_state->guest_CC_DEP1,
       vex_state->guest_CC_DEP2
       );
   return flags;
}

/* VISIBLE TO LIBVEX CLIENT */
void LibVEX_GuestPPC32_initialise ( /*OUT*/VexGuestPPC32State* vex_state )
{
   vex_state->guest_GPR0  = 0;
   vex_state->guest_GPR1  = 0;
   vex_state->guest_GPR2  = 0;
   vex_state->guest_GPR3  = 0;
   vex_state->guest_GPR4  = 0;
   vex_state->guest_GPR5  = 0;
   vex_state->guest_GPR6  = 0;
   vex_state->guest_GPR7  = 0;
   vex_state->guest_GPR8  = 0;
   vex_state->guest_GPR9  = 0;
   vex_state->guest_GPR10 = 0;
   vex_state->guest_GPR11 = 0;
   vex_state->guest_GPR12 = 0;
   vex_state->guest_GPR13 = 0;
   vex_state->guest_GPR14 = 0;
   vex_state->guest_GPR15 = 0;
   vex_state->guest_GPR16 = 0;
   vex_state->guest_GPR17 = 0;
   vex_state->guest_GPR18 = 0;
   vex_state->guest_GPR19 = 0;
   vex_state->guest_GPR20 = 0;
   vex_state->guest_GPR21 = 0;
   vex_state->guest_GPR22 = 0;
   vex_state->guest_GPR23 = 0;
   vex_state->guest_GPR24 = 0;
   vex_state->guest_GPR25 = 0;
   vex_state->guest_GPR26 = 0;
   vex_state->guest_GPR27 = 0;
   vex_state->guest_GPR28 = 0;
   vex_state->guest_GPR29 = 0;
   vex_state->guest_GPR30 = 0;
   vex_state->guest_GPR31 = 0;

   vex_state->guest_CIA  = 0;
   vex_state->guest_LR   = 0;
   vex_state->guest_CTR  = 0;

   vex_state->guest_CC_OP   = 0;
   vex_state->guest_CC_DEP1 = 0;
   vex_state->guest_CC_DEP2 = 0;

   vex_state->guest_CR2_7 = 0;

   vex_state->guest_XER_SO = 0;
   vex_state->guest_XER_OV = 0;
   vex_state->guest_XER_CA = 0;

   vex_state->guest_EMWARN = 0;
}


/*-----------------------------------------------------------*/
/*--- Describing the ppc32 guest state, for the benefit     ---*/
/*--- of iropt and instrumenters.                         ---*/
/*-----------------------------------------------------------*/

/* Figure out if any part of the guest state contained in minoff
   .. maxoff requires precise memory exceptions.  If in doubt return
   True (but this is generates significantly slower code).  
*/
Bool guest_ppc32_state_requires_precise_mem_exns ( Int minoff, 
                                                 Int maxoff)
{
   return True; // FIXME (also comment above)
}



#define ALWAYSDEFD(field)                           \
    { offsetof(VexGuestPPC32State, field),            \
      (sizeof ((VexGuestPPC32State*)0)->field) }

VexGuestLayout
   ppc32Guest_layout 
      = { 
          /* Total size of the guest state, in bytes. */
          .total_sizeB = sizeof(VexGuestPPC32State),

          /* Describe the stack pointer. */
          .offset_SP = offsetof(VexGuestPPC32State,guest_GPR1),
          .sizeof_SP = 4,

          /* Describe the instruction pointer. */
          .offset_IP = offsetof(VexGuestPPC32State,guest_CIA),
          .sizeof_IP = 4,

          /* Describe any sections to be regarded by Memcheck as
             'always-defined'. */
          .n_alwaysDefd = 1,
          /* flags thunk: only using last_result, which is always defd. */

          .alwaysDefd 
             = { /*  0 */ ALWAYSDEFD(guest_CC_OP)
               }
        };


/*---------------------------------------------------------------*/
/*--- end                              guest-ppc32/ghelpers.c ---*/
/*---------------------------------------------------------------*/
