Syscall param (syscallno) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: (below main) (in /...libc...)

Syscall param write(fd) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: (below main) (in /...libc...)

Syscall param write(count) contains uninitialised byte(s)
   at 0x........: syscall (in /...libc...)
   by 0x........: (below main) (in /...libc...)
