--------------------------------------------------------------------------------
Command:            ./alloc-fns
Massif arguments:   --stacks=no --time-unit=B --heap-admin=0 --alloc-fn=a4 --alloc-fn=b4 --alloc-fn=b3 --alloc-fn=c4 --alloc-fn=c3 --alloc-fn=c2 --alloc-fn=d4 --alloc-fn=d3 --alloc-fn=d2 --alloc-fn=d1 --massif-out-file=massif.out --ignore-fn=__part_load_locale --ignore-fn=__time_load_locale --ignore-fn=dwarf2_unwind_dyld_add_image_hook --ignore-fn=get_or_create_key_element --alloc-fn=_xpc_malloc --ignore-fn=_xpc_dictionary_insert --ignore-fn=map_images_nolock --ignore-fn=allocBuckets(void*, unsigned int) --ignore-fn=realizeClass(objc_class*) --ignore-fn=_NXHashRehashToCapacity --ignore-fn=NXCreateHashTableFromZone --ignore-fn=NXCreateMapTableFromZone --ignore-fn=NXHashInsert --ignore-fn=add_class_to_loadable_list --ignore-fn=class_createInstance --ignore-fn=xpc_string_create --alloc-fn=strdup --alloc-fn=_xpc_calloc --ignore-fn=xpc_array_create
ms_print arguments: massif.out
--------------------------------------------------------------------------------


    KB
3.516^                                                                       @
     |                                                                       @
     |                                                                       @
     |                                                                :::::::@
     |                                                                :      @
     |                                                        :::::::::      @
     |                                                        :       :      @
     |                                                :::::::::       :      @
     |                                                :       :       :      @
     |                                        :::::::::       :       :      @
     |                                        :       :       :       :      @
     |                                        :       :       :       :      @
     |                                :::::::::       :       :       :      @
     |                                :       :       :       :       :      @
     |                        :::::::::       :       :       :       :      @
     |                        :       :       :       :       :       :      @
     |                :::::::::       :       :       :       :       :      @
     |                :       :       :       :       :       :       :      @
     |        :::::::::       :       :       :       :       :       :      @
     |        :       :       :       :       :       :       :       :      @
   0 +----------------------------------------------------------------------->KB
     0                                                                   3.516

Number of snapshots: 10
 Detailed snapshots: [9]

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1            400              400              400             0            0
  2            800              800              800             0            0
  3          1,200            1,200            1,200             0            0
  4          1,600            1,600            1,600             0            0
  5          2,000            2,000            2,000             0            0
  6          2,400            2,400            2,400             0            0
  7          2,800            2,800            2,800             0            0
  8          3,200            3,200            3,200             0            0
  9          3,600            3,600            3,600             0            0
100.00% (3,600B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->33.33% (1,200B) 0x........: a3 (alloc-fns.c:4)
| ->33.33% (1,200B) 0x........: a2 (alloc-fns.c:5)
|   ->33.33% (1,200B) 0x........: a1 (alloc-fns.c:6)
|     ->11.11% (400B) 0x........: main (alloc-fns.c:25)
|     | 
|     ->11.11% (400B) 0x........: main (alloc-fns.c:26)
|     | 
|     ->11.11% (400B) 0x........: main (alloc-fns.c:27)
|       
->11.11% (400B) 0x........: b2 (alloc-fns.c:10)
| ->11.11% (400B) 0x........: b1 (alloc-fns.c:11)
|   ->11.11% (400B) 0x........: main (alloc-fns.c:28)
|     
->11.11% (400B) 0x........: c1 (alloc-fns.c:16)
| ->11.11% (400B) 0x........: main (alloc-fns.c:29)
|   
->11.11% (400B) 0x........: main (alloc-fns.c:30)
| 
->11.11% (400B) 0x........: main (alloc-fns.c:31)
| 
->11.11% (400B) 0x........: main (alloc-fns.c:32)
| 
->11.11% (400B) 0x........: main (alloc-fns.c:33)
  
