--------------------------------------------------------------------------------
Command:            ./custom_alloc
Massif arguments:   --stacks=no --time-unit=B --heap-admin=16 --massif-out-file=massif.out --ignore-fn=__part_load_locale --ignore-fn=__time_load_locale --ignore-fn=dwarf2_unwind_dyld_add_image_hook --ignore-fn=get_or_create_key_element --alloc-fn=_xpc_malloc --ignore-fn=_xpc_dictionary_insert --ignore-fn=map_images_nolock --ignore-fn=allocBuckets(void*, unsigned int) --ignore-fn=realizeClass(objc_class*) --ignore-fn=_NXHashRehashToCapacity --ignore-fn=NXCreateHashTableFromZone --ignore-fn=NXCreateMapTableFromZone --ignore-fn=NXHashInsert --ignore-fn=add_class_to_loadable_list --ignore-fn=class_createInstance --ignore-fn=xpc_string_create --alloc-fn=strdup --alloc-fn=_xpc_calloc --ignore-fn=xpc_array_create
ms_print arguments: massif.out
--------------------------------------------------------------------------------


     B
  816^                        ############                        ::::::::::: 
     |                        #                                   :           
     |                        #                                   :           
     |                        #                                   :           
     |                        #                                   :           
     |                        #                                   :           
     |                        #                                   :           
     |                        #                                   :           
     |                        #                                   :           
     |                        #                                   :           
     |      @@@@@@            #                 ::::::            :           
     |      @                 #                 :                 :           
     |      @                 #                 :                 :           
     |      @                 #                 :                 :           
     |      @                 #                 :                 :           
     |      @                 #                 :                 :           
     |      @                 #                 :                 :           
     |      @                 #                 :                 :           
     |      @                 #                 :                 :           
     |      @                 #                 :                 :           
   0 +----------------------------------------------------------------------->KB
     0                                                                   4.812

Number of snapshots: 11
 Detailed snapshots: [2, 5 (peak)]

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1            416              416              400            16            0
  2            416              416              400            16            0
96.15% (400B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->96.15% (400B) 0x........: custom_alloc (custom_alloc.c:41)
  ->96.15% (400B) 0x........: main (custom_alloc.c:60)
    
--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  3            832                0                0             0            0
  4          1,648              816              800            16            0
  5          1,648              816              800            16            0
98.04% (800B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->98.04% (800B) 0x........: custom_alloc (custom_alloc.c:41)
  ->98.04% (800B) 0x........: main (custom_alloc.c:63)
  | 
  ->00.00% (0B) in 1+ places, all below ms_print's threshold (01.00%)
  
--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  6          2,464                0                0             0            0
  7          2,880              416              400            16            0
  8          3,296                0                0             0            0
  9          4,112              816              800            16            0
 10          4,928                0                0             0            0
