Massif: alloc-fns:
Massif:   malloc
Massif:   __builtin_new
Massif:   operator new(unsigned)
Massif:   __builtin_vec_new
Massif:   operator new[](unsigned)
Massif:   calloc
Massif:   aligned_alloc
Massif:   realloc
Massif:   memalign
Massif:   posix_memalign
Massif:   valloc
Massif:   operator new(unsigned, std::nothrow_t const&)
Massif:   operator new[](unsigned, std::nothrow_t const&)
Massif:   operator new(unsigned, std::align_val_t)
Massif:   operator new[](unsigned, std::align_val_t)
Massif:   operator new(unsigned, std::align_val_t, std::nothrow_t const&)
Massif:   operator new[](unsigned, std::align_val_t, std::nothrow_t const&)
Massif:   a3
Massif:   a4
Massif:   a5
Massif:   a6
Massif:   a7
Massif:   a8
Massif:   a9
Massif:   a10
Massif:   a11
Massif:   a12
Massif:   _xpc_malloc
Massif:   strdup
Massif:   _xpc_calloc
Massif: ignore-fns:
Massif:   0: __part_load_locale
Massif:   1: __time_load_locale
Massif:   2: dwarf2_unwind_dyld_add_image_hook
Massif:   3: get_or_create_key_element
Massif:   4: _xpc_dictionary_insert
Massif:   5: map_images_nolock
Massif:   6: allocBuckets(void*, unsigned int)
Massif:   7: realizeClass(objc_class*)
Massif:   8: _NXHashRehashToCapacity
Massif:   9: NXCreateHashTableFromZone
Massif:   10: NXCreateMapTableFromZone
Massif:   11: NXHashInsert
Massif:   12: add_class_to_loadable_list
Massif:   13: class_createInstance
Massif:   14: xpc_string_create
Massif:   15: xpc_array_create
Massif: startup S.  0 (t:0, hp:0, ex:0, st:0)
Massif:   alloc S.  1 (t:408, hp:400, ex:8, st:0)
Massif:   alloc S.  2 (t:816, hp:800, ex:16, st:0)
Massif:   alloc S.  3 (t:1224, hp:1200, ex:24, st:0)
Massif:   alloc S.  4 (t:1632, hp:1600, ex:32, st:0)
Massif:   alloc S.  5 (t:2040, hp:2000, ex:40, st:0)
Massif:   alloc S.  6 (t:2448, hp:2400, ex:48, st:0)
Massif:   alloc S.  7 (t:2856, hp:2800, ex:56, st:0)
Massif:   alloc S.  8 (t:3264, hp:3200, ex:64, st:0)
Massif:   alloc Sd  9 (t:3672, hp:3600, ex:72, st:0)
Massif:   alloc S. 10 (t:4080, hp:4000, ex:80, st:0)
Massif: heap allocs:           10
Massif: heap reallocs:         0
Massif: heap frees:            0
Massif: ignored heap allocs:   ...
Massif: ignored heap frees:    ...
Massif: ignored heap reallocs: ...
Massif: stack allocs:          0
Massif: skipped snapshots:     0
Massif: real snapshots:        11
Massif: detailed snapshots:    1
Massif: peak snapshots:        0
Massif: cullings:              0
