Massif: alloc-fns:
Massif:   0: malloc
Massif:   1: __builtin_new
Massif:   2: operator new(unsigned)
Massif:   3: operator new(unsigned long)
Massif:   4: __builtin_vec_new
Massif:   5: operator new[](unsigned)
Massif:   6: operator new[](unsigned long)
Massif:   7: calloc
Massif:   8: realloc
Massif:   9: memalign
Massif:   10: operator new(unsigned, std::nothrow_t const&)
Massif:   11: operator new[](unsigned, std::nothrow_t const&)
Massif:   12: operator new(unsigned long, std::nothrow_t const&)
Massif:   13: operator new[](unsigned long, std::nothrow_t const&)
Massif:   14: a6
Massif:   15: a7
Massif:   16: a8
Massif:   17: a9
Massif:   18: a10
Massif:   19: a11
Massif:   20: a12
Massif: startup S.  0 (t:0, hp:0, ex:0, st:0)
Massif:   alloc S.  1 (t:208, hp:200, ex:8, st:0)
Massif:   alloc S.  2 (t:416, hp:400, ex:16, st:0)
Massif:   alloc S.  3 (t:624, hp:600, ex:24, st:0)
Massif:   alloc S.  4 (t:832, hp:800, ex:32, st:0)
Massif:   alloc S.  5 (t:1040, hp:1000, ex:40, st:0)
Massif:   alloc S.  6 (t:1248, hp:1200, ex:48, st:0)
Massif:   alloc S.  7 (t:1456, hp:1400, ex:56, st:0)
Massif:   alloc S.  8 (t:1664, hp:1600, ex:64, st:0)
Massif:   alloc Sd  9 (t:1872, hp:1800, ex:72, st:0)
Massif:   alloc S. 10 (t:2080, hp:2000, ex:80, st:0)
Massif: heap allocs:          10
Massif: heap reallocs:        0
Massif: heap frees:           0
Massif: stack allocs:         0
Massif: stack frees:          0
Massif: XPts:                 ...
Massif: top-XPts:             ...
Massif: XPt init expansions:  ...
Massif: XPt later expansions: ...
Massif: SXPt allocs:          ...
Massif: SXPt frees:           ...
Massif: skipped snapshots:    0
Massif: real snapshots:       11
Massif: detailed snapshots:   1
Massif: peak snapshots:       0
Massif: cullings:             0
Massif: XCon redos:           ...
