--------------------------------------------------------------------------------
Command:            ./deep
Massif arguments:   --stacks=no --time-unit=B --alloc-fn=a1 --alloc-fn=a2 --alloc-fn=a3 --alloc-fn=a4 --alloc-fn=a5 --alloc-fn=a6 --alloc-fn=a7 --alloc-fn=a8 --alloc-fn=a9 --alloc-fn=a10 --alloc-fn=a11 --alloc-fn=a12 --alloc-fn=main --depth=20 --massif-out-file=massif.out --ignore-fn=__part_load_locale --ignore-fn=__time_load_locale --ignore-fn=dwarf2_unwind_dyld_add_image_hook --ignore-fn=get_or_create_key_element --alloc-fn=_xpc_malloc --ignore-fn=_xpc_dictionary_insert --ignore-fn=map_images_nolock --ignore-fn=allocBuckets(void*, unsigned int) --ignore-fn=realizeClass(objc_class*) --ignore-fn=_NXHashRehashToCapacity --ignore-fn=NXCreateHashTableFromZone --ignore-fn=NXCreateMapTableFromZone --ignore-fn=NXHashInsert --ignore-fn=add_class_to_loadable_list --ignore-fn=class_createInstance --ignore-fn=xpc_string_create --alloc-fn=strdup --alloc-fn=_xpc_calloc --ignore-fn=xpc_array_create
ms_print arguments: massif.out
--------------------------------------------------------------------------------


    KB
3.984^                                                                       :
     |                                                                       :
     |                                                                @@@@@@@:
     |                                                                @      :
     |                                                         :::::::@      :
     |                                                         :      @      :
     |                                                  ::::::::      @      :
     |                                                  :      :      @      :
     |                                           ::::::::      :      @      :
     |                                           :      :      :      @      :
     |                                    ::::::::      :      :      @      :
     |                                    :      :      :      :      @      :
     |                            :::::::::      :      :      :      @      :
     |                            :       :      :      :      :      @      :
     |                     ::::::::       :      :      :      :      @      :
     |                     :      :       :      :      :      :      @      :
     |              ::::::::      :       :      :      :      :      @      :
     |              :      :      :       :      :      :      :      @      :
     |       ::::::::      :      :       :      :      :      :      @      :
     |       :      :      :      :       :      :      :      :      @      :
   0 +----------------------------------------------------------------------->KB
     0                                                                   3.984

Number of snapshots: 11
 Detailed snapshots: [9]

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1            408              408              400             8            0
  2            816              816              800            16            0
  3          1,224            1,224            1,200            24            0
  4          1,632            1,632            1,600            32            0
  5          2,040            2,040            2,000            40            0
  6          2,448            2,448            2,400            48            0
  7          2,856            2,856            2,800            56            0
  8          3,264            3,264            3,200            64            0
  9          3,672            3,672            3,600            72            0
98.04% (3,600B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->98.04% (3,600B) 0x........: (below main)
  
--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
 10          4,080            4,080            4,000            80            0
