#! /bin/sh

dir=`dirname $0`

$dir/../../tests/filter_stderr_basic                |

# Remove "Massif, ..." line and the following copyright line.
sed "/^Massif, a heap profiler/ , /./ d" |

# Remove AIX-only alloc-fns
perl -n -e 'print if !/^Massif:   (malloc|calloc|realloc|memalign)_common$/' |

# Remove Darwin-only alloc-fns
perl -n -e 'print if !/^Massif:   malloc_zone_(malloc|calloc|realloc|memalign|valloc)$/'


