#! /bin/sh

dir=`dirname $0`

$dir/../../tests/filter_stderr_basic                |

# Remove "Massif, ..." line and the following copyright line.
sed "/^Massif, a space profiler./ , /./ d" |

# Remove numbers from all lines
sed "s/\([a-zA-Z(): ]*\)[ 0-9\.,()+rdw]*\(%\|ms.B\)$/\1/"

