--------------------------------------------------------------------------------
Command:            ./ignored
Massif arguments:   --stacks=no --time-unit=B --heap-admin=0 --massif-out-file=massif.out --ignore-fn=ignore1 --ignore-fn=ignore2 --ignore-fn=__part_load_locale --ignore-fn=__time_load_locale --ignore-fn=dwarf2_unwind_dyld_add_image_hook --ignore-fn=get_or_create_key_element
ms_print arguments: massif.out
--------------------------------------------------------------------------------


     B
  800^                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                                                       #
     |                                    :::::::::::::::::::::::::::::::::::#
     |                                    :                                  #
     |                                    :                                  #
     |                                    :                                  #
     |                                    :                                  #
     |                                    :                                  #
     |                                    :                                  #
     |                                    :                                  #
     |                                    :                                  #
     |                                    :                                  #
   0 +----------------------------------------------------------------------->B
     0                                                                     800

Number of snapshots: 5
 Detailed snapshots: [3 (peak)]

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1            400              400              400             0            0
  2            800              800              800             0            0
  3            800              800              800             0            0
100.00% (800B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->100.00% (800B) 0x........: main (ignored.c:38)
| 
->00.00% (0B) in 1+ places, all below ms_print's threshold (01.00%)

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  4            800              800              400           400            0
