--------------------------------------------------------------------------------
Command:            ./null
Massif arguments:   --stacks=no --time-unit=B --massif-out-file=massif.out --alloc-fn=_xpc_malloc --alloc-fn=strdup --alloc-fn=_xpc_calloc
ms_print arguments: massif.out
--------------------------------------------------------------------------------


     B
    1^                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
   0 +----------------------------------------------------------------------->B
     0                                                                       1

Number of snapshots: 1
 Detailed snapshots: []

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
