--------------------------------------------------------------------------------
Command:            ./one
Massif arguments:   --stacks=no --time-unit=B --heap-admin=0 --massif-out-file=massif.out --alloc-fn=_xpc_malloc --alloc-fn=strdup --alloc-fn=_xpc_calloc
ms_print arguments: massif.out
--------------------------------------------------------------------------------


     B
    8^                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
     |                                                                       :
   0 +----------------------------------------------------------------------->B
     0                                                                       8

Number of snapshots: 2
 Detailed snapshots: []

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1              8                8                1             7            0
