Massif: alloc-fns:
Massif:   malloc
Massif:   __builtin_new
Massif:   operator new(unsigned)
Massif:   __builtin_vec_new
Massif:   operator new[](unsigned)
Massif:   calloc
Massif:   aligned_alloc
Massif:   realloc
Massif:   memalign
Massif:   posix_memalign
Massif:   valloc
Massif:   operator new(unsigned, std::nothrow_t const&)
Massif:   operator new[](unsigned, std::nothrow_t const&)
Massif:   operator new(unsigned, std::align_val_t)
Massif:   operator new[](unsigned, std::align_val_t)
Massif:   operator new(unsigned, std::align_val_t, std::nothrow_t const&)
Massif:   operator new[](unsigned, std::align_val_t, std::nothrow_t const&)
Massif:   _xpc_malloc
Massif:   strdup
Massif:   _xpc_calloc
Massif: ignore-fns:
Massif:   0: __part_load_locale
Massif:   1: __time_load_locale
Massif:   2: dwarf2_unwind_dyld_add_image_hook
Massif:   3: get_or_create_key_element
Massif:   4: _xpc_dictionary_insert
Massif:   5: map_images_nolock
Massif:   6: allocBuckets(void*, unsigned int)
Massif:   7: realizeClass(objc_class*)
Massif:   8: _NXHashRehashToCapacity
Massif:   9: NXCreateHashTableFromZone
Massif:   10: NXCreateMapTableFromZone
Massif:   11: NXHashInsert
Massif:   12: add_class_to_loadable_list
Massif:   13: class_createInstance
Massif:   14: xpc_string_create
Massif:   15: xpc_array_create
Massif: startup S.  0 (t:0, hp:0, ex:0, st:0)
Massif:   alloc S.  1 (t:1728, hp:1600, ex:128, st:0)
Massif:   alloc S.  2 (t:1872, hp:1616, ex:256, st:0)
Massif: de-PEAK Sp  3 (t:1872, hp:1616, ex:256, st:0)
Massif: dealloc S.  4 (t:2016, hp:1600, ex:128, st:0)
Massif:   alloc S.  5 (t:3744, hp:3200, ex:256, st:0)
Massif:   alloc S.  6 (t:3888, hp:3216, ex:384, st:0)
Massif: de-PEAK Sp  7 (t:3888, hp:3216, ex:384, st:0)
Massif: dealloc S.  8 (t:4032, hp:3200, ex:256, st:0)
Massif:   alloc S.  9 (t:5760, hp:4800, ex:384, st:0)
Massif:   alloc S. 10 (t:5904, hp:4816, ex:512, st:0)
Massif: de-PEAK Sp 11 (t:5904, hp:4816, ex:512, st:0)
Massif: dealloc S. 12 (t:6048, hp:4800, ex:384, st:0)
Massif:   alloc S. 13 (t:7776, hp:6400, ex:512, st:0)
Massif:   alloc S. 14 (t:7920, hp:6416, ex:640, st:0)
Massif: de-PEAK Sp 15 (t:7920, hp:6416, ex:640, st:0)
Massif: dealloc S. 16 (t:8064, hp:6400, ex:512, st:0)
Massif:   alloc S. 17 (t:9792, hp:8000, ex:640, st:0)
Massif:   alloc S. 18 (t:9936, hp:8016, ex:768, st:0)
Massif: de-PEAK Sp 19 (t:9936, hp:8016, ex:768, st:0)
Massif: dealloc S. 20 (t:10080, hp:8000, ex:640, st:0)
Massif:   alloc S. 21 (t:11808, hp:9600, ex:768, st:0)
Massif:   alloc S. 22 (t:11952, hp:9616, ex:896, st:0)
Massif: de-PEAK Sp 23 (t:11952, hp:9616, ex:896, st:0)
Massif: dealloc S. 24 (t:12096, hp:9600, ex:768, st:0)
Massif:   alloc S. 25 (t:13824, hp:11200, ex:896, st:0)
Massif:   alloc S. 26 (t:13968, hp:11216, ex:1024, st:0)
Massif: de-PEAK Sp 27 (t:13968, hp:11216, ex:1024, st:0)
Massif: dealloc S. 28 (t:14112, hp:11200, ex:896, st:0)
Massif:   alloc S. 29 (t:15840, hp:12800, ex:1024, st:0)
Massif:   alloc S. 30 (t:15984, hp:12816, ex:1152, st:0)
Massif: de-PEAK Sp 31 (t:15984, hp:12816, ex:1152, st:0)
Massif: dealloc S. 32 (t:16128, hp:12800, ex:1024, st:0)
Massif:   alloc S. 33 (t:17856, hp:14400, ex:1152, st:0)
Massif:   alloc S. 34 (t:18000, hp:14416, ex:1280, st:0)
Massif: de-PEAK Sp 35 (t:18000, hp:14416, ex:1280, st:0)
Massif: dealloc S. 36 (t:18144, hp:14400, ex:1152, st:0)
Massif:   alloc S. 37 (t:19872, hp:16000, ex:1280, st:0)
Massif:   alloc S. 38 (t:20016, hp:16016, ex:1408, st:0)
Massif: de-PEAK Sp 39 (t:20016, hp:16016, ex:1408, st:0)
Massif: dealloc S. 40 (t:20160, hp:16000, ex:1280, st:0)
Massif:   alloc S. 41 (t:21888, hp:17600, ex:1408, st:0)
Massif:   alloc S. 42 (t:22032, hp:17616, ex:1536, st:0)
Massif: dealloc S. 43 (t:22176, hp:17600, ex:1408, st:0)
Massif:   alloc S. 44 (t:23904, hp:19200, ex:1536, st:0)
Massif:   alloc S. 45 (t:24048, hp:19216, ex:1664, st:0)
Massif: de-PEAK Sp 46 (t:24048, hp:19216, ex:1664, st:0)
Massif: dealloc S. 47 (t:24192, hp:19200, ex:1536, st:0)
Massif:   alloc S. 48 (t:25920, hp:20800, ex:1664, st:0)
Massif:   alloc S. 49 (t:26064, hp:20816, ex:1792, st:0)
Massif: dealloc S. 50 (t:26208, hp:20800, ex:1664, st:0)
Massif:   alloc S. 51 (t:27936, hp:22400, ex:1792, st:0)
Massif:   alloc S. 52 (t:28080, hp:22416, ex:1920, st:0)
Massif: de-PEAK Sp 53 (t:28080, hp:22416, ex:1920, st:0)
Massif: dealloc S. 54 (t:28224, hp:22400, ex:1792, st:0)
Massif:   alloc S. 55 (t:29952, hp:24000, ex:1920, st:0)
Massif:   alloc S. 56 (t:30096, hp:24016, ex:2048, st:0)
Massif: dealloc S. 57 (t:30240, hp:24000, ex:1920, st:0)
Massif:   alloc S. 58 (t:31968, hp:25600, ex:2048, st:0)
Massif:   alloc S. 59 (t:32112, hp:25616, ex:2176, st:0)
Massif: de-PEAK Sp 60 (t:32112, hp:25616, ex:2176, st:0)
Massif: dealloc S. 61 (t:32256, hp:25600, ex:2048, st:0)
Massif:   alloc S. 62 (t:33984, hp:27200, ex:2176, st:0)
Massif:   alloc S. 63 (t:34128, hp:27216, ex:2304, st:0)
Massif: dealloc S. 64 (t:34272, hp:27200, ex:2176, st:0)
Massif:   alloc S. 65 (t:36000, hp:28800, ex:2304, st:0)
Massif:   alloc S. 66 (t:36144, hp:28816, ex:2432, st:0)
Massif: de-PEAK Sp 67 (t:36144, hp:28816, ex:2432, st:0)
Massif: dealloc S. 68 (t:36288, hp:28800, ex:2304, st:0)
Massif:   alloc S. 69 (t:38016, hp:30400, ex:2432, st:0)
Massif:   alloc S. 70 (t:38160, hp:30416, ex:2560, st:0)
Massif: dealloc S. 71 (t:38304, hp:30400, ex:2432, st:0)
Massif:   alloc S. 72 (t:40032, hp:32000, ex:2560, st:0)
Massif:   alloc S. 73 (t:40176, hp:32016, ex:2688, st:0)
Massif: de-PEAK Sp 74 (t:40176, hp:32016, ex:2688, st:0)
Massif: dealloc S. 75 (t:40320, hp:32000, ex:2560, st:0)
Massif: heap allocs:           40
Massif: heap reallocs:         0
Massif: heap frees:            20
Massif: ignored heap allocs:   ...
Massif: ignored heap frees:    ...
Massif: ignored heap reallocs: ...
Massif: stack allocs:          0
Massif: skipped snapshots:     0
Massif: real snapshots:        76
Massif: detailed snapshots:    15
Massif: peak snapshots:        15
Massif: cullings:              0
