Massif: alloc-fns:
Massif:   0: malloc
Massif:   1: __builtin_new
Massif:   2: operator new(unsigned)
Massif:   3: operator new(unsigned long)
Massif:   4: __builtin_vec_new
Massif:   5: operator new[](unsigned)
Massif:   6: operator new[](unsigned long)
Massif:   7: calloc
Massif:   8: realloc
Massif:   9: memalign
Massif:   10: operator new(unsigned, std::nothrow_t const&)
Massif:   11: operator new[](unsigned, std::nothrow_t const&)
Massif:   12: operator new(unsigned long, std::nothrow_t const&)
Massif:   13: operator new[](unsigned long, std::nothrow_t const&)
Massif: startup S.  0 (t:0, hp:0, ad:0, st:0)
Massif:   alloc S.  1 (t:108, hp:100, ad:8, st:0)
Massif:   alloc S.  2 (t:117, hp:101, ad:16, st:0)
Massif: de-PEAK Sp  3 (t:117, hp:101, ad:16, st:0)
Massif: dealloc S.  4 (t:126, hp:100, ad:8, st:0)
Massif:   alloc S.  5 (t:234, hp:200, ad:16, st:0)
Massif:   alloc S.  6 (t:243, hp:201, ad:24, st:0)
Massif: de-PEAK Sp  7 (t:243, hp:201, ad:24, st:0)
Massif: dealloc S.  8 (t:252, hp:200, ad:16, st:0)
Massif:   alloc S.  9 (t:360, hp:300, ad:24, st:0)
Massif:   alloc S. 10 (t:369, hp:301, ad:32, st:0)
Massif: de-PEAK Sp 11 (t:369, hp:301, ad:32, st:0)
Massif: dealloc S. 12 (t:378, hp:300, ad:24, st:0)
Massif:   alloc S. 13 (t:486, hp:400, ad:32, st:0)
Massif:   alloc S. 14 (t:495, hp:401, ad:40, st:0)
Massif: de-PEAK Sp 15 (t:495, hp:401, ad:40, st:0)
Massif: dealloc S. 16 (t:504, hp:400, ad:32, st:0)
Massif:   alloc S. 17 (t:612, hp:500, ad:40, st:0)
Massif:   alloc S. 18 (t:621, hp:501, ad:48, st:0)
Massif: de-PEAK Sp 19 (t:621, hp:501, ad:48, st:0)
Massif: dealloc S. 20 (t:630, hp:500, ad:40, st:0)
Massif:   alloc S. 21 (t:738, hp:600, ad:48, st:0)
Massif:   alloc S. 22 (t:747, hp:601, ad:56, st:0)
Massif: de-PEAK Sp 23 (t:747, hp:601, ad:56, st:0)
Massif: dealloc S. 24 (t:756, hp:600, ad:48, st:0)
Massif:   alloc S. 25 (t:864, hp:700, ad:56, st:0)
Massif:   alloc S. 26 (t:873, hp:701, ad:64, st:0)
Massif: de-PEAK Sp 27 (t:873, hp:701, ad:64, st:0)
Massif: dealloc S. 28 (t:882, hp:700, ad:56, st:0)
Massif:   alloc S. 29 (t:990, hp:800, ad:64, st:0)
Massif:   alloc S. 30 (t:999, hp:801, ad:72, st:0)
Massif: de-PEAK Sp 31 (t:999, hp:801, ad:72, st:0)
Massif: dealloc S. 32 (t:1008, hp:800, ad:64, st:0)
Massif:   alloc S. 33 (t:1116, hp:900, ad:72, st:0)
Massif:   alloc S. 34 (t:1125, hp:901, ad:80, st:0)
Massif: de-PEAK Sp 35 (t:1125, hp:901, ad:80, st:0)
Massif: dealloc S. 36 (t:1134, hp:900, ad:72, st:0)
Massif:   alloc S. 37 (t:1242, hp:1000, ad:80, st:0)
Massif:   alloc S. 38 (t:1251, hp:1001, ad:88, st:0)
Massif: de-PEAK Sp 39 (t:1251, hp:1001, ad:88, st:0)
Massif: dealloc S. 40 (t:1260, hp:1000, ad:80, st:0)
Massif:   alloc S. 41 (t:1368, hp:1100, ad:88, st:0)
Massif:   alloc S. 42 (t:1377, hp:1101, ad:96, st:0)
Massif: dealloc S. 43 (t:1386, hp:1100, ad:88, st:0)
Massif:   alloc S. 44 (t:1494, hp:1200, ad:96, st:0)
Massif:   alloc S. 45 (t:1503, hp:1201, ad:104, st:0)
Massif: de-PEAK Sp 46 (t:1503, hp:1201, ad:104, st:0)
Massif: dealloc S. 47 (t:1512, hp:1200, ad:96, st:0)
Massif:   alloc S. 48 (t:1620, hp:1300, ad:104, st:0)
Massif:   alloc S. 49 (t:1629, hp:1301, ad:112, st:0)
Massif: dealloc S. 50 (t:1638, hp:1300, ad:104, st:0)
Massif:   alloc S. 51 (t:1746, hp:1400, ad:112, st:0)
Massif:   alloc S. 52 (t:1755, hp:1401, ad:120, st:0)
Massif: de-PEAK Sp 53 (t:1755, hp:1401, ad:120, st:0)
Massif: dealloc S. 54 (t:1764, hp:1400, ad:112, st:0)
Massif:   alloc S. 55 (t:1872, hp:1500, ad:120, st:0)
Massif:   alloc S. 56 (t:1881, hp:1501, ad:128, st:0)
Massif: dealloc S. 57 (t:1890, hp:1500, ad:120, st:0)
Massif:   alloc S. 58 (t:1998, hp:1600, ad:128, st:0)
Massif:   alloc S. 59 (t:2007, hp:1601, ad:136, st:0)
Massif: de-PEAK Sp 60 (t:2007, hp:1601, ad:136, st:0)
Massif: dealloc S. 61 (t:2016, hp:1600, ad:128, st:0)
Massif:   alloc S. 62 (t:2124, hp:1700, ad:136, st:0)
Massif:   alloc S. 63 (t:2133, hp:1701, ad:144, st:0)
Massif: dealloc S. 64 (t:2142, hp:1700, ad:136, st:0)
Massif:   alloc S. 65 (t:2250, hp:1800, ad:144, st:0)
Massif:   alloc S. 66 (t:2259, hp:1801, ad:152, st:0)
Massif: de-PEAK Sp 67 (t:2259, hp:1801, ad:152, st:0)
Massif: dealloc S. 68 (t:2268, hp:1800, ad:144, st:0)
Massif:   alloc S. 69 (t:2376, hp:1900, ad:152, st:0)
Massif:   alloc S. 70 (t:2385, hp:1901, ad:160, st:0)
Massif: dealloc S. 71 (t:2394, hp:1900, ad:152, st:0)
Massif:   alloc S. 72 (t:2502, hp:2000, ad:160, st:0)
Massif:   alloc S. 73 (t:2511, hp:2001, ad:168, st:0)
Massif: de-PEAK Sp 74 (t:2511, hp:2001, ad:168, st:0)
Massif: dealloc S. 75 (t:2520, hp:2000, ad:160, st:0)
Massif: heap allocs:          40
Massif: heap reallocs:        0
Massif: heap frees:           20
Massif: stack allocs:         0
Massif: stack frees:          0
Massif: XPts:                 7
Massif: top-XPts:             2 (28%)
Massif: XPt-init-expansions:  5
Massif: XPt-later-expansions: 0
Massif: SXPt allocs:          77
Massif: SXPt frees:           0
Massif: skipped snapshots:    0
Massif: real snapshots:       76
Massif: detailed snapshots:   15
Massif: peak snapshots:       15
Massif: cullings:             0
Massif: XCon_redos:           0
