Massif: alloc-fns:
Massif:   0: malloc
Massif:   1: __builtin_new
Massif:   2: operator new(unsigned)
Massif:   3: operator new(unsigned long)
Massif:   4: __builtin_vec_new
Massif:   5: operator new[](unsigned)
Massif:   6: operator new[](unsigned long)
Massif:   7: calloc
Massif:   8: realloc
Massif:   9: memalign
Massif:   10: operator new(unsigned, std::nothrow_t const&)
Massif:   11: operator new[](unsigned, std::nothrow_t const&)
Massif:   12: operator new(unsigned long, std::nothrow_t const&)
Massif:   13: operator new[](unsigned long, std::nothrow_t const&)
Massif: startup S.  0 (t:0, hp:0, ex:0, st:0)
Massif:   alloc S.  1 (t:864, hp:800, ex:64, st:0)
Massif:   alloc S.  2 (t:936, hp:808, ex:128, st:0)
Massif: de-PEAK Sp  3 (t:936, hp:808, ex:128, st:0)
Massif: dealloc S.  4 (t:1008, hp:800, ex:64, st:0)
Massif:   alloc S.  5 (t:1872, hp:1600, ex:128, st:0)
Massif:   alloc S.  6 (t:1944, hp:1608, ex:192, st:0)
Massif: de-PEAK Sp  7 (t:1944, hp:1608, ex:192, st:0)
Massif: dealloc S.  8 (t:2016, hp:1600, ex:128, st:0)
Massif:   alloc S.  9 (t:2880, hp:2400, ex:192, st:0)
Massif:   alloc S. 10 (t:2952, hp:2408, ex:256, st:0)
Massif: de-PEAK Sp 11 (t:2952, hp:2408, ex:256, st:0)
Massif: dealloc S. 12 (t:3024, hp:2400, ex:192, st:0)
Massif:   alloc S. 13 (t:3888, hp:3200, ex:256, st:0)
Massif:   alloc S. 14 (t:3960, hp:3208, ex:320, st:0)
Massif: de-PEAK Sp 15 (t:3960, hp:3208, ex:320, st:0)
Massif: dealloc S. 16 (t:4032, hp:3200, ex:256, st:0)
Massif:   alloc S. 17 (t:4896, hp:4000, ex:320, st:0)
Massif:   alloc S. 18 (t:4968, hp:4008, ex:384, st:0)
Massif: de-PEAK Sp 19 (t:4968, hp:4008, ex:384, st:0)
Massif: dealloc S. 20 (t:5040, hp:4000, ex:320, st:0)
Massif:   alloc S. 21 (t:5904, hp:4800, ex:384, st:0)
Massif:   alloc S. 22 (t:5976, hp:4808, ex:448, st:0)
Massif: de-PEAK Sp 23 (t:5976, hp:4808, ex:448, st:0)
Massif: dealloc S. 24 (t:6048, hp:4800, ex:384, st:0)
Massif:   alloc S. 25 (t:6912, hp:5600, ex:448, st:0)
Massif:   alloc S. 26 (t:6984, hp:5608, ex:512, st:0)
Massif: de-PEAK Sp 27 (t:6984, hp:5608, ex:512, st:0)
Massif: dealloc S. 28 (t:7056, hp:5600, ex:448, st:0)
Massif:   alloc S. 29 (t:7920, hp:6400, ex:512, st:0)
Massif:   alloc S. 30 (t:7992, hp:6408, ex:576, st:0)
Massif: de-PEAK Sp 31 (t:7992, hp:6408, ex:576, st:0)
Massif: dealloc S. 32 (t:8064, hp:6400, ex:512, st:0)
Massif:   alloc S. 33 (t:8928, hp:7200, ex:576, st:0)
Massif:   alloc S. 34 (t:9000, hp:7208, ex:640, st:0)
Massif: de-PEAK Sp 35 (t:9000, hp:7208, ex:640, st:0)
Massif: dealloc S. 36 (t:9072, hp:7200, ex:576, st:0)
Massif:   alloc S. 37 (t:9936, hp:8000, ex:640, st:0)
Massif:   alloc S. 38 (t:10008, hp:8008, ex:704, st:0)
Massif: de-PEAK Sp 39 (t:10008, hp:8008, ex:704, st:0)
Massif: dealloc S. 40 (t:10080, hp:8000, ex:640, st:0)
Massif:   alloc S. 41 (t:10944, hp:8800, ex:704, st:0)
Massif:   alloc S. 42 (t:11016, hp:8808, ex:768, st:0)
Massif: dealloc S. 43 (t:11088, hp:8800, ex:704, st:0)
Massif:   alloc S. 44 (t:11952, hp:9600, ex:768, st:0)
Massif:   alloc S. 45 (t:12024, hp:9608, ex:832, st:0)
Massif: de-PEAK Sp 46 (t:12024, hp:9608, ex:832, st:0)
Massif: dealloc S. 47 (t:12096, hp:9600, ex:768, st:0)
Massif:   alloc S. 48 (t:12960, hp:10400, ex:832, st:0)
Massif:   alloc S. 49 (t:13032, hp:10408, ex:896, st:0)
Massif: dealloc S. 50 (t:13104, hp:10400, ex:832, st:0)
Massif:   alloc S. 51 (t:13968, hp:11200, ex:896, st:0)
Massif:   alloc S. 52 (t:14040, hp:11208, ex:960, st:0)
Massif: de-PEAK Sp 53 (t:14040, hp:11208, ex:960, st:0)
Massif: dealloc S. 54 (t:14112, hp:11200, ex:896, st:0)
Massif:   alloc S. 55 (t:14976, hp:12000, ex:960, st:0)
Massif:   alloc S. 56 (t:15048, hp:12008, ex:1024, st:0)
Massif: dealloc S. 57 (t:15120, hp:12000, ex:960, st:0)
Massif:   alloc S. 58 (t:15984, hp:12800, ex:1024, st:0)
Massif:   alloc S. 59 (t:16056, hp:12808, ex:1088, st:0)
Massif: de-PEAK Sp 60 (t:16056, hp:12808, ex:1088, st:0)
Massif: dealloc S. 61 (t:16128, hp:12800, ex:1024, st:0)
Massif:   alloc S. 62 (t:16992, hp:13600, ex:1088, st:0)
Massif:   alloc S. 63 (t:17064, hp:13608, ex:1152, st:0)
Massif: dealloc S. 64 (t:17136, hp:13600, ex:1088, st:0)
Massif:   alloc S. 65 (t:18000, hp:14400, ex:1152, st:0)
Massif:   alloc S. 66 (t:18072, hp:14408, ex:1216, st:0)
Massif: de-PEAK Sp 67 (t:18072, hp:14408, ex:1216, st:0)
Massif: dealloc S. 68 (t:18144, hp:14400, ex:1152, st:0)
Massif:   alloc S. 69 (t:19008, hp:15200, ex:1216, st:0)
Massif:   alloc S. 70 (t:19080, hp:15208, ex:1280, st:0)
Massif: dealloc S. 71 (t:19152, hp:15200, ex:1216, st:0)
Massif:   alloc S. 72 (t:20016, hp:16000, ex:1280, st:0)
Massif:   alloc S. 73 (t:20088, hp:16008, ex:1344, st:0)
Massif: de-PEAK Sp 74 (t:20088, hp:16008, ex:1344, st:0)
Massif: dealloc S. 75 (t:20160, hp:16000, ex:1280, st:0)
Massif: heap allocs:          40
Massif: heap reallocs:        0
Massif: heap frees:           20
Massif: stack allocs:         0
Massif: stack frees:          0
Massif: XPts:                 ...
Massif: top-XPts:             ...
Massif: XPt init expansions:  5
Massif: XPt later expansions: 0
Massif: SXPt allocs:          ...
Massif: SXPt frees:           ...
Massif: skipped snapshots:    0
Massif: real snapshots:       76
Massif: detailed snapshots:   15
Massif: peak snapshots:       15
Massif: cullings:             0
Massif: XCon redos:           ...
