Massif: alloc-fns:
Massif:   malloc
Massif:   __builtin_new
Massif:   operator new(unsigned)
Massif:   __builtin_vec_new
Massif:   operator new[](unsigned)
Massif:   calloc
Massif:   aligned_alloc
Massif:   realloc
Massif:   memalign
Massif:   posix_memalign
Massif:   valloc
Massif:   operator new(unsigned, std::nothrow_t const&)
Massif:   operator new[](unsigned, std::nothrow_t const&)
Massif:   operator new(unsigned, std::align_val_t)
Massif:   operator new[](unsigned, std::align_val_t)
Massif:   operator new(unsigned, std::align_val_t, std::nothrow_t const&)
Massif:   operator new[](unsigned, std::align_val_t, std::nothrow_t const&)
Massif:   _xpc_malloc
Massif:   strdup
Massif:   _xpc_calloc
Massif:   _xpc_alloc_typed
Massif:   _xpc_strdup
Massif:   _xpc_alloc
Massif:   _malloc_zone_malloc_with_options_np_outlined
Massif: ignore-fns:
Massif:   0: __part_load_locale
Massif:   1: __time_load_locale
Massif:   2: dwarf2_unwind_dyld_add_image_hook
Massif:   3: get_or_create_key_element
Massif:   4: _xpc_dictionary_insert
Massif:   5: map_images_nolock
Massif:   6: allocBuckets(void*, unsigned int)
Massif:   7: realizeClass(objc_class*)
Massif:   8: _NXHashRehashToCapacity
Massif:   9: NXCreateHashTableFromZone
Massif:   10: NXCreateMapTableFromZone
Massif:   11: NXHashInsert
Massif:   12: add_class_to_loadable_list
Massif:   13: class_createInstance
Massif:   14: xpc_string_create
Massif:   15: xpc_array_create
Massif:   16: realizeClassWithoutSwift(objc_class*, objc_class*)
Massif:   17: allocBuckets(unsigned int)
Massif:   18: _xpc_array_create
Massif:   19: NXCreateMapTable
Massif:   20: NXCreateHashTable
Massif:   21: id2data(objc_object*, SyncKind, usage)
Massif:   22: class_rw_t::extAlloc(class_ro_t const*, bool)
Massif:   23: _fetchInitializingClassList(bool)
Massif:   24: objc::SafeRanges::add(unsigned long, unsigned long)
Massif:   25: cache_t::insert(objc_selector*, void (*)(), objc_object*)
Massif:   26: _vasprintf
Massif:   27: xpc_bundle_create_from_origin
Massif:   28: _xpc_realpath
Massif:   29: _xpc_realpath_fd
Massif:   30: _xpc_bundle_resolve_executable_variant
Massif:   31: _xpc_bundle_copy_container
Massif:   32: objc::DenseMap<objc_class*, objc::category_list, objc::DenseMapValueInfo<objc::category_list>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, objc::category_list> >::init(unsigned int)
Massif:   33: objc::DenseMap<DisguisedPtr<objc_class>, objc::category_list, objc::DenseMapValueInfo<objc::category_list>, objc::DenseMapInfo<DisguisedPtr<objc_class> >, objc::detail::DenseMapPair<DisguisedPtr<objc_class>, objc::category_list> >::init(unsigned int)
Massif: startup S.  0 (t:0, hp:0, ex:0, st:0)
Massif:   alloc S.  1 (t:800, hp:800, ex:0, st:0)
Massif: realloc S.  2 (t:800, hp:800, ex:0, st:0)
Massif: re-PEAK Sp  3 (t:800, hp:800, ex:0, st:0)
Massif: realloc S.  4 (t:800, hp:400, ex:400, st:0)
Massif: realloc S.  5 (t:1200, hp:1200, ex:0, st:0)
Massif: de-PEAK Sp  6 (t:1200, hp:1200, ex:0, st:0)
Massif: dealloc S.  7 (t:2400, hp:0, ex:0, st:0)
Massif: heap allocs:           1
Massif: heap reallocs:         3
Massif: heap frees:            1
Massif: ignored heap allocs:   ...
Massif: ignored heap frees:    ...
Massif: ignored heap reallocs: ...
Massif: stack allocs:          0
Massif: skipped snapshots:     0
Massif: real snapshots:        8
Massif: detailed snapshots:    2
Massif: peak snapshots:        2
Massif: cullings:              0
