--------------------------------------------------------------------------------
Command:            ./realloc
Massif arguments:   --stacks=no --heap-admin=0 --time-unit=B --threshold=0 --massif-out-file=massif.out --ignore-fn=__part_load_locale --ignore-fn=__time_load_locale --ignore-fn=dwarf2_unwind_dyld_add_image_hook --ignore-fn=get_or_create_key_element
ms_print arguments: --threshold=0 massif.out
--------------------------------------------------------------------------------


    KB
1.172^                                    ################################### 
     |                                    #                                   
     |                                    #                                   
     |                                    #                                   
     |                                    #                                   
     |                                    #                                   
     |                                    #                                   
     |                        @:::::::::::#                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
     |                        @           #                                   
   0 +----------------------------------------------------------------------->KB
     0                                                                   2.344

Number of snapshots: 8
 Detailed snapshots: [3, 6 (peak)]

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1            800              800              800             0            0
  2            800              800              800             0            0
  3            800              800              800             0            0
100.00% (800B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->100.00% (800B) 0x........: main (realloc.c:8)
| 
->00.00% (0B) 0x........: main (realloc.c:5)
  
--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  4            800              800              400           400            0
  5          1,200            1,200            1,200             0            0
  6          1,200            1,200            1,200             0            0
100.00% (1,200B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->100.00% (1,200B) 0x........: main (realloc.c:12)
| 
->00.00% (0B) 0x........: main (realloc.c:5)
| 
->00.00% (0B) 0x........: main (realloc.c:8)
| 
->00.00% (0B) 0x........: main (realloc.c:10)
  
--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  7          2,400                0                0             0            0
