--------------------------------------------------------------------------------
Command:            ./thresholds
Massif arguments:   --stacks=no --time-unit=B --heap-admin=0 --threshold=5 --massif-out-file=massif.out --ignore-fn=__part_load_locale --ignore-fn=__time_load_locale --ignore-fn=dwarf2_unwind_dyld_add_image_hook --ignore-fn=get_or_create_key_element
ms_print arguments: massif.out --threshold=10
--------------------------------------------------------------------------------


    KB
78.12^                                                                       @
     |                                                                       @
     |                                                                       @
     |                                                                       @
     |                                                                       @
     |                                                         ::::::::::::::@
     |                                                   :::::::             @
     |                                                 :::::   :             @
     |                                           ::::::: :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
     |                                           :     : :::   :             @
   0 +----------------------------------------------------------------------->KB
     0                                                                   78.12

Number of snapshots: 10
 Detailed snapshots: [9]

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1         48,000           48,000           48,000             0            0
  2         55,200           55,200           55,200             0            0
  3         57,600           57,600           57,600             0            0
  4         58,400           58,400           58,400             0            0
  5         59,200           59,200           59,200             0            0
  6         59,600           59,600           59,600             0            0
  7         63,600           63,600           63,600             0            0
  8         79,600           79,600           79,600             0            0
  9         80,000           80,000           80,000             0            0
100.00% (80,000B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->66.50% (53,200B) 0x........: my_malloc1 (thresholds.c:23)
| ->60.00% (48,000B) 0x........: a7550 (thresholds.c:38)
| | ->60.00% (48,000B) 0x........: main (thresholds.c:52)
| |   
| ->06.50% (5,200B) in 2+ places, all below ms_print's threshold (10.00%)
| 
->20.00% (16,000B) 0x........: main (thresholds.c:55)
| 
->13.00% (10,400B) 0x........: my_malloc2 (thresholds.c:28)
| ->13.00% (10,400B) in 2+ places, all below ms_print's threshold (10.00%)
| 
->00.50% (400B) in 1+ places, all below ms_print's threshold (10.00%)

