--------------------------------------------------------------------------------
Command:            ./zero
Massif arguments:   --stacks=no --heap-admin=0 --time-unit=B --massif-out-file=massif.out --ignore-fn=__part_load_locale --ignore-fn=__time_load_locale --ignore-fn=dwarf2_unwind_dyld_add_image_hook --ignore-fn=get_or_create_key_element
ms_print arguments: massif.out
--------------------------------------------------------------------------------


     B
    1^                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
     |                                                                        
   0 +----------------------------------------------------------------------->B
     0                                                                       1

Number of snapshots: 21
 Detailed snapshots: [9, 19]

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1              0                0                0             0            0
  2              0                0                0             0            0
  3              0                0                0             0            0
  4              0                0                0             0            0
  5              0                0                0             0            0
  6              0                0                0             0            0
  7              0                0                0             0            0
  8              0                0                0             0            0
  9              0                0                0             0            0
00.00% (0B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->00.00% (0B) in 1+ places, all below ms_print's threshold (01.00%)

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
 10              0                0                0             0            0
 11              0                0                0             0            0
 12              0                0                0             0            0
 13              0                0                0             0            0
 14              0                0                0             0            0
 15              0                0                0             0            0
 16              0                0                0             0            0
 17              0                0                0             0            0
 18              0                0                0             0            0
 19              0                0                0             0            0
00.00% (0B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->00.00% (0B) in 1+ places, all below ms_print's threshold (01.00%)

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
 20              0                0                0             0            0
