
Thread 2:
Conflicting store by thread 2 at 0x........ size 4
   at 0x........: threadfunc (pth_barrier.c:?)
   by 0x........: vg_thread_wrapper (drd_intercepts.c:?)
   by 0x........: start_thread (in libpthread-?.?.so)
   by 0x........: clone (in /...libc...)
Allocation context: unknown
Other segment start (thread 3)
   at 0x........: pthread_barrier_wait (drd_intercepts.c:?)
   by 0x........: threadfunc (pth_barrier.c:?)
   by 0x........: vg_thread_wrapper (drd_intercepts.c:?)
   by 0x........: start_thread (in libpthread-?.?.so)
   by 0x........: clone (in /...libc...)
Other segment end (thread 3)
   at 0x........: __lll_mutex_lock_wait (in libpthread-?.?.so)
   by 0x........: pthread_barrier_wait (in libpthread-?.?.so)
   by 0x........: threadfunc (pth_barrier.c:?)
   by 0x........: vg_thread_wrapper (drd_intercepts.c:?)
   by 0x........: start_thread (in libpthread-?.?.so)
   by 0x........: clone (in /...libc...)

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
