
Attempt to unlock a mutex that is not locked: address 0x........, recursion count -1, owner 1.
   at 0x........: pthread_mutex_unlock (drd_intercepts.c:?)
   by 0x........: nearly_main (tc09_bad_unlock.c:27)
   by 0x........: main (tc09_bad_unlock.c:49)

Thread 2:
Mutex not unlocked by owner thread: address 0x........, recursion count 1, owner 1.
   at 0x........: pthread_mutex_unlock (drd_intercepts.c:?)
   by 0x........: child_fn (tc09_bad_unlock.c:11)
   by 0x........: vg_thread_wrapper (drd_intercepts.c:?)
   by 0x........: start_thread (in libpthread-?.?.so)
   by 0x........: clone (in /...libc...)

Thread 1:
Invalid mutex
   at 0x........: pthread_mutex_unlock (drd_intercepts.c:?)
   by 0x........: nearly_main (tc09_bad_unlock.c:41)
   by 0x........: main (tc09_bad_unlock.c:49)

Not a mutex
   at 0x........: pthread_mutex_unlock (drd_intercepts.c:?)
   by 0x........: nearly_main (tc09_bad_unlock.c:41)
   by 0x........: main (tc09_bad_unlock.c:49)

Mutex reinitialization: address 0x........, recursion count 0, owner 1.
   at 0x........: pthread_mutex_init (drd_intercepts.c:?)
   by 0x........: nearly_main (tc09_bad_unlock.c:23)
   by 0x........: main (tc09_bad_unlock.c:50)

Attempt to unlock a mutex that is not locked: address 0x........, recursion count -1, owner 1.
   at 0x........: pthread_mutex_unlock (drd_intercepts.c:?)
   by 0x........: nearly_main (tc09_bad_unlock.c:27)
   by 0x........: main (tc09_bad_unlock.c:50)

Thread 2:
Mutex not unlocked by owner thread: address 0x........, recursion count 1, owner 1.
   at 0x........: pthread_mutex_unlock (drd_intercepts.c:?)
   by 0x........: child_fn (tc09_bad_unlock.c:11)
   by 0x........: vg_thread_wrapper (drd_intercepts.c:?)
   by 0x........: start_thread (in libpthread-?.?.so)
   by 0x........: clone (in /...libc...)

Thread 1:
Invalid mutex
   at 0x........: pthread_mutex_unlock (drd_intercepts.c:?)
   by 0x........: nearly_main (tc09_bad_unlock.c:41)
   by 0x........: main (tc09_bad_unlock.c:50)

Not a mutex
   at 0x........: pthread_mutex_unlock (drd_intercepts.c:?)
   by 0x........: nearly_main (tc09_bad_unlock.c:41)
   by 0x........: main (tc09_bad_unlock.c:50)

ERROR SUMMARY: 9 errors from 9 contexts (suppressed: 0 from 0)
