Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:69)
   by 0x........: main (insn-pmovmskb.c:140)

0: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:73)
   by 0x........: main (insn-pmovmskb.c:140)

1: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:77)
   by 0x........: main (insn-pmovmskb.c:140)

2: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:81)
   by 0x........: main (insn-pmovmskb.c:140)

3: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:85)
   by 0x........: main (insn-pmovmskb.c:140)

4: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:89)
   by 0x........: main (insn-pmovmskb.c:140)

5: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:93)
   by 0x........: main (insn-pmovmskb.c:140)

6: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:97)
   by 0x........: main (insn-pmovmskb.c:140)

7: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:101)
   by 0x........: main (insn-pmovmskb.c:140)

8: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:105)
   by 0x........: main (insn-pmovmskb.c:140)

9: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:109)
   by 0x........: main (insn-pmovmskb.c:140)

10: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:113)
   by 0x........: main (insn-pmovmskb.c:140)

11: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:117)
   by 0x........: main (insn-pmovmskb.c:140)

12: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:121)
   by 0x........: main (insn-pmovmskb.c:140)

13: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:125)
   by 0x........: main (insn-pmovmskb.c:140)

14: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:129)
   by 0x........: main (insn-pmovmskb.c:140)

15: Invalid value is false
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:85)
   by 0x........: main (insn-pmovmskb.c:143)

4: Invalid value is true
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:89)
   by 0x........: main (insn-pmovmskb.c:143)

5: Invalid value is true
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:93)
   by 0x........: main (insn-pmovmskb.c:143)

6: Invalid value is true
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:97)
   by 0x........: main (insn-pmovmskb.c:143)

7: Invalid value is true
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:101)
   by 0x........: main (insn-pmovmskb.c:143)

8: Invalid value is true
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:105)
   by 0x........: main (insn-pmovmskb.c:143)

9: Invalid value is true
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:117)
   by 0x........: main (insn-pmovmskb.c:143)

12: Invalid value is true
Conditional jump or move depends on uninitialised value(s)
   at 0x........: use (insn-pmovmskb.c:48)
   by 0x........: doit (insn-pmovmskb.c:121)
   by 0x........: main (insn-pmovmskb.c:143)

13: Invalid value is true
