Syscall param posix_fadvise(fd) contains uninitialised byte(s)
   at 0x........: posix_fadvise (in /...libc...)
   by 0x........: main (posix_fadvise.c:16)

Syscall param posix_fadvise(offset) contains uninitialised byte(s)
   at 0x........: posix_fadvise (in /...libc...)
   by 0x........: main (posix_fadvise.c:17)

Syscall param posix_fadvise(len) contains uninitialised byte(s)
   at 0x........: posix_fadvise (in /...libc...)
   by 0x........: main (posix_fadvise.c:18)

Syscall param posix_fadvise(advice) contains uninitialised byte(s)
   at 0x........: posix_fadvise (in /...libc...)
   by 0x........: main (posix_fadvise.c:19)

