
All heap blocks were freed -- no leaks are possible

LEAK SUMMARY:
   definitely lost: 0 (+0) bytes in 0 (+0) blocks
   indirectly lost: 0 (+0) bytes in 0 (+0) blocks
     possibly lost: 0 (+0) bytes in 0 (+0) blocks
   still reachable: 40 (+40) bytes in 1 (+1) blocks
        suppressed: 0 (+0) bytes in 0 (+0) blocks
Reachable blocks (those to which a pointer was found) are not shown.
To see them, rerun with: --leak-check=full --show-leak-kinds=all

realloc() with size 0
   at 0x........: reallocf (vg_replace_malloc.c:...)
   by 0x........: main (reallocf.c:12)
 Address 0x........ is 0 bytes inside a block of size 40 alloc'd
   at 0x........: reallocf (vg_replace_malloc.c:...)
   by 0x........: main (reallocf.c:10)

All heap blocks were freed -- no leaks are possible

LEAK SUMMARY:
   definitely lost: 0 (+0) bytes in 0 (+0) blocks
   indirectly lost: 0 (+0) bytes in 0 (+0) blocks
     possibly lost: 0 (+0) bytes in 0 (+0) blocks
   still reachable: 40 (+0) bytes in 1 (+0) blocks
        suppressed: 0 (+0) bytes in 0 (+0) blocks
Reachable blocks (those to which a pointer was found) are not shown.
To see them, rerun with: --leak-check=full --show-leak-kinds=all

All heap blocks were freed -- no leaks are possible


HEAP SUMMARY:
    in use at exit: 0 bytes in 0 blocks
  total heap usage: 4 allocs, 4 frees, 562,949,953,421,393 bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For lists of detected and suppressed errors, rerun with: -s
ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
