
Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (xor-undef-x86.c:17)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (xor-undef-x86.c:38)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (xor-undef-x86.c:67)

ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 1 allocs, 1 frees, 48 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
