---Status---
debugging core file of coredump_single (32-bit) from ...
initial argv: ./coredump_single_thread
status: process terminated by SIGSEGV (Segmentation Fault), addr=........

---Registers---
%cs = 0x........            %eax = 0x00000101 
%ds = 0x........            %ebx = 0x00000102 
%ss = 0x........            %ecx = 0x00000103 
%es = 0x........            %edx = 0x00000104 
%fs = 0x........            %esi = 0x00000105 
%gs = 0x........            %edi = 0x00000106 

 %eip = 0x........  inner+0x........
%kesp = 0x00000000


   %esp = 0x00000108
%trapno = 0x0
   %err = 0x0

---Stack trace---
inner
outer
main
_start
