
Process terminating with default action of signal 11 (SIGSEGV)
 Access not within mapped region at address 0x........
   at 0x........: thread_func5 (coredump_many_threads.c:40)
   by 0x........: _thrp_setup (in /...libc...)
   by 0x........: ??? (in /...libc...)
 If you believe this happened as a result of a stack
 overflow in your program's main thread (unlikely but
 possible), you can try to increase the size of the
 main thread stack using the --main-stacksize= flag.
 The main thread stack size used in this run was ....
