Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:87)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:95)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:37)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:95)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:37)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:95)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:95)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:95)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:95)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:95)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_sse.c:95)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_sse.c:41)

