Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:84)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:43)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:91)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:43)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_gpr.c:91)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_gpr.c:39)

