Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_rflags2.c:85)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_rflags2.c:44)

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (context_rflags2.c:85)
 Uninitialised value was created by a heap allocation
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (context_rflags2.c:44)

