---------------------------------------------------------
166:         SYS_lwp_private 3s 1m
---------------------------------------------------------
Syscall param lwp_private(cmd) contains uninitialised byte(s)
   ...

Syscall param lwp_private(which) contains uninitialised byte(s)
   ...

Syscall param lwp_private(base) contains uninitialised byte(s)
   ...

Syscall param lwp_private(base) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

