---------------------------------------------------------
 54:               SYS_ioctl (CRYPTO_GET_PROVIDER_LIST) 3s 1m
---------------------------------------------------------
Syscall param ioctl(fd) contains uninitialised byte(s)
   ...

Syscall param ioctl(request) contains uninitialised byte(s)
   ...

Syscall param ioctl(arg) contains uninitialised byte(s)
   ...

Syscall param ioctl(CRYPTO_GET_PROVIDER_LIST, pl->pl_count) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

---------------------------------------------------------
 54:               SYS_ioctl (CRYPTO_GET_PROVIDER_LIST) 4s 0m
---------------------------------------------------------
Syscall param ioctl(fd) contains uninitialised byte(s)
   ...

Syscall param ioctl(request) contains uninitialised byte(s)
   ...

Syscall param ioctl(arg) contains uninitialised byte(s)
   ...

Syscall param ioctl(CRYPTO_GET_PROVIDER_LIST, pl->pl_count) points to uninitialised byte(s)
   ...
 Address 0x........ is on thread 1's stack

