#! /bin/sh

# Solaris libc prints 'Infinity' or 'infinity' instead of 'inf' and 'NaN' instead of 'nan'.
# Filter these differences here.
sed "s/-[Ii]nfinity/     -inf/g" |
sed "s/[Ii]nfinity/     inf/g"   |
sed "s/NaN/nan/g"

exit 0

