--------------------------------------------------------------------------------
Profile data file '../../cachegrind/tests/ann1.cgout'
--------------------------------------------------------------------------------
I1 cache:         32768 B, 64 B, 8-way associative
D1 cache:         32768 B, 64 B, 8-way associative
LL cache:         19922944 B, 64 B, 19-way associative
Profiled target:  ./a.out
Events recorded:  Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Events shown:     Ir I1mr ILmr
Event sort order: Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Thresholds:       99 0 0 0 0 0 0 0 0
Include dirs:     ../../cachegrind/tests/
User annotated:   
Auto-annotation:  on

--------------------------------------------------------------------------------
Ir        I1mr ILmr 
--------------------------------------------------------------------------------
5,229,753  952  931  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir        I1mr ILmr  file:function
--------------------------------------------------------------------------------
5,000,015    1    1  a.c:main
   47,993   19   19  /build/glibc-OTsEL5/glibc-2.27/elf/dl-lookup.c:do_lookup_x
   28,534   11   11  /build/glibc-OTsEL5/glibc-2.27/elf/dl-lookup.c:_dl_lookup_symbol_x
   28,136    7    7  /build/glibc-OTsEL5/glibc-2.27/elf/dl-tunables.c:__GI___tunables_init
   25,408   47   47  /build/glibc-OTsEL5/glibc-2.27/string/../sysdeps/x86_64/strcmp.S:strcmp
   21,821   23   23  /build/glibc-OTsEL5/glibc-2.27/elf/../sysdeps/x86_64/dl-machine.h:_dl_relocate_object
   11,521   15   15  /build/glibc-OTsEL5/glibc-2.27/elf/do-rel.h:_dl_relocate_object
    8,055    0    0  /build/glibc-OTsEL5/glibc-2.27/elf/dl-tunables.h:__GI___tunables_init
    6,898    2    2  /build/glibc-OTsEL5/glibc-2.27/elf/dl-misc.c:_dl_name_match_p

--------------------------------------------------------------------------------
-- Auto-annotated source: ../../cachegrind/tests/ + a.c
--------------------------------------------------------------------------------
Ir        I1mr ILmr 

        2    0    0  int main(void) {
        1    1    1     int z = 0;
3,000,004    0    0     for (int i = 0; i < 1000000; i++) {
2,000,000    0    0        z += i;
        .    .    .     }
        6    0    0     return z % 256;
        2    0    0  }

--------------------------------------------------------------------------------
The following files chosen for auto-annotation could not be found:
--------------------------------------------------------------------------------
  /build/glibc-OTsEL5/glibc-2.27/elf/../sysdeps/x86_64/dl-machine.h
  /build/glibc-OTsEL5/glibc-2.27/elf/dl-lookup.c
  /build/glibc-OTsEL5/glibc-2.27/elf/dl-misc.c
  /build/glibc-OTsEL5/glibc-2.27/elf/dl-tunables.c
  /build/glibc-OTsEL5/glibc-2.27/elf/dl-tunables.h
  /build/glibc-OTsEL5/glibc-2.27/elf/do-rel.h
  /build/glibc-OTsEL5/glibc-2.27/string/../sysdeps/x86_64/strcmp.S

--------------------------------------------------------------------------------
Ir        I1mr ILmr 
--------------------------------------------------------------------------------
5,000,015    1    1  events annotated

