--------------------------------------------------------------------------------
-- Cachegrind profile
--------------------------------------------------------------------------------
Files compared:   ann-diff2a.cgout; ann-diff2b.cgout
Command:          cmd1; cmd2
Data file:        ann-diff2c.cgout
Events recorded:  One Two
Events shown:     One Two
Event sort order: One Two
Threshold:        0.1
Include dirs:     
User annotated:   
Auto-annotation:  on

--------------------------------------------------------------------------------
-- Summary
--------------------------------------------------------------------------------
One            Two            

2,100 (100.0%) 1,900 (100.0%)  PROGRAM TOTALS

--------------------------------------------------------------------------------
-- Function summary
--------------------------------------------------------------------------------
One           Two            file:function

1,000 (47.6%) 1,000 (52.6%)  aux/ann-diff2-basic.rs:groffN
1,000 (47.6%) 1,000 (52.6%)  aux/ann-diff2-basic.rs:fN_ffN_fooN_F4_g5
  100  (4.8%)  -100 (-5.3%)  aux/ann-diff2-basic.rs:basic1

--------------------------------------------------------------------------------
-- Auto-annotated source file: aux/ann-diff2-basic.rs
--------------------------------------------------------------------------------
This file was unreadable

--------------------------------------------------------------------------------
-- Annotation summary
--------------------------------------------------------------------------------
One            Two            

    0              0             annotated: files known & above threshold & readable, line numbers known
    0              0             annotated: files known & above threshold & readable, line numbers unknown
2,100 (100.0%) 1,900 (100.0%)  unannotated: files known & above threshold & unreadable 
    0              0           unannotated: files known & below threshold
    0              0           unannotated: files unknown

