--------------------------------------------------------------------------------
-- Cachegrind profile
--------------------------------------------------------------------------------
Command:          ann2
Data file:        ann2.cgout
Events recorded:  A SomeCount VeryLongEventName
Events shown:     A SomeCount VeryLongEventName
Event sort order: A SomeCount VeryLongEventName
Threshold:        0.5
Include dirs:     ann2-no-such-dir
                  ann2-no-such-dir-2
                  ann2-aux
User annotated:   ann2-unmentioned.rs
                  ann2-no-such-file.rs
Auto-annotation:  on

--------------------------------------------------------------------------------
-- Summary
--------------------------------------------------------------------------------
A                SomeCount          VeryLongEventName 

100,000 (100.0%)   100,000 (100.0%)                 0  PROGRAM TOTALS

--------------------------------------------------------------------------------
-- Function summary
--------------------------------------------------------------------------------
A              SomeCount         VeryLongEventName        file:function

70,091 (70.1%)    90,291 (90.3%)                 0        ann2-basic.rs:f0
15,000 (15.0%)       600  (0.6%)                 0        ann2-basic.rs:f1
 9,000  (9.0%)     6,000  (6.0%)                 0        ann2-could-not-be-found.rs:f1
 2,000  (2.0%)       100  (0.1%)                 0        ann2-basic.rs:f2
 1,000  (1.0%)       500  (0.5%)                 0        ann2-via-I.rs:f1
 1,000  (1.0%)       300  (0.3%)            -1,000 (n/a)  ann2-past-the-end.rs:f1
-1,000 (-1.0%)         0                         0        ann2-negatives.rs:neg3
-1,000 (-1.0%)         0                         0        ann2-negatives.rs:neg2
 1,000  (1.0%)         0                         0        ann2-more-recent-than-cgout.rs:new
 1,000  (1.0%)         0                         0        ???:unknown
   500  (0.5%)         0                         0        ann2-basic.rs:f6
   500  (0.5%)         0                         0        ann2-basic.rs:f4

--------------------------------------------------------------------------------
-- Auto-annotated source file: ann2-basic.rs
--------------------------------------------------------------------------------
A              SomeCount         VeryLongEventName 

 7,100  (7.1%)       100  (0.1%)                 0  <unknown (line 0)>

-- line 2 ----------------------------------------
     .                 .                         .  two
     .                 .                         .  three
 5,000  (5.0%)       500  (0.5%)                 0  four
 5,000  (5.0%)       100  (0.1%)                 0  five
     .                 .                         .  six
70,091 (70.1%)    90,291 (90.3%)                 0  seven
     .                 .                         .  eight
   110  (0.1%)         9  (0.0%)                 0  nine
     .                 .                         .  ten
     .                 .                         .  eleven
   200  (0.2%)         0                         0  twelve
   200  (0.2%)         0                         0  thirteen
   100  (0.1%)         0                         0  fourteen
     0                 0                         0  fifteen
     0                 0                         0  sixteen
     0                 0                         0  seventeen
     0                 0                         0  eighteen
   499  (0.5%)     2,000  (2.0%)                 0  nineteen
   300  (0.3%)         0                         0  twenty

--------------------------------------------------------------------------------
-- Auto-annotated source file: ann2-could-not-be-found.rs
--------------------------------------------------------------------------------
This file was unreadable

--------------------------------------------------------------------------------
-- Auto-annotated source file: ann2-more-recent-than-cgout.rs
--------------------------------------------------------------------------------
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@ WARNING @@ WARNING @@ WARNING @@ WARNING @@ WARNING @@ WARNING @@ WARNING @@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ Source file 'ann2-more-recent-than-cgout.rs' is newer than data file 'ann2.cgout'.
@ Annotations may not be correct.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

A            SomeCount VeryLongEventName 

    .                .                 .  one
1,000 (1.0%)         0                 0  two
    .                .                 .  three
    .                .                 .  four
-- line 4 ----------------------------------------

--------------------------------------------------------------------------------
-- Auto-annotated source file: ann2-negatives.rs
--------------------------------------------------------------------------------
A                     SomeCount         VeryLongEventName       

    -2,000    (-2.0%)    -1,000 (-1.0%)              -990 (n/a)  <unknown (line 0)>

     2,000     (2.0%)     2,000  (2.0%)             2,000 (n/a)  one
    -1,000    (-1.0%)    -1,000 (-1.0%)                 0        two
         .                    .                         .        three
         .                    .                         .        four
   999,000   (999.0%)         0                  -150,000 (n/a)  five
-1,000,000 (-1000.0%)         0                   150,000 (n/a)  six
         .                    .                         .        seven
         .                    .                         .        eight
         .                    .                         .        nine
   -10,000   (-10.0%)         0                        10 (n/a)  ten
    10,000    (10.0%)         0                       -20 (n/a)  eleven
         .                    .                         .        twelve
         .                    .                         .        thirteen
-- line 13 ----------------------------------------

--------------------------------------------------------------------------------
-- User-annotated source file: ann2-no-such-file.rs
--------------------------------------------------------------------------------
This file was unreadable

--------------------------------------------------------------------------------
-- Auto-annotated source file: ann2-past-the-end.rs
--------------------------------------------------------------------------------
A          SomeCount        VeryLongEventName       

200 (0.2%)       100 (0.1%)                 0        one
  .                .                        .        two
  .                .                        .        three
-- line 3 ----------------------------------------
-- line 18 ----------------------------------------
300 (0.3%)       100 (0.1%)                 0        <bogus line 20>
300 (0.3%)       100 (0.1%)                 0        <bogus line 21>
200 (0.2%)         0                   -1,000 (n/a)  <bogus line 22>

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@ WARNING @@ WARNING @@ WARNING @@ WARNING @@ WARNING @@ WARNING @@ WARNING @@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@ Information recorded about lines past the end of 'ann2-past-the-end.rs'.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

--------------------------------------------------------------------------------
-- User-annotated source file: ann2-unmentioned.rs
--------------------------------------------------------------------------------
This file was not mentioned by the data file

--------------------------------------------------------------------------------
-- Auto-annotated source file: ann2-aux/ann2-via-I.rs
--------------------------------------------------------------------------------
A            SomeCount        VeryLongEventName 

1,000 (1.0%)       500 (0.5%)                 0  one

--------------------------------------------------------------------------------
-- Annotation summary
--------------------------------------------------------------------------------
A              SomeCount         VeryLongEventName       

84,500 (84.5%)    94,700 (94.7%)               990 (n/a)    annotated: files known & above threshold & readable, line numbers known
 5,100  (5.1%)      -900 (-0.9%)              -990 (n/a)    annotated: files known & above threshold & readable, line numbers unknown
 9,000  (9.0%)     6,000  (6.0%)                 0        unannotated: files known & above threshold & unreadable 
   400  (0.4%)       200  (0.2%)                 0        unannotated: files known & below threshold
 1,000  (1.0%)         0                         0        unannotated: files unknown

