--------------------------------------------------------------------------------
I1 cache:         32768 B, 64 B, 8-way associative
D1 cache:         32768 B, 64 B, 8-way associative
LL cache:         19922944 B, 64 B, 19-way associative
Command:          ./a.out
Data file:        cgout-test
Events recorded:  Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Events shown:     Dw Dr Ir
Event sort order: Dr
Thresholds:       0.1
Include dirs:     
User annotated:   a.c
Auto-annotation:  off

--------------------------------------------------------------------------------
Dw              Dr                 Ir                 
--------------------------------------------------------------------------------
18,005 (100.0%) 4,057,955 (100.0%) 5,229,753 (100.0%)  PROGRAM TOTALS

--------------------------------------------------------------------------------
Dw            Dr                Ir                 file:function
--------------------------------------------------------------------------------
    3  (0.0%) 4,000,004 (98.6%) 5,000,015 (95.6%)  a.c:main
4,543 (25.2%)    17,566  (0.4%)    47,993  (0.9%)  /build/glibc-OTsEL5/glibc-2.27/elf/dl-lookup.c:do_lookup_x
3,083 (17.1%)     5,750  (0.1%)    28,534  (0.5%)  /build/glibc-OTsEL5/glibc-2.27/elf/dl-lookup.c:_dl_lookup_symbol_x
    8  (0.0%)     5,521  (0.1%)    28,136  (0.5%)  /build/glibc-OTsEL5/glibc-2.27/elf/dl-tunables.c:__GI___tunables_init
2,490 (13.8%)     5,219  (0.1%)    21,821  (0.4%)  /build/glibc-OTsEL5/glibc-2.27/elf/../sysdeps/x86_64/dl-machine.h:_dl_relocate_object
    0             5,158  (0.1%)    25,408  (0.5%)  /build/glibc-OTsEL5/glibc-2.27/string/../sysdeps/x86_64/strcmp.S:strcmp

--------------------------------------------------------------------------------
-- User-annotated source: a.c
--------------------------------------------------------------------------------
Dw        Dr                Ir                

 1 (0.0%)         0                 2  (0.0%)  int main(void) {
 1 (0.0%)         0                 1  (0.0%)     int z = 0;
 1 (0.0%) 2,000,001 (49.3%) 3,000,004 (57.4%)     for (int i = 0; i < 1000000; i++) {
 0        2,000,000 (49.3%) 2,000,000 (38.2%)        z += i;
 .                .                 .             }
 0                1  (0.0%)         6  (0.0%)     return z % 256;
 0                2  (0.0%)         2  (0.0%)  }

--------------------------------------------------------------------------------
Dw        Dr                Ir                
--------------------------------------------------------------------------------
 3 (0.0%) 4,000,004 (98.6%) 5,000,015 (95.6%)  events annotated

