--------------------------------------------------------------------------------
Files compared:   cgout-test; cgout-test2
Command:          ./a.out; ./a.out
Data file:        cgout-diff
Events recorded:  Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Events shown:     Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Event sort order: Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Threshold:        0.1
Include dirs:     
User annotated:   
Auto-annotation:  on

--------------------------------------------------------------------------------
Ir                 I1mr ILmr Dr                  D1mr DLmr Dw D1mw DLmw 
--------------------------------------------------------------------------------
5,000,000 (100.0%)    0    0 -2,000,000 (100.0%)    0    0  0    0    0  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir                 I1mr ILmr Dr                  D1mr DLmr Dw D1mw DLmw  file:function
--------------------------------------------------------------------------------
5,000,000 (100.0%)    0    0 -2,000,000 (100.0%)    0    0  0    0    0  a.c:main

--------------------------------------------------------------------------------
-- Auto-annotated source: a.c
--------------------------------------------------------------------------------
Ir                 I1mr ILmr Dr                  D1mr DLmr Dw D1mw DLmw 

5,000,000 (100.0%)    0    0 -2,000,000 (100.0%)    0    0  0    0    0  <unknown (line 0)>


--------------------------------------------------------------------------------
Ir                 I1mr ILmr Dr                  D1mr DLmr Dw D1mw DLmw 
--------------------------------------------------------------------------------
        0             0    0          0             0    0  0    0    0    annotated: files known & above threshold & readable, line numbers known
5,000,000 (100.0%)    0    0 -2,000,000 (100.0%)    0    0  0    0    0    annotated: files known & above threshold & readable, line numbers unknown
        0             0    0          0             0    0  0    0    0  unannotated: files known & above threshold & unreadable 
        0             0    0          0             0    0  0    0    0  unannotated: files known & below threshold
        0             0    0          0             0    0  0    0    0  unannotated: files unknown

