--------------------------------------------------------------------------------
Files compared:   cgout-test; cgout-test2
Command:          ./a.out; ./a.out
Data file:        cgout-diff
Events recorded:  Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Events shown:     Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Event sort order: Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw
Thresholds:       0.1 100 100 100 100 100 100 100 100
Include dirs:     
User annotated:   
Auto-annotation:  on

--------------------------------------------------------------------------------
Ir                 I1mr       ILmr       Dr                  D1mr       DLmr       Dw         D1mw       DLmw       
--------------------------------------------------------------------------------
5,000,000 (100.0%) 0          0          -2,000,000 (100.0%) 0          0          0          0          0           PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir                 I1mr       ILmr       Dr                  D1mr       DLmr       Dw         D1mw       DLmw        file:function
--------------------------------------------------------------------------------
5,000,000 (100.0%) 0          0          -2,000,000 (100.0%) 0          0          0          0          0           a.c:main

--------------------------------------------------------------------------------
-- Auto-annotated source: a.c
--------------------------------------------------------------------------------
Ir                 I1mr       ILmr       Dr                  D1mr       DLmr       Dw         D1mw       DLmw       


5,000,000 (100.0%) 0          0          -2,000,000 (100.0%) 0          0          0          0          0           <counts for unidentified lines in a.c>

--------------------------------------------------------------------------------
Ir I1mr ILmr Dr D1mr DLmr Dw D1mw DLmw 
--------------------------------------------------------------------------------
.          .          .          .          .          .          .          .          .           events annotated

