#! /bin/sh

dir=`dirname $0`

$dir/../../tests/filter_stderr_basic                |

# Remove "Cachegrind, ..." line and the following copyright line.
sed "/^Cachegrind, an I1\/D1\/L2 cache profiler./ , /./ d" |

# Remove numbers from I/D/L2 "refs:" lines
sed "s/\(\(I\|D\|L2\) *refs:\)[ 0-9,()+rdw]*$/\1/"  |

# Remove numbers from I1/D1/L2/L2i/L2d "misses:" and "miss rates:" lines
sed "s/\(\(I1\|D1\|L2\|L2i\|L2d\) *\(misses\|miss rate\):\)[ 0-9,()+rdw%\.]*$/\1/" |

# Remove warnings lines for P4s:
sed "/warning: Pentium with 12 K micro-op instruction trace cache/d" |
sed "/Simulating a 16 KB cache with 32 B lines/d"

