#! /bin/sh

dir=`dirname $0`

$dir/../filter_stderr_basic                         |

# Remove numbers from I/D/L2 "refs:" lines
sed "s/\(\(I\|D\|L2\) *refs:\)[ 0-9,()+rdw]*$/\1/"  |

# Remove numbers from I1/D1/L2/L2i/L2d "misses:" and "miss rates:" lines
sed "s/\(\(I1\|D1\|L2\|L2i\|L2d\) *\(misses\|miss rate\):\)[ 0-9,()+rdw%\.]*$/\1/" 

