Invalid read of size 8
   at 0x........: main (fprw.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
   Address 0x........ is 0 bytes inside a block of size 8 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fprw.c:18)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid write of size 8
   at 0x........: main (fprw.c:20)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
   Address 0x........ is 0 bytes inside a block of size 8 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fprw.c:18)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid read of size 4
   at 0x........: main (fprw.c:21)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
   Address 0x........ is 0 bytes inside a block of size 4 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fprw.c:19)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid write of size 4
   at 0x........: main (fprw.c:21)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
   Address 0x........ is 0 bytes inside a block of size 4 free'd
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fprw.c:19)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...

Invalid free() / delete / delete[]
   at 0x........: free (vg_replace_malloc.c:...)
   by 0x........: main (fprw.c:22)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
   Address 0x........ is not stack'd, malloc'd or free'd

Invalid write of size 8
   at 0x........: main (fprw.c:24)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
   Address 0x........ is 0 bytes inside a block of size 4 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (fprw.c:23)
   by 0x........: __libc_start_main (...libc...)
   by 0x........: ...
