
searching for pointers to 1 not-freed blocks.
checked ... bytes.

LEAK SUMMARY:
   definitely lost: 0 bytes in 0 blocks.
     possibly lost: 0 bytes in 0 blocks.
   still reachable: 10 bytes in 1 blocks.
        suppressed: 0 bytes in 0 blocks.
Reachable blocks (those to which a pointer was found) are not shown.
To see them, rerun with: --show-reachable=yes

ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
malloc/free: in use at exit: 0 bytes in 0 blocks.
malloc/free: 1 allocs, 1 frees, 10 bytes allocated.
For a detailed leak analysis,  rerun with: --leak-check=yes
For counts of detected errors, rerun with: -v
