
Warning: invalid file descriptor -1 in syscall aio_read()
Syscall param aio_read(aiocbp->aio_buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Conditional jump or move depends on uninitialised value(s)
   at 0x........: main (aio.c:55)

Syscall param aio_write(aiocbp->aio_buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd


HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
  total heap usage: ... allocs, ... frees, ... bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
Use --track-origins=yes to see where uninitialised values come from
ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
