-----------------------------------------------------
x2000001(1):           __NR_exit below
-----------------------------------------------------
-----------------------------------------------------
x2000002(2):           __NR_fork other
-----------------------------------------------------
-----------------------------------------------------
x2000003(3):           __NR_read 1+3s 1m
-----------------------------------------------------
Syscall param (syscallno) contains uninitialised byte(s)
   ...

Syscall param read(fd) contains uninitialised byte(s)
   ...

Syscall param read(buf) contains uninitialised byte(s)
   ...

Syscall param read(count) contains uninitialised byte(s)
   ...

Syscall param read(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000004(4):          __NR_write 3s 1m
-----------------------------------------------------

Syscall param write(fd) contains uninitialised byte(s)
   ...

Syscall param write(buf) contains uninitialised byte(s)
   ...

Syscall param write(count) contains uninitialised byte(s)
   ...

Syscall param write(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000069(105):     __NR_setsockopt 5s 1m
-----------------------------------------------------

Syscall param setsockopt(s) contains uninitialised byte(s)
   ...

Syscall param setsockopt(level) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optname) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optval) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optlen) contains uninitialised byte(s)
   ...

Syscall param socketcall.setsockopt(optval) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000076(118):     __NR_getsockopt 5s 1m
-----------------------------------------------------

Syscall param getsockopt(s) contains uninitialised byte(s)
   ...

Syscall param getsockopt(level) contains uninitialised byte(s)
   ...

Syscall param getsockopt(optname) contains uninitialised byte(s)
   ...

Syscall param getsockopt(optval) contains uninitialised byte(s)
   ...

Syscall param getsockopt(optlen) contains uninitialised byte(s)
   ...

Syscall param socketcall.getsockopt(optlen) points to unaddressable byte(s)
   ...
 Address 0x........ is 0 bytes after a block of size 4 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (scalar.c:14)
-----------------------------------------------------
x20000a9(169):          __NR_csops 4s 1m
-----------------------------------------------------

Syscall param csops(pid) contains uninitialised byte(s)
   ...

Syscall param csops(ops) contains uninitialised byte(s)
   ...

Syscall param csops(useraddr) contains uninitialised byte(s)
   ...

Syscall param csops(usersize) contains uninitialised byte(s)
   ...

Syscall param csops(addr) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x20000df(223):   __NR_exchangedata 3s 2m
-----------------------------------------------------

Syscall param exchangedata(path1) contains uninitialised byte(s)
   ...

Syscall param exchangedata(path2) contains uninitialised byte(s)
   ...

Syscall param exchangedata(options) contains uninitialised byte(s)
   ...

Syscall param exchangedata(path1) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param exchangedata(path2) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000107(263):         __NR_shmctl 3s 1m
-----------------------------------------------------

Syscall param shmctl(shmid) contains uninitialised byte(s)
   ...

Syscall param shmctl(cmd) contains uninitialised byte(s)
   ...

Syscall param shmctl(buf) contains uninitialised byte(s)
   ...

Syscall param shmctl(IPC_STAT, buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000109(265):         __NR_shmget 3s 0m
-----------------------------------------------------

Syscall param shmget(key) contains uninitialised byte(s)
   ...

Syscall param shmget(size) contains uninitialised byte(s)
   ...

Syscall param shmget(shmflg) contains uninitialised byte(s)
   ...
-----------------------------------------------------
x200010c(268):       __NR_sem_open 2s 1m
-----------------------------------------------------

Syscall param sem_open(name) contains uninitialised byte(s)
   ...

Syscall param sem_open(oflag) contains uninitialised byte(s)
   ...

Syscall param sem_open(name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x200010c(268):       __NR_sem_open (4-args) 2s 0m
-----------------------------------------------------

Syscall param sem_open(mode) contains uninitialised byte(s)
   ...

Syscall param sem_open(value) contains uninitialised byte(s)
   ...
-----------------------------------------------------
x200010d(269):      __NR_sem_close 1s 0m
-----------------------------------------------------

Syscall param sem_close(sem) contains uninitialised byte(s)
   ...
-----------------------------------------------------
x200010e(270):     __NR_sem_unlink 1s 1m
-----------------------------------------------------

Syscall param sem_unlink(name) contains uninitialised byte(s)
   ...

Syscall param sem_unlink(name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x200010f(271):       __NR_sem_wait 1s 0m
-----------------------------------------------------

Syscall param sem_wait(sem) contains uninitialised byte(s)
   ...
-----------------------------------------------------
x2000110(272):    __NR_sem_trywait 1s 0m
-----------------------------------------------------

Syscall param sem_trywait(sem) contains uninitialised byte(s)
   ...
-----------------------------------------------------
x2000111(273):       __NR_sem_post 1s 0m
-----------------------------------------------------

Syscall param sem_post(sem) contains uninitialised byte(s)
   ...
-----------------------------------------------------
x2000113(275):       __NR_sem_init 3s 1m
-----------------------------------------------------

Syscall param sem_init(sem) contains uninitialised byte(s)
   ...

Syscall param sem_init(pshared) contains uninitialised byte(s)
   ...

Syscall param sem_init(value) contains uninitialised byte(s)
   ...

Syscall param sem_init(sem) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000114(276):    __NR_sem_destroy 1s 1m
-----------------------------------------------------

Syscall param sem_destroy(sem) contains uninitialised byte(s)
   ...

Syscall param sem_destroy(sem) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000117(279):  __NR_stat_extended 4s 4m
-----------------------------------------------------

Syscall param stat_extended(file_name) contains uninitialised byte(s)
   ...

Syscall param stat_extended(buf) contains uninitialised byte(s)
   ...

Syscall param stat_extended(fsacl) contains uninitialised byte(s)
   ...

Syscall param stat_extended(fsacl_size) contains uninitialised byte(s)
   ...

Syscall param stat_extended(file_name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param stat_extended(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param stat_extended(fsacl_size) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param stat_extended(fsacl) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000118(280): __NR_lstat_extended 4s 4m
-----------------------------------------------------

Syscall param lstat_extended(file_name) contains uninitialised byte(s)
   ...

Syscall param lstat_extended(buf) contains uninitialised byte(s)
   ...

Syscall param lstat_extended(fsacl) contains uninitialised byte(s)
   ...

Syscall param lstat_extended(fsacl_size) contains uninitialised byte(s)
   ...

Syscall param lstat_extended(file_name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lstat_extended(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lstat_extended(fsacl_size) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lstat_extended(fsacl) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000155(341):__NR_stat64_extended 4s 4m
-----------------------------------------------------

Syscall param stat64_extended(file_name) contains uninitialised byte(s)
   ...

Syscall param stat64_extended(buf) contains uninitialised byte(s)
   ...

Syscall param stat64_extended(fsacl) contains uninitialised byte(s)
   ...

Syscall param stat64_extended(fsacl_size) contains uninitialised byte(s)
   ...

Syscall param stat64_extended(file_name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param stat64_extended(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param stat64_extended(fsacl_size) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param stat64_extended(fsacl) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x2000156(342):__NR_lstat64_extended 4s 4m
-----------------------------------------------------

Syscall param lstat64_extended(file_name) contains uninitialised byte(s)
   ...

Syscall param lstat64_extended(buf) contains uninitialised byte(s)
   ...

Syscall param lstat64_extended(fsacl) contains uninitialised byte(s)
   ...

Syscall param lstat64_extended(fsacl_size) contains uninitialised byte(s)
   ...

Syscall param lstat64_extended(file_name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lstat64_extended(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lstat64_extended(fsacl_size) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Syscall param lstat64_extended(fsacl) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
x270f(9999):                9999 1e
-----------------------------------------------------
WARNING: unhandled syscall: unix:9999
You may be able to write your own handler.
Read the file README_MISSING_SYSCALL_OR_IOCTL.
Nevertheless we consider this a bug.  Please report
it at http://valgrind.org/support/bug_reports.html.
-----------------------------------------------------
x2000001(1):           __NR_exit 1s 0m
-----------------------------------------------------

Syscall param exit(status) contains uninitialised byte(s)
   ...
