-----------------------------------------------------
  1:           __NR_exit below
-----------------------------------------------------
-----------------------------------------------------
  2:           __NR_fork other
-----------------------------------------------------
-----------------------------------------------------
  3:           __NR_read 1+3s 1m
-----------------------------------------------------
Syscall param (syscallno) contains uninitialised byte(s)
   ...

Syscall param read(fd) contains uninitialised byte(s)
   ...

Syscall param read(buf) contains uninitialised byte(s)
   ...

Syscall param read(count) contains uninitialised byte(s)
   ...

Syscall param read(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
  4:          __NR_write 3s 1m
-----------------------------------------------------

Syscall param write(fd) contains uninitialised byte(s)
   ...

Syscall param write(buf) contains uninitialised byte(s)
   ...

Syscall param write(count) contains uninitialised byte(s)
   ...

Syscall param write(buf) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
105:     __NR_setsockopt 5s 1m
-----------------------------------------------------

Syscall param setsockopt(s) contains uninitialised byte(s)
   ...

Syscall param setsockopt(level) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optname) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optval) contains uninitialised byte(s)
   ...

Syscall param setsockopt(optlen) contains uninitialised byte(s)
   ...

Syscall param socketcall.setsockopt(optval) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
118:     __NR_getsockopt 5s 1m
-----------------------------------------------------

Syscall param getsockopt(s) contains uninitialised byte(s)
   ...

Syscall param getsockopt(level) contains uninitialised byte(s)
   ...

Syscall param getsockopt(optname) contains uninitialised byte(s)
   ...

Syscall param getsockopt(optval) contains uninitialised byte(s)
   ...

Syscall param getsockopt(optlen) contains uninitialised byte(s)
   ...

Syscall param socketcall.getsockopt(optlen) points to unaddressable byte(s)
   ...
 Address 0x........ is 0 bytes after a block of size 4 alloc'd
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (scalar.c:13)
-----------------------------------------------------
169:          __NR_csops 4s 1m
-----------------------------------------------------

Syscall param csops(pid) contains uninitialised byte(s)
   ...

Syscall param csops(ops) contains uninitialised byte(s)
   ...

Syscall param csops(useraddr) contains uninitialised byte(s)
   ...

Syscall param csops(usersize) contains uninitialised byte(s)
   ...

Syscall param csops(addr) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
265:         __NR_shmget 3s 0m
-----------------------------------------------------

Syscall param shmget(key) contains uninitialised byte(s)
   ...

Syscall param shmget(size) contains uninitialised byte(s)
   ...

Syscall param shmget(shmflg) contains uninitialised byte(s)
   ...
-----------------------------------------------------
268:       __NR_sem_open 2s 1m
-----------------------------------------------------

Syscall param sem_open(name) contains uninitialised byte(s)
   ...

Syscall param sem_open(oflag) contains uninitialised byte(s)
   ...

Syscall param sem_open(name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
268:       __NR_sem_open (4-args) 2s 0m
-----------------------------------------------------

Syscall param sem_open(mode) contains uninitialised byte(s)
   ...

Syscall param sem_open(value) contains uninitialised byte(s)
   ...
-----------------------------------------------------
269:      __NR_sem_close 1s 0m
-----------------------------------------------------

Syscall param sem_close(sem) contains uninitialised byte(s)
   ...
-----------------------------------------------------
270:     __NR_sem_unlink 1s 1m
-----------------------------------------------------

Syscall param sem_unlink(name) contains uninitialised byte(s)
   ...

Syscall param sem_unlink(name) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
273:       __NR_sem_post 1s 0m
-----------------------------------------------------

Syscall param sem_post(sem) contains uninitialised byte(s)
   ...
-----------------------------------------------------
275:       __NR_sem_init 3s 1m
-----------------------------------------------------

Syscall param sem_init(sem) contains uninitialised byte(s)
   ...

Syscall param sem_init(pshared) contains uninitialised byte(s)
   ...

Syscall param sem_init(value) contains uninitialised byte(s)
   ...

Syscall param sem_init(sem) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
276:    __NR_sem_destroy 1s 1m
-----------------------------------------------------

Syscall param sem_destroy(sem) contains uninitialised byte(s)
   ...

Syscall param sem_destroy(sem) points to unaddressable byte(s)
   ...
 Address 0x........ is not stack'd, malloc'd or (recently) free'd
-----------------------------------------------------
420:__NR_sem_wait_nocancel 1s 0m
-----------------------------------------------------

Syscall param sem_wait_nocancel(sem) contains uninitialised byte(s)
   ...
-----------------------------------------------------
9999:                9999 1e
-----------------------------------------------------
WARNING: unhandled syscall: 33564431
           a.k.a.: 9999
You may be able to write your own handler.
Read the file README_MISSING_SYSCALL_OR_IOCTL.
Nevertheless we consider this a bug.  Please report
it at http://valgrind.org/support/bug_reports.html.
-----------------------------------------------------
  1:           __NR_exit 1s 0m
-----------------------------------------------------

Syscall param exit(status) contains uninitialised byte(s)
   ...
