name: Test

on:
  workflow_dispatch:
  push:
    # Comment out to trigger
    # branches:
    #   - nothing/will/match

env:
  I_ACKNOWLEDGE_THIS_MIGHT_CRASH_OR_DAMAGE_MY_COMPUTER: yes

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26

    runs-on: ${{ matrix.os }}

    name: Test on ${{matrix.os}}

    steps:
      - name: checkout project
        uses: actions/checkout@v3
      - name: install Valgrind
        run: |
          brew install --HEAD LouisBrunner/valgrind/valgrind
        env:
          HOMEBREW_I_ACKNOWLEDGE_THIS_MIGHT_CRASH_OR_DAMAGE_MY_COMPUTER: yes
      - name: Build sysctl tester
        run: |
          cc -o sysctl_tester .github/sysctl_tester.c
      - name: Run sysctl tester
        run: |
          valgrind --trace-syscalls=yes ./sysctl_tester
